- content/articles/products/accessibility/policy.mdx
accessibility@smarthr.co.jp を作ったので、アクセシビリティ関係の問い合わせに利用したい
- ウェブアクセシビリティ方針の問い合わせ先をGitHubのissuesのURLからメールアドレスに変更
- 特にナシ
- メールアドレスクリックでメールが送信できるか
- メールアドレスが間違ってないか
|Before|After|
| --- | --- |
| <img width="530" alt="画面のスクショ。問い合わせ先 リンク:https://github.com/kufu/smarthr-ui/issues" src="https://user-images.githubusercontent.com/6724665/164176323-3a898cea-8c4f-4655-9ac1-2f8e8cb85e1b.png"> | <img width="479" alt="画面のスクショ。問い合わせ先 株式会社SmartHR プログレッシブデザイングループ リンク accessibility@smarthr.co.jp" src="https://user-images.githubusercontent.com/6724665/164175990-9cb3ee31-3d5a-474a-8055-310f9a146b4a.png"> |
> feat: add contact email address to web accessibility policy

- src/__generated__/gatsby-types.ts
- src/gatsby-node/index.ts
https://github.com/kufu/smarthr-design-system-issues/issues/893 に関連して、#34 でmdxのfrontmatterに対するGraphQLクエリの型定義を追加したが、その後コンポーネントページ冒頭のリンクが表示されなくなっていました。
型定義があると、GraphQLからfrontmatterの`smarthr-ui`（クエリ内では `smarthr_ui`）を取得しても`null`になってしまうようなので、いったん定義を削除しました。
https://deploy-preview-38--smarthr-design-system.netlify.app/products/components/accordion-panel/
|Before|After|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/7822534/165695037-d8afcc24-1e47-49da-8e0f-aded5d0ff5ec.png" width="350" alt=""> | <img src="https://user-images.githubusercontent.com/7822534/165695125-7257f205-3eaa-4e1d-bcab-33ecbf7c3f4d.png" width="350"  alt=""> |
> コンポーネントページにsmarthr-ui関連の情報が表示されなくなっていたので修正

- package.json
- src/components/contents/BasicConceptTable/BasicConceptTable.tsx
- src/components/contents/IdiomaticUsageTable/IdiomaticUsageTable.tsx
- yarn.lock
https://github.com/kufu/smarthr-design-system-issues/issues/894
https://github.com/kufu/smarthr-design-system-issues/issues/911
- Airtable由来のコンテンツのうち、`description`部分でマークダウンを利用できるようにしました
- [Marked](https://www.npmjs.com/package/marked) パッケージを導入しました
- [用事用語一覧ページ](https://smarthr.design/products/contents/idiomatic-usage/data/) で、コンテンツの量によりテーブル幅が広がっているようなので、横スクロールを追加しました。
**マークダウン記法の反映**
https://deploy-preview-35--smarthr-design-system.netlify.app//products/contents/writing-style/
https://deploy-preview-35--smarthr-design-system.netlify.app//products/contents/idiomatic-usage/usage/
行頭が「-」のコンテンツなどは、すでにマークダウン変換がされています→ https://deploy-preview-35--smarthr-design-system.netlify.app/products/contents/writing-style/#recrVEn3NYr2AV33o-0
リンクについては、URLを「()」で囲う必要がありそうです。
**テーブルの横スクロール** …
> Airtableコンテンツでマークダウンが利用できるように

- content/articles/products/components/dialog.mdx
ダイアログの実装方法を検討中、ガイドラインの「ESCキー押下でダイアログを閉じる」にデモが準拠していないことに気付いたので、修正しました。
https://kufuinc.slack.com/archives/C02NUAT7P0X/p1652322660794599?thread_ts=1652319019.097679&cid=C02NUAT7P0X
- ActionDialogとMessageDialogのプロパティにonPressEscapeを追加しました。
- ModelessDialogは元々onPressEscapeプロパティが指定されていたので、修正していません。
- Previewで確認をお願いします。
> ESCキー押下でデモのダイアログを閉じるように修正

- .eslintrc.js
- package.json
- yarn.lock
影響が広そうなのと、設定がいまいちなので npm scripts にはしていない。
> ローカルの VS Code 環境で mdx に対しても eslint がかかるように設定

- src/__generated__/gatsby-types.ts
- src/components/contents/AppWriting/AppWriting.tsx
- src/components/contents/BasicConceptTable/BasicConceptTable.tsx
- src/components/contents/IdiomaticUsageTable/IdiomaticUsageTable.tsx
- src/constants/airtable.ts
- src/templates/article.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/933
- Airtableデータから`order`も取得するようにしました。
- もし`order`が入っていない場合は、最大値をセットして一番後ろになるようにしています。
- AppwritingとBasicConceptTableでは`order`の昇順でコンテンツ・右サイドバーに出力されます。
- `/src/constants/airtable.ts` に`sort: 'AIRTABLE'`とあるものが対象です。（用字用語はこれまでどおり文字列順でのソートです）
また、GraphQLクエリを編集したため、`typegen`を実行して型定義をも更新しています。
（まだ型のエラーが出ていますが、別途Airtable関連コンポーネントをリファクタリングする際に対応したいです。）
- https://github.com/kufu/smarthr-design-system-issues/issues/937 のリファクタリング
- 型エラーの対応
https://deploy-preview-84--smarthr-design-system.netlify.app/products/contents/app-writing/
https://deploy-preview-84--smarthr-design-system.netlify.app/products/contents/writing-style/
（以前と変わらず）
https://deploy-preview-84--smarthr-design-system.netlify.app/products/contents/idiomatic-usage/usage/ …
> Airtableの`order`順にソートして表示する

- src/__generated__/gatsby-types.ts
- src/components/article/Sidebar/Sidebar.tsx
- src/gatsby-node/index.ts
- src/templates/article.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/898
コンテンツページ左カラムのナビゲーションメニューを更新しました。
- 表示中以外のページの子・孫ページのデータも取得しておき、ナビゲーションに追加しました。
- 子ページが存在する場合は、右端にキャレットを表示します。
- クリックすると、子ページのリストが開閉します。
実装としては、`aria-controls` `aria-expanded` `aria-hidden` 属性をJSで切り替え、さらにCSSで表示の制御をしています。
例 https://deploy-preview-86--smarthr-design-system.netlify.app/products/contents/
|Before|After|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/7822534/170618584-d9be6f00-d139-46cf-803d-7cf83abd05db.png" width="350" alt=""> | <img src="https://user-images.githubusercontent.com/7822534/170618645-0d453878-4e63-43b1-ad5d-ea1024ca5bb1.png" width="350" alt=""> |
> 左ナビゲーションに子ページの開閉機能を追加

- src/components/contents/AppWriting/AppWriting.tsx
- src/components/contents/BasicConceptTable/BasicConceptTable.tsx
- src/components/contents/IdiomaticUsageTable/IdiomaticUsageTable.tsx
- src/components/contents/shared/TextAnchor.tsx
- src/components/contents/shared/TextUrlToLink.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/937
Airtableのコンテンツを表示するコンポーネント（`/src/components/contents/*`）をリファクタリングしました。
**データをフィルタリングする場所**（https://github.com/kufu/smarthr-design-system/pull/72#discussion_r877831239 ）
→ ソートの手前に移動しました
**recordIdからfragmentIdを生成するところ** （https://github.com/kufu/smarthr-design-system/pull/72#discussion_r877837675 ）
→ `<FragmentTitle>`がstring型を受け取る実装になっているので、`recordId`がない場合はデータの通し番号を使うように書き換えました。また、関数名を動詞に変更しています。
**URLをリンクに変換して表示するところ** （https://github.com/kufu/smarthr-design-system/pull/72#discussion_r877843981 ）
→ 3つのコンポーネントで共通の処理をしていたので、コンポーネントとして独立させました。ひとまず`/src/components/contents/shared/TextAnchor.tsx`というファイルにしましたがどうでしょうか。
型定義については、Airtable関連の型エラーは現在は出なくなっていたため、何もしていません。
https://deploy-preview-93--smarthr-design-system.netlify.app/products …
> Airtableコンテンツ用のコンポーネントをリファクタリング

- src/components/ComponentPreview/ComponentPreview.tsx
- src/components/ComponentPropsTable/ComponentPropsTable.tsx
- src/components/article/CodeBlock/CodeBlock.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/951
ESLintでの警告、TypeScriptのエラーが出ている部分を修正、または調査の上無視するよう設定しました。
- `src/components/ComponentPreview/ComponentPreview.tsx`にて、`useMemo`の依存配列がESLintの`react-hooks/exhaustive-deps`ルールに引っ掛かっていたので、修正しました。
- `src/components/ComponentPropsTable/ComponentPropsTable.tsx`で`smarthr-ui-props.json`を読み込みますが、このJSON由来のpropsオブジェクトに型が定義されていなかったため、追加しました。
- `src/components/article/CodeBlock/CodeBlock.tsx`で、[react-live](https://github.com/FormidableLabs/react-live)のコンポーネントのpropsについて2つ型エラーが出ていますが、これはreact-live側の型定義に問題があるようで、PRも出ていたので（マージはされていませんでしたが）、その旨コメントを追加してエラーは無視するようにしました。
- `node_modules`以下のコードに由来するTSエラーについては何もしていません。
- `src/components/article/CodeBlock/CodeBlock.tsx`で、styled-componentsの`<ThemeProvider …
> lintの警告、TypeScriptの型エラーに対処

- content/articles/products/components/dialog.mdx
- content/articles/products/contents/error-messages-guide.mdx
- content/articles/products/design-patterns/delete-dialog.mdx
- content/articles/products/design-patterns/help-link.mdx
https://github.com/kufu/smarthr-design-system-issues/issues/968
- Airtableで出力されるiframeのコードに含まれている（と思われる）`onmousewheel`を削除
- React要素のstyle属性では、`box-sizing`ではなく`boxSizing`と記述するように変更
もう1点、[ヘルプページへの動線](https://smarthr.design/products/design-patterns/help-link/) ページで、`visuallyHiddenText`という属性はない、という警告が出ていましたが、smarthr-uiのアイコン要素に指定されている属性で、そもそもアイコンが`import`されていないのが原因のようでした。
`import`を追加すると警告は消え、アイコンも表示されるようになりました。
見た目は変わっていないはずのページ例：
https://deploy-preview-109--smarthr-design-system.netlify.app/products/design-patterns/delete-dialog/
アイコンの`import`を追加したページ
https://deploy-preview-109--smarthr-design-system.netlify.app/products/design-patterns/help-link/#h3-2
アイコンの表示が意図したものになっているでしょうか？
|Before|After|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/7822534/172331132-61173fbe-c88e-4 …
> 開発コンソールに出ていたReactの警告に対処

- src/components/index/Faq/FaqItem.tsx
- src/components/shared/RoundedBoxLink/RoundedBoxLink.tsx
- src/components/shared/RoundedBoxLink/index.tsx
- src/templates/article.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/952
各記事ページ下部の「次へ」ナビゲーションを改良しました。
- ページタイトルの追加
- UIをトップ＞よくある質問と同じに（コンポーネントも共通化しました→ `/src/components/shared/RoundedBoxLink`)
- コンポーネント名にもっと良さそうなものがあれば変えたいです
- 「前へ」も追加
また、ページの並び順について、プロダクト→コンポーネント 以下のページのみ、frontmatterの`order`ではなくページタイトル（＝コンポーネントの名前）順にするのが正しいかと思いますが、プロダクト→コンポーネント以外のページでは`order`順になってしまっていたため、修正しました。（左サイドバーの開閉メニューを実装した際に考慮が漏れていました。）
https://deploy-preview-123--smarthr-design-system.netlify.app/concept/about/
https://deploy-preview-123--smarthr-design-system.netlify.app/products/contents/
**ナビゲーション**
|Before|After|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/7822534/173738357-bc6d4e9e-7c40-4881-946c-c290ec2f0b3b.png" alt="" width="350"> | <img …
> 「次へ」ナビゲーションの改良、関連する不具合の修正

- src/components/ComponentStory/ComponentStory.tsx
- src/components/ComponentStory/ResizableContainer.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/973
今までは、高さのみ簡易的にCSSの`resize`でリサイズできるようにしてありましたが、JSベースのUIに置き換えて幅もリサイズできるようになりました。
JSのコードがそれなりの量になるので、リサイズ機能の部分を新たにコンポーネントにしています（`/src/components/ComponentStory/ResizableContainer.tsx`）。
現状、スマートフォンサイズの場合もそのまま同じUIが出てきますが、ある程度幅が狭くなったら非表示にするなどしたほうがいいでしょうか？
一応、iPhoneでもリサイズできることは確認していますが、高さのほうはページ自体のスクロール動作と重なるため、あまり実用的ではなさそうです（何か調整すればもう少し使いやすくできるかもしれませんが）。
https://deploy-preview-124--smarthr-design-system.netlify.app/products/components/accordion-panel/
|Before|After|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/7822534/174230421-6d1d04c6-416a-4ad3-bd8a-e2dca1883127.png" width="350" alt=""> | <img src="https://user-images.githubusercontent.com/7822534/174230400-20e29200-301e-41aa-b213-0e38b996a473.png" …
> Storybookのiframeリサイズ機能をJSベースのものに置き換え

- src/components/index/Gotcha.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/978
- `vw`を使って`height`を計算せず、`aspect-ratio`プロパティを使うように変更しました。
- `aspect-ratio`をサポートしていない環境（主にSafari14以前）用には、`@supports not(...)`ルールで以前と同じ`height`の計算をするようにフォールバックしています。
また、そもそも上下のボーダーが太く見えていたのは、正確にはボーダーと画像の隙間から背景色（同じ水色）が見えていることが原因なのですが、上記の対応をしても画像が拡大・縮小される都合上、若干の余白が出てしまうポイント（画面幅）があるようでした。そこで、
- 画像に`object-fit: contain;`を指定していたが、`cover`に変更（画像の縦横比が表示エリアと異なる場合に画像が切れないようにという意図だったが、全て表示エリアに合わせたサイズになっているようなので。）
- 画像の周りに1pxのボーダーをつけていたが、`::after`疑似要素を利用して画像の上に1pxのボーダーを重ねる方法に変更　→ 1px未満の余白であればボーダーの下に隠れる
としてみました。Figmaでは画像に対して`inset`でボーダーが指定されていたので、それに近い表示にもなったかと思います。
https://deploy-preview-141--smarthr-design-system.netlify.app/
**aspect-ratioに変更Before/After**
|Before|After|
| --- | --- |
| <img …
> Gotchaの画像まわりの余白が出ないよう調整

- content/articles/products/contents/index.mdx
- src/__generated__/gatsby-types.ts
- src/components/article/PageIndex/PageIndex.tsx
- src/components/article/PageIndex/index.ts
https://github.com/kufu/smarthr-design-system-issues/issues/969
- 指定されたパス（slug）の子ページのインデックス（リンク＋Description）を表示するコンポーネントを追加しました
- コンポーネント本体→ `/src/components/article/PageIndex/PageIndex.tsx`
- 試しにコンポーネントを配置したページ→ `/content/articles/products/contents/index.mdx`
- `path` propsに`/products/contents/`のように指定すると、その子ページの一覧を表示します
- 表示順やページ名は各ページのfrontmatterから取得します
- `excludes` propsに指定されたページは除外します
- `<Description />`タグで指定された文字列があればそれを、なければfrontmatterのdescriptionを表示します
- `<Description />`タグ内の文字列は、マークダウンとして変換します。改行を入れたい場合は`{'\n'}`を入力します。（コード内の改行では反映されません。）
また、`/content/articles/products/contents/index.mdx`では、コメントによってTextLintが無効になっていたようですが、今回の`<Description />`タグなどが引っかかることはなさそうだったので、再度有効にしてみました。2点テキストを修正しましたが問題なさそうでしょうか？
```
リリースノートの目的と書く時 -> リリースノートの目的と書くとき
気になる点がある場合は 社内Slack -> 気になる点がある場合は、社内Slack …
```
> 目次を表示するコンポーネントを追加

- .storybook/preview.js
- content/articles/products/design-patterns/DesignPatternCodeBlock.tsx
- content/articles/products/design-patterns/select-company-account/SelectCompanyAccount.stories.tsx
- src/components/ComponentPreview/WrapperBase.tsx
- src/components/ComponentStory/ComponentStory.tsx
- src/components/ComponentStory/ResizableContainer.tsx
- src/components/article/CodeBlock/CodeBlock.tsx
- src/constants/application.ts
https://github.com/kufu/smarthr-design-system-issues/issues/974
iframeで埋め込んでいるsmarthr-uiのStorybook、ライブプレビューを実装しているデザインパターンのStorybookの両方に、別画面で開くリンクテキストを追加しました。
また、デザインパターンのStorybookにヘッダーを追加しました。
ヘッダーはStorybookのdecoratorで追加して見ました。ひとまずグローバルなdecorator（`/.storybook/preview.js`）には追加せず、コンポーネントのほう（`SelectCompanyAccount.stories.tsx`）に入れました。また、`body`に`padding`がついていたのですが、ヘッダーの周囲に余白がないほうがいいかと考えて`fullscreen`に変更しています。
https://deploy-preview-152--smarthr-design-system.netlify.app/products/components/accordion-panel/
https://deploy-preview-152--smarthr-design-system.netlify.app/products/design-patterns/select-company-account/
（↑こちらの別画面で開く、のリンク先はmainブランチのStorybookなのでヘッダーはないです。）
https://62992322cdff0a004aaf9263-yqiexbohnn.chromatic.com/?path=/story/selectcompanyaccount--select-company-account …
> Storybookに別画面で開くリンクを追加、ヘッダーを追加

- src/components/shared/GlobalStyle/GlobalStyle.tsx
Global Style に `word-break: break-all;` が指定されているので、改行位置によっては英単語が途中で折り返されてしまう。
```
具体的には「JIS X 8341-3:2016 高齢者・障害者等配慮設計指針－情報通信における
機器、ソフトウェア及びサービス－第3部：ウェブコンテンツ」、に加えて「Web C
ontent Accessibility Guidelines 2.1」に対応することを目標としています。
```
- グローバルスタイルから `word-break: break-all;` を削除
- リンク文字列まんまなリンクが折り返されないので、 `<a>` に `overflow-wrap: break-word` を指定。
- 
- word-break: break-all が無いと崩れるところがあればご指摘を…
|Before|After|
| --- | --- |
| <img width="643" alt="折り返されているスクショ。ContentのCの次に改行が入っている。" src="https://user-images.githubusercontent.com/6724665/176619462-c477d3ff-6fd3-48e6-83fb-e73c9a8afe87.png"> | <img width="637" alt="Screen Shot 2022-06-30 at 16 35 25" src="https://user-images.githubusercontent.com/6724665/176620054-cf6413d5-4924-4faf-bc9e-c38e188acf34.png"> |
Content が始まる前で折り返されるようになります。
> 英単語が改行途中で折り返されてしまうのを防ぐ

- src/components/ColorPalette/ColorPalette.tsx
- src/components/shared/GlobalStyle/GlobalStyle.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/992
ColorPaletteコンポーネント、グローバルCSSのテーブルセル（`th`、`td`）に`word-break: break-all;`を追加しました。
- ColorPalette：PC表示では4カラムでの表示になっていて幅が狭いので、文字列部分に`word-break: break-all;`を追加しました。
- テーブルセル：URLが入る場合などにテーブルが中央カラムからはみ出しているケースがあったため、グローバルCSSの`th, td`に`word-break: break-all;`を追加しました。
以前はグローバルCSSに`word-break: break-all;`があったこともあり、テーブルについては一律に指定してしまいましたが、例えば`th > a, td > a`にする、個別に指定する、などでも良いかもしれません。
https://deploy-preview-170--smarthr-design-system.netlify.app/products/design-tokens/color/#h2-3
https://deploy-preview-170--smarthr-design-system.netlify.app/downloads/#h2-1
|Before|After|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/7822534/177289301-aa0ec218-f569-4b85-989f-154ba2fc6b44.png" width="350" alt> | <img …
> テキストの折り返しが必要な部分のCSSを調整

- content/articles/accessibility/policy.mdx
- content/articles/accessibility/test/202105/index.mdx
- content/articles/accessibility/test/202112/index.mdx
- content/articles/operational-guideline/page-template/style-template.mdx
- content/articles/products/components/dialog.mdx
- content/articles/products/components/heading.mdx
- content/articles/products/components/table.mdx
- content/articles/products/design-tokens/typography.mdx
- src/components/ComponentPropsTable/ComponentPropsTable.tsx
- src/components/contents/IdiomaticUsageTable/IdiomaticUsageTable.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/993
smarthr-uiの、`Body`、`Head`、`Row`、`Cell`が使われていた部分を、`tbody`、`thead`、`tr`と`Th`、`Td`に置き換えました。
また、プロダクト＞コンポーネント＞Tableコンポーネントのページのコード例も変更しました。
https://deploy-preview-177--smarthr-design-system.netlify.app/accessibility/policy/
https://deploy-preview-177--smarthr-design-system.netlify.app/accessibility/test/202105/
https://deploy-preview-177--smarthr-design-system.netlify.app/accessibility/test/202112/
https://deploy-preview-177--smarthr-design-system.netlify.app/operational-guideline/page-template/style-template/
https://deploy-preview-177--smarthr-design-system.netlify.app/products/components/dialog/
https://deploy-preview-177--smarthr-design-system.netlify.app/products/components/heading/ …
> smarthr-uiで非推奨となったtable関連のコンポーネントを置き換え

- content/articles/operational-guideline/page-template/index.mdx
- content/articles/products/design-process/index.mdx
https://github.com/kufu/smarthr-design-system-issues/issues/997
.mdxファイル内で、子ページのリンク一覧を表示している箇所がありましたが、見出しの中にリンクを置くとビルド後に`a`タグが入れ子になるという事情があるため、PageIndexコンポーネントに置き換えました。
https://deploy-preview-178--smarthr-design-system.netlify.app/products/design-process/
https://deploy-preview-178--smarthr-design-system.netlify.app/operational-guideline/page-template/
アンカーリンクではなく、子ページへのリンクになるため、
- ホバー時にアンカーリンクのアイコンが出ない
- 右サイドバーに見出しリストが表示されない
の2点は変わりますが、それ以外の見た目の変化はありません。
> 子ページのリンクリストを表示するページで、PageIndexコンポーネントを使用するように変更

- src/components/ComponentPropsTable/ComponentPropsTable.tsx
- src/components/contents/IdiomaticUsageTable/IdiomaticUsageTable.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/1006
smarthr-uiの`Th`コンポーネントを使用していて、そこに独自のスタイルをあてる必要がある箇所を修正しました。具体的には、ComponentPropsTableとIdiomaticUsageTableの2つのコンポーネントです。
（`Cell`コンポーネントを`Th`と`Td`に分けた際の対応が不十分でした。）
https://deploy-preview-180--smarthr-design-system.netlify.app/products/components/button/#h2-5
https://deploy-preview-180--smarthr-design-system.netlify.app/products/contents/idiomatic-usage/data/ （←こちらは、現状ではthの中身がそれほど長くないので、見た目に変化はありません。）
|Before|After|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/7822534/179180796-a2a07211-3516-453f-b4c0-df14b51939d7.png" width="350" alt> | <img src="https://user-images.githubusercontent.com/7822534/179180892-b2c3a830-67f7-453b-8c7d-e091da10874f.png" width="350" alt> |
> Thコンポーネントのスタイルを修正

- src/components/shared/Header/Header.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/999
画面幅が768px〜1114pxの時の、ヘッダーメニューの各アイテムの左右の余白を縮めました。
また、スクロールバーを表示した状態＋画面幅が1441px〜1448pxの場合、ヘッダーが2列になってしまうことも確認したので、こちらも調整しました（1406px〜1440pxは1列で収まるので、一瞬だけ2列になるような状態でした）。
https://deploy-preview-189--smarthr-design-system.netlify.app/
画面幅800pxでの比較
|Before|After|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/7822534/179671818-e6f8fc08-b934-4023-8edf-072b79b84e66.png" alt="" width="350"> | <img src="https://user-images.githubusercontent.com/7822534/179671969-584a3713-ac76-4073-9bf0-c4d12acd06ac.png" alt="" width="350"> |
画面幅1445pxでの比較
|Before|After|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/7822534/179675181-5ad6a758-c0fd-4c61-a919-39d1eadc1f49.png" alt="" width="350"> | <img …
> ヘッダーメニューの余白を調整

- content/articles/products/design-tokens/color.mdx
- https://github.com/kufu/smarthr-design-system-issues/issues/984
- SmartHR UIの色のアップデートに追従
- https://github.com/kufu/smarthr-ui/pull/2447
- 色のアップデート
- `TEXT_BLACK`
- `SCRIM`
- `OVERLAY`
- 色の新旧比較表を更新
- `SCRIM`と`OVERLAY`のrgba表示に透明度が反映されていない問題は別途
|Before|After|
| --- | --- |
|  |  |
> プロダクトの色をSmartHR UIの最新に追従する

- src/components/ComponentStory/ComponentStory.tsx
- https://github.com/kufu/smarthr-design-system/pull/181#issuecomment-1189876160
- https://github.com/kufu/smarthr-design-system-issues/issues/1010
Story名を抽出する正規表現の改修
- https://deploy-preview-194--smarthr-design-system.netlify.app/products/components/dropdown/
|Before|After|
| --- | --- |
| <img width="979" alt="image" src="https://user-images.githubusercontent.com/1369376/180108788-dd8dc960-cbe3-4bc2-aa98-0c2587679025.png"> | <img width="979" alt="image" src="https://user-images.githubusercontent.com/1369376/180108848-6e39e930-f6ff-44de-b3ba-fb48a127f24e.png"> |
> コードからストーリー名を抽出する際の正規表現を修正

- content/articles/products/design-tokens/color.mdx
- #190 でカラーコードを変更しましたが、誤っていたため修正します。
- https://github.com/kufu/smarthr-ui/blob/master/src/themes/createColor.ts#L32
- `SCRIM`と`OVERLAY`のカラーコードを修正しました。
|Before|After|
| --- | --- |
|  |  |
> SCRIMとOVERLAYのカラーコードを修正

- src/components/ComponentStory/ResizableContainer.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/1016
プロダクト>コンポーネント以下の各コンポーネントページで、
- iframeをラップしている`div`に`user-select: none;`のCSSを追加しました
- 横幅のドラッグ時に、幅100%に近づいたら（<20px）自動的に100%に吸着するようにしました
https://deploy-preview-208--smarthr-design-system.netlify.app/products/components/accordion-panel/
> コンポーネントのページのiframeのリサイズUIを改善

- src/components/search/Search/HitComponent.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/1019
祖先カテゴリー（基本要素やプロダクトなどの第二階層）の定義が`src/components/search/Search/HitComponent.tsx`に書かれていましたが、リニューアル前のカテゴリー定義のままで、「プロダクト」以外表示されなくなっていたので修正しました。
「|」の表示自体は変えていないです。カテゴリーが出るようになったので、末尾が「|」で終わるケースは、ダウンロードや利用規約などの一部のページのみです。
そういう場合は末尾の「|」を出さないようにしたほうが良いでしょうか？
https://deploy-preview-215--smarthr-design-system.netlify.app/search/
|Before|After|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/7822534/182752427-d82916ed-5739-46bb-a701-80eff639bb2b.png" width="350" alt> | <img src="https://user-images.githubusercontent.com/7822534/182752386-4ad08264-5860-41c6-b677-a202bd69c3cf.png" width="350" alt> |
> 検索結果に表示するカテゴリーのラベルを更新

- content/articles/products/design-patterns/components/index.ts
- content/articles/products/design-patterns/upward-navigation/UpwardNavigation.stories.tsx
- content/articles/products/design-patterns/upward-navigation/UpwardNavigation.tsx
- content/articles/products/design-patterns/upward-navigation/index.mdx
- src/components/ComponentPreview/ProductWrapper.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/1013
1. Upward navigationのコード例・プレビュー部分をコンポーネントの埋め込みから独立したStoryに変更しました
2. デザインパターンのStoryをプレビューしている部分（`layout='product'`で呼び出される`CodeBlock`コンポーネント）に、ドラッグで幅・高さを変更できる機能を追加しました。
- `products/components/`以下の、smarthr-uiのStoryを表示している部分と同様に、`ResizableContainer`コンポーネントでラップしています。 
https://deploy-preview-229--smarthr-design-system.netlify.app/products/design-patterns/upward-navigation/#h2-1
https://deploy-preview-229--smarthr-design-system.netlify.app/products/design-patterns/select-company-account/#h2-2
https://62992322cdff0a004aaf9263-frmsevrgym.chromatic.com/?path=/story/upwardnavigation--upward-navigation
|Before|After|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/7822534/183355443-665a16ab-6e39-4106-882c-f7a752da6222 …
> デザインパターンのコード例をStoryにする・プレビュー領域のサイズを可変にする

- content/articles/products/components/heading.mdx
- content/articles/products/design-tokens/leading.mdx
- content/articles/products/design-tokens/typography.mdx
- #214 で対応いただいたため、対象コンテンツに反映しました。
- Tdコンポーネントの中でデザイントークンを表記している部分を`<code>`で括りました。
- ついでに、行送りの使用状況が変わっていたので追従しました。
- Previewでみてね。
|Before|After|
| --- | --- |
|  |  |
> Tdコンポーネント内のデザイントークンをcodeタグで表記

- src/templates/article.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/1026
`src/templates/article.tsx`内にMDXコンテンツ全体に適用されるCSSが定義されていますが、`td`の中の`p`や入れ子になった`ul`の子要素などに意図しない上マージンが効いているケースがあったため、CSSを修正しました。
具体的には、`td`内の`p`、`ul`、`ol`の先頭の要素（`:first-child`）と、入れ子になった`ul`または`ol`の子の先頭の要素について、`margin-block-start: 0;`を追加しました。
https://deploy-preview-241--smarthr-design-system.netlify.app/products/design-tokens/typography/#h3-3
https://deploy-preview-241--smarthr-design-system.netlify.app/products/design-patterns/table-bulk-action/#h2-0
https://deploy-preview-241--smarthr-design-system.netlify.app/products/contents/help-center/#h3-3
https://deploy-preview-241--smarthr-design-system.netlify.app/products/contents/idiomatic-usage/data/
|Before|After|
| --- | --- |
| <img …
> MDXコンテンツ用のスタイルを調整

- content/articles/products/design-tokens/typography.mdx
- https://github.com/kufu/smarthr-design-system-issues/issues/1037
- タイポグラフィのリンクの記載内容を最新の基準でアップデートした
- [「よくあるテーブル」の遷移リンクのスタイル](/products/design-patterns/smarthr-table/#h5-0)がアップデートされていないが、別で対応する。
- Previewでみてね。
- https://deploy-preview-242--smarthr-design-system.netlify.app/products/design-tokens/typography/#h3-7
| Before | After |
| --- | --- |
| <img width="762" alt="image" src="https://user-images.githubusercontent.com/64398878/185554416-d8cfb35a-70af-4079-98c9-351e6de14bac.png"> | <img width="762" alt="image" src="https://user-images.githubusercontent.com/64398878/185554388-74dd96b4-8750-43ad-9c6a-50d08b0da61b.png"> |
> テキストリンクの装飾の基準を最新化する

- src/components/article/Sidebar/Sidebar.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/1054
第4階層が複数出てくる想定になっていなかったため、コードを修正しました。
開閉ボタンと開閉対象の要素を紐づけるために、配列のindexをベースにidを振っていますが、第4階層は4-1、4-2のようなidでは重複の可能性があるので、4-1-1、4-1-2…のようなidに変更しました。
https://deploy-preview-276--smarthr-design-system.netlify.app/products/design-process/usability-test/
> サイドバーの第4階層の開閉を修正

- content/articles/products/components/dialog.mdx
- コンポーネントのDialogのPropsに「Dialog」がなかったので追加した。
- 👆のとおり。
|Before|After|
| --- | --- |
|  |  |
> DialogのPropsテーブルを追加

- src/components/shared/GlobalStyle/GlobalStyle.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/1079
グローバルなCSS内で、`th`・`td`に対して`word-break: break-all;`が適用されていましたが、これを`break-word`に変更しました。
`break-all`が適用されているのは他に、
- カラーパレット（ https://smarthr.design/products/design-tokens/color/#h2-3 ）
- コードブロック
がありますが、これらはそのままです。
https://deploy-preview-329--smarthr-design-system.netlify.app/products/contents/idiomatic-usage/data/
ダウンロードページのテーブルにも影響しているはずですが、URLなどは折り返されているので大丈夫そうです。
https://deploy-preview-329--smarthr-design-system.netlify.app/downloads/#h2-1
|Before|After|
| --- | --- |
| ![image](https://user-images.githubusercontent.com/7822534/196334568-15d412a6-4151-4643-b9b1-62e7216e6222.png) | ![image](https://user-images.githubusercontent.com/7822534/196334594-b904a8fe-178f-42a7-9200-a06d0f4dfca9.png) |
> テーブル内のテキストは`break-all`→`break-word`に変更

- src/__generated__/gatsby-types.ts
- src/components/shared/Footer/Footer.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/1060
フッターのナビゲーションメニューにアクセシビリティカテゴリのページも追加しました。
https://deploy-preview-314--smarthr-design-system.netlify.app/
|Before|After|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/7822534/193749099-71523727-ddbd-4bdf-bdb3-3afd6d07efa0.png" alt="" width="350"> | <img src="https://user-images.githubusercontent.com/7822534/193749550-ceef5340-111a-46d2-b2c5-3ed9b023c680.png" alt="" width="350"> |
この各ページへのリンク部分は4カラムのレイアウトになっているため、基本原則を1カラム目に移動し、基本要素の下にアクセシビリティを入れたのが現在の状態です。
結果的に、フッター左端のログインボタンなどがあるカラムとの間の余白が減ってしまい、ちょっとアンバランスな印象かもしれません。
以下、解消できないか手元で試してみた方法です。
現状では↑の2と3の間の最小値は40pxなので、80pxに増やすと以下のようになります。
アクセシビリティカテゴリ以下のページタイトルのが比較的長いことが影響しているので、仮に縮められれば以下ようにはなります。ただし、画面幅が狭くなるとまた余白が縮んではきます。
**画面幅が広い**
**画面幅が狭い**
> フッターメニューにアクセシビリティを追加

- content/articles/basics/colors/printguideline.mdx
- content/articles/contact.mdx
印刷ガイドラインページに社外向けのフィードバック先を追加する #1072
[こちら](https://github.com/kufu/smarthr-design-system-issues/issues/1072)を確認
- 「印刷ガイドライン」のお問い合わせ先にメールアドレスを追加
- 「お問い合わせ」にメールアドレスを追加
- なし
|Before|After|
| --- | --- |
| <img width="1338" alt="CleanShot 2022-10-21 at 18 20 29@2x" src="https://user-images.githubusercontent.com/113964708/197163608-923bdbdc-e899-4b5a-b63c-034c9bb5d58c.png"> | <img width="1310" alt="CleanShot 2022-10-21 at 18 20 11@2x" src="https://user-images.githubusercontent.com/113964708/197163667-bab456e0-d53f-4734-8088-63bfad121c67.png"> |
> お問い合わせに専用メールアドレスを追加する

- src/components/shared/Footer/Footer.tsx
フッターのアクセシビリティのリンク先がプロダクトになっていたので、
アクセシビリティに変更しました
フッターのアクセシビリティのリンク先を`/accessibility/`に変更
https://deploy-preview-349--smarthr-design-system.netlify.app/
> アクセシビリティのリンクを修正

- src/plugins/gatsby-remark-index-id-header/index.js
https://github.com/kufu/smarthr-design-system-issues/issues/1106
`src/plugins/gatsby-remark-index-id-header/index.js`のコードで、参考にしたGatsby公式のプラグインと異なる点があり、意図した動作にもなってなさそうなので、修正しました。
結果として、.mdxに含まれるh2〜h6ノードが持つ`data`オブジェクトの中身が、
**before**  
`{ id: 'h2-3', htmlAttributes: 'h2-3', hProperties: { id: 'h2-3' } }`
**after**
`{ id: 'h2-3', htmlAttributes: { id: 'h2-3' }, hProperties: { id: 'h2-3' } }`
に変わってしまいますが、その後の処理では`id`propsをhtmlの`id`として使うので、動作には影響がなさそうです。
このあたり→ https://github.com/kufu/smarthr-design-system/blob/6f3e729cdeef71865308afd965cd31d65915b65a/src/templates/article.tsx#L29-L52
.mdx由来のページで、見出しへのアンカーリンクが以前と同様に動作していることを確認しました。
例：https://deploy-preview-347--smarthr-design-system.netlify.app/foundation/#h3-0
見た目の変化はありません。
> remark-pluginのコードを修正

- content/articles/basics/colors/index.mdx
- content/articles/communication/capture/kit.mdx
- content/articles/operational-guideline/page-template/style-template.mdx
- content/articles/products/design-tokens/color.mdx
- src/components/ColorPalette/ColorPalette.tsx
- デザイントークンに新しい色が追加されてたのでカラーパレットを追加して、既存のカテゴリーはセマンティックに変更
- 透明色が追加されたのでrgbaでも記述できるようにColor PaletteのI/Fを変更
-
https://deploy-preview-350--smarthr-design-system.netlify.app/products/design-tokens/color/
|Before|After|
| --- | --- |
|  |  |
> カラーパレットを追加、rgbaで記述できるように変更

- package.json
- yarn.lock
https://github.com/kufu/smarthr-design-system-issues/issues/1111
- `stylelint`のバージョンを最新の`14.14.1`にアップデート
- `stylelint-config-standard`のバージョンを最新の`29.0.0`にアップデート
- `postcss`のバージョンを`8.4.16`以上に固定（package.jsonに`resolutions`として追加）
[postcssのissueコメント](https://github.com/postcss/postcss/issues/1767#issuecomment-1216281818)を参考に、`8.4.16`以上を指定するとエラーにならなくなりました。
ローカルにて動作確認済み。
`yarn lint:style`を実行してもエラーにならず、`✨  Done in 3.24s.`のような表示が出ます。
わざとlintエラーとなるようなCSSを追加すると、エラーを検出しました。
stylelint実行時のCSSエラーはなかったため、CSSの変更はなく、見た目や動作に影響はありません。
> Stylelintの最新バージョンが動作しないため、PostCSSのバージョンを固定

- scripts/linkChecker.ts
https://github.com/kufu/smarthr-design-system-issues/issues/1130
リンク切れと判定していたもののうち、末尾にスラッシュがないだけで、リンク自体は機能しているものは、`Missing link:  ...`ではなく、`No trailing slash: ...`というエラーメッセージに変更しました。
（厳密には”リンク切れ”ではなく、末尾スラッシュをつけるという方針に沿っていないだけ、というものです。）
`npx ts-node scripts/linkChecker.ts`
↓
```
No trailing slash: /products/design-process/usability-test/planing_tips in /content/articles/products/design-process/usability-test/index.mdx at L:31
Found 1 missing links. Link check finished.
```
ビルドされるサイト自体には影響ありません。
（現時点では実際にはリンク切れ箇所はありませんでした。）
> リンクチェッカーのエラーメッセージを修正

- .gitignore
- README.md
- netlify.toml
https://github.com/kufu/smarthr-design-system-issues/issues/1131
devサーバー起動時に、
```
◈ No app server detected. Using simple static server
◈ Unable to determine public folder to serve files from. Using current working directory
◈ Setup a netlify.toml file with a [dev] section to specify your dev server settings.
◈ See docs at: https://cli.netlify.com/netlify-dev#project-detection
◈ Running static server from "smarthr-design-system"
◈ Setting up local development server
```
という表示が出ており、何らかの原因で、"No app server detected."な状態になっている様子でした。Gatsbyまたはnetlify-cliのアップデートにより、何か状況が変わったのかもしれません。（以前はGatsbyのdevサーバーを"detect"できていたと思うので。）
下の行にある、"◈ See docs at: 〜"の[リンク先](https://cli.netlify.com/netlify-dev#project-detection)を参考に、`netlify.toml`に、devサーバーの設定を追記しました。
あわせてREADME.mdの内容も更新しました。
- …
> Netlifyのdevサーバーの設定を調整

- gatsby-plugin-algolia-config.ts
- package.json
- yarn.lock
https://github.com/kufu/smarthr-design-system-issues/issues/1133
プラグインのリポジトリにある[CHANGELOG](https://github.com/algolia/gatsby-plugin-algolia/blob/master/CHANGELOG.md)を参考に、`gatsby-plugin-algolia-config.ts`を更新しました。
具体的には、
- `internal { contentDigest }`が必要になるため、GraqhQLクエリに追加
- `skipIndexing`オプションがなくなったため、`dryRun`に変更
しています。
テスト用にAlgolia環境を作り、`dryRun`せずにビルドするとindexが登録されることを確認しました。登録されたレコード数は162件でした。
`main`ブランチ以外では`dryRun`になるので、
```
==== THIS IS A DRY RUN ====================
- No records will be pushed to your index
- No settings will be updated on your index
```
のようなログが記録されるはずです。
サイトの見た目上の変化はありません。
> gatsby-plugin-algoliaをバージョンアップ

- .github/workflows/link-check.yml
https://github.com/kufu/smarthr-design-system-issues/issues/1125
`scripts/linkChecker.ts`を実行するGitHub Actionsを作成しました。月曜日のAM9時（日本時間）と、Actionsタブからの手動実行ができるようになっています。
リンクチェックでエラー（リンク切れなど）があった場合はこのリポジトリにissueが作成されます。
issueが作られた時の、Asigneesや通知などの設定は特に追加していません。
（Webサイト本体への影響はありません。）
エラーがあった場合、以下のようなissueが作成されます（テスト用リポジトリでの画面です）。
> リンクチェッカーを実行するGitHub Actionsを追加

- content/articles/basics/logos/index.mdx
- ロゴページのダウンロードセクションの表記に揺れがあったり、誤りがあったりしました。
- 記述記号を全角にする
- 参考：[記述記号は全角を使用し、前後にスペースは入れない](https://smarthr.design/products/contents/writing-style/#recrVEn3NYr2AV33o-0)
- ファイル形式間の区切りは、「・」を使用
- 参考：[複数の語句を列挙する場合の、読点（、）とナカグロ（・）の使い分け](https://smarthr.design/products/contents/writing-style/#recKGcTEWxvwUk5pp-0)
- ダウンロードできるテキストリンクは、「形式+ファイル」に。
- ユーザーがダウンロードするのは、ファイルなので。
- AIファイルのテキストリンクに、カラー or モノクロを記載
- データの内容を明示
- ファイル自体の調整
-  ドキュメントのみ調整しました
https://deploy-preview-387--smarthr-design-system.netlify.app/basics/logos/#h2-1
|Before|After|
| --- | --- |
| <img width="1376" alt="スクリーンショット 2022-11-22 15 11 03" src="https://user-images.githubusercontent.com/101125529/203238342-5211ceec-9a60-4b05-b3b6-a459255cdbc8.png"> | <img width="1352" alt="スクリーンショット 2022-11-22 15 16 18" …
> ロゴページのダウンロードセクション表記を調整

- gatsby-config.ts
- gatsby-ssr.ts
- src/components/Head/Head.tsx
- src/pages/404.tsx
- src/pages/index.tsx
- src/pages/login.tsx
- src/pages/search.tsx
- src/templates/article.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/1138
[gatsby-plugin-react-helmetが非推奨になる](https://www.gatsbyjs.com/plugins/gatsby-plugin-react-helmet/#%EF%B8%8F-this-package-will-be-deprecated)予定とのこと。おそらくreact-helmetの開発が停滞しているため。
現在、HTMLヘッダーに出力されているのと同じものを、[Gatsby Head API](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/)を利用して出力するようにしました。
- `<html>`要素に`lang="ja"`を指定
- [ドキュメント](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/#editing-html-and-body)に従って、`gatsby-ssr.ts`を追加しました
- `<title>`・`<meta>`・`<link>`
- `/src/components/Head/Head.tsx` からreact-helmetを削除し、直接記述しています。
各ページからは、[`Head`という名前でコンポーネントをexportする](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/#using-gatsby-head-in-your-page)必要があるため、`/src/pages/`以下の …
> react-helmetプラグインをGatsby Head APIに置き換え

- src/components/shared/RoundedBoxLink/RoundedBoxLink.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/1140
トップページのFAQや、前後の記事へのリンクに使われている`RoundedBoxLink`コンポーネントで、キャレットの位置やtext-alignを指定するためのprops（`caret`と`align`）がHTMLに出力されてしまい、その結果invalidなHTMLになっているようです。
`caret`と`align`は、styled-componentsがpropsとして受け取り、CSSの出し分けに使っている。
```
const BoxLink = styled(Link)<{ 'align': 'left' | 'center' | 'right'; 'caret': 'left' | 'right' }>`
text-align: ${({align}) => align};
...
`
```
`styled('a')`であれば、`align`や`caret`はHTMLには出力されなくなりますが、ここではgatsby由来の`Link`コンポーネントなので、`styled(Link)`となっており、propsがそのままHTMLに出力されてしまっているようです。
ひとまず出力されてもHTMLとして問題ないよう`data-align` `data-caret`として、data属性にしました。
その他、propsを使わずにクラス名やマークアップで表示を切り替える方法もできそうですが、どうでしょうか？
https://deploy-preview-421--smarthr-design-system.netlify.app/ →よくあるご質問 …
> styled-components用のpropsが出力されるケースに対応

- gatsby-plugin-algolia-config.ts
https://github.com/kufu/smarthr-design-system-issues/issues/1133
gatsby-plugin-algolia のアップデートに伴い、`skipIndexing`オプションが`dryRun`に変更された結果、挙動が変わったようです。
`skipIndexing`では何も実行されませんでしたが、`dryRun`ではインデックス登録の試行が行われるため、`GATSBY_ALGOLIA_APP_ID`などの環境変数が存在しない場合はエラーになってしまいます。
そして、`continueOnFailure`オプションが`false`なので、エラーになった場合にはビルドが止まってしまいます。
ローカルの開発環境ではAlgoliaの動作確認が不要な場面もありそうなので、`continueOnFailure`も`dryRun`と同様に、`process.env.BRANCH !== 'main'`としました。
また、`gatsby-plugin-algolia-config.ts`内では、`process.env.GATSBY_...`が`undefined`になっていたので、dotenvのimportを追加しました。
ローカルでは、
- mainブランチ以外では、Algolia関連の環境変数がなくてもビルドエラーにはならない
- mainブランチ以外では、環境変数をセットしておけばdryRunが実行され、想定される送信レコード数や設定などのステータスがターミナルに出力される
- mainブランチ（dryRunしない）では、環境変数に誤りがある場合などはエラーとなりビルドが止まる
ことを確認しました。
また、このPRのプレビュー（mainブランチではないが環境変数はセットされている状況）では、dryRunが成功していました。 …
> 開発時のAlgoliaへのindex送信まわりを修正

- src/components/shared/Footer/FootStaticLinks.tsx
- src/components/shared/Footer/Footer.tsx
- src/components/shared/Header/Header.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/1154
- ハンバーガーメニューで表示されるダイアログ内のメニューリンクのクリック領域を広げた
- フッター内のメニューリンクのクリック領域を広げた
フッター内のリンクは横には広げられたものの、フォントが小さくて縦に広げることはできないため、Ligthhouseのモバイル版チェックでは相変わらず警告が出てしまうが、デザインの変更を伴わざるをえないので、ここでは対応しなかった。
https://deploy-preview-428--smarthr-design-system.netlify.app/
* 横幅は広がりましたが、縦幅が48px以上無いということで依然としてLighthouseに警告されてしまいます。
|Before|After|
| --- | --- |
| <img width="654" alt="image" src="https://user-images.githubusercontent.com/1369376/208368504-01b8088b-552a-4b54-bc00-e063f0efab80.png"> | <img width="654" alt="image" src="https://user-images.githubusercontent.com/1369376/208368579-2ea2cb40-4f30-439f-9cc5-a4117e9b359c.png"> |
> フッターとハンバーガーメニューで表示されるメニューリンクのクリック領域を広げた

- src/@types/cdn-typescript/index.d.ts
- src/components/article/CodeBlock/CodeBlock.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/1153
ライブエディタで使用するTypeScriptのライブラリの容量が大きいため、`script`タグを使ってCDN（https://unpkg.com/typescript@latest/lib/typescriptServices.js ）から読み込むようにし、Gatsbyが生成するJSバンドルに含めないようにしました。
合わせて、ライブエディタ部分はクライアントでのみレンダリングされるように変更しました。
また、`script`タグでのJSの読み込みがロードされないケースがあり、この部分もクライアントのみでレンダリングされるようにすると問題が回避できました。
型定義のみ、そのまま
```
declare type TsType = typeof import('typescript/lib/typescript.js')
```
として利用しているので、`package.json`にはtypescriptへの依存が残っています。とはいえ、コード自体はクライアントでCDNから読み込むわけなので、型は`any`にしてしまい、依存もなくす、というのもありかもしれません。
ライブエディタのあるページ例：
https://deploy-preview-445--smarthr-design-system.netlify.app/products/design-patterns/upward-navigation/#h2-1
https://deploy-preview-445--smarthr-design-system.netlify.app/products/design-patterns/select-company-account/#h2-2 …
> ライブエディタで使用するTypeScriptをCDNからの読み込みに変更

- src/context/LoginContext.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/1163
ログイン状態の確認のために、従業員専用ページにアクセスする際のメソッドを`GET`ではなく`HEAD`に変更しました。
アクセス先などは変更ありません。
コンソールにエラーが出てしまう点は、非ログイン状態でも400未満のステータスコードが返ってくれば回避できるのですが、Netlifyから401が返っているので難しそうです。
https://deploy-preview-446--smarthr-design-system.netlify.app/
プレビューにて、最初のアクセス時には`HEAD`でリクエストが飛んでいる点、ログイン機能には影響がない点を確認しました。
見た目上の変更はありません。
> ログインチェックのリクエストメソッドをHEADに変更

- gatsby-node.ts
https://github.com/kufu/smarthr-design-system-issues/issues/1162
webpackのオプションを追加し、mainブランチではソースマップのURLを出力しないようにしました。
[gatsby-plugin-no-sourcemaps](https://www.gatsbyjs.com/plugins/gatsby-plugin-no-sourcemaps/)というプラグインもありますが、Node.js v18以上が条件となっていること、[ソースコード](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-no-sourcemaps/gatsby-node.js)を見ると、webpackに`devtool: false`を追加しているだけであることから、プラグインは利用しませんでした。
また、編集した`gatsby-node.ts`の`import`文部分でeslintエラーが出るようになっていたので合わせて修正しています。
mainブランチ以外では、Gatsbyが生成したJSファイル内（おもに末尾）に、
```
//# sourceMappingURL=9ca8d63625eed7145188ccefa38d3172193a88f3-1c9b720a44169db194e3.js.map
```
のような文字列がありますが、mainブランチではこれが出力されなくなります。`public`ディレクトリ内の`*.js.map`も出力されません。
**Before**
**After**
（テストのため、全ブランチで`devtool: false`したときのNetlifyプレビュー） …
> 本環境ではJSのソースマップURLが出力されないよう設定

- src/templates/article.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/1168
`/srctemplates/article.tsx`内で、Airtableの各レコードを`h2`レベルの見出しとして扱う処理があるが、[用字用語：一覧](https://smarthr.design/products/contents/idiomatic-usage/data/)のページはテーブル表示のため、見出しとして扱うのは適切ではないため、除外しました。
具体的には、レコードの`name`という項目が`null`になっているものを除外しています。
https://deploy-preview-458--smarthr-design-system.netlify.app/products/contents/idiomatic-usage/data/
また、Airtableを利用するページのうち、用字用語：理由のページなどは、各レコードを`h2`レベルの見出しとするのが正しいので、これまで通りで変化はありません。（ https://deploy-preview-458--smarthr-design-system.netlify.app/products/contents/idiomatic-usage/usage/ ）
もともと空白文字を囲むタグが出力されている状態だったため、見た目は変わっていません。
ソースコードには空白のタグが出力されなくなりました。
> Airtableコンテンツの見出し抽出処理を修正

- src/templates/article.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/1171
テンプレート（`/src/templates/article.tsx`）内で、そのページの見出しリストが空配列の場合は、`<IndexNav>`コンポーネントを出力しないようにしました。
空の`nav`要素と`ul`要素が出力されなくなります。
出力されないページ例：
https://deploy-preview-470--smarthr-design-system.netlify.app/products/contents/idiomatic-usage/data/
https://deploy-preview-470--smarthr-design-system.netlify.app/communication/
**Before**
**After**
> 見出し一覧が空の場合はIndexNavを出力しないように変更

- package.json
- yarn.lock
https://github.com/kufu/smarthr-design-system-issues/issues/1170
`package.json`から`babel-loader`と`@babel/core`を削除しました。
（Gatsby本体などが依存しているため、`node_modules`からなくなったわけではありません。）
削除しても、特に影響はなさそうでした。
- `yarn build` `yarn dev`ともに正常に動く
- Linterも動作している
- ソースコードを"babel"で検索しても、`yarn.lock`しかヒットしない
https://deploy-preview-471--smarthr-design-system.netlify.app/
検索・ログインなども問題ないようです。
見た目や動作には影響ありません。
> babelへの明示的な依存を除去

- src/components/login/Login.tsx
- src/components/search/Search/SearchBox.tsx
closes kufu/smarthr-design-system-issues#1173
eslint-plugin-smarthrの以下のルールに最近アップデートがあったことから、警告が出るようになったのかもしれません。
https://github.com/kufu/eslint-plugin-smarthr/tree/main/rules/a11y-input-has-name-attribute
（ローカルでも`yarn --frozen-lockfile`してから`yarn lint:ts`すると同様の警告が出ました。）
検索とログインパスワードのinput要素にname属性値を追加しました。
- 検索：`query`
- ログインパスワード：`password`
`autocomplete`属性は追加していないので、`name`属性を追加したことでブラウザが値の補完を行う可能性があります。
https://deploy-preview-474--smarthr-design-system.netlify.app/search/
https://deploy-preview-474--smarthr-design-system.netlify.app/login/
https://github.com/kufu/smarthr-design-system/actions/runs/3936427868 → Warningは出なくなりました
表示上の変化はありません。
> input要素にname属性値を追加

- src/templates/article.tsx
closes kufu/smarthr-design-system-issues#1179
右サイドバーに表示するものがない場合でも、`position: sticky; height: 100vh;`の空`div`が書き出されていましたが、出力しないようにしました。
テーブルが中央のグリッドエリアからはみ出している、という状態については何もしていないため、解決していません。
https://deploy-preview-495--smarthr-design-system.netlify.app/products/contents/idiomatic-usage/data/
他に、右サイドバーが空のページは以下のようなものがありますが、表示の崩れなどはありません。
https://deploy-preview-495--smarthr-design-system.netlify.app/products/design-patterns-core-features/
https://deploy-preview-495--smarthr-design-system.netlify.app/operational-guideline/page-template/
https://user-images.githubusercontent.com/7822534/214201109-c7576077-4074-4bbf-abba-6e3513b02bca.mov
> 右サイドバーに表示するものがない場合は空divを出力しない

- src/components/contents/AppWriting/AppWriting.tsx
- src/components/contents/BasicConceptTable/BasicConceptTable.tsx
- src/components/contents/IdiomaticUsageTable/IdiomaticUsageTable.tsx
- src/components/shared/GlobalStyle/GlobalStyle.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/1178
→ 改行問題
これまで：`table td`に`word-break: break-word;`、`a`に`overflow-wrap: break-word;`が適用されていましたが、これらは削除し、`body`に`overflow-wrap: break-word;`を適用しました。
※`overflow-wrap: break-word;`は各ブラウザともかなり前から実装しているようで、その点は問題なさそうです→ https://caniuse.com/mdn-css_properties_overflow-wrap_break-word
https://developer.mozilla.org/ja/docs/Web/CSS/overflow-wrap
> このプロパティはもともと、標準外かつ接頭辞のない word-wrap と呼ばれる Microsoft 拡張であり、多くのブラウザーはこの名前で実装していました。 overflow-wrap に改名されたため、 word-wrap は別名になりました。
→基本的には、すべての要素に`break-word`が適用されるので、はみ出す可能性は減っているはずです。ただし、`word-break`と`overflow-wrap`の挙動の違い（単語がおさまらない場合のみ改行する）から、テーブル幅の算出結果などは少し変わっていそうです。
以下はそのままですので、グローバルの`overflow-wrap: break-word;`を上書きする挙動になります。
- コードブロックの`word-break: break-all;`
- カラーパレットの`word-break: break-all;` …
> グローバルに`overflow-wrap: break-word`を追加・調整

- src/components/ComponentStory/ComponentStory.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/1174
https://github.com/kufu/smarthr-design-system/pull/478
SmartHR UIのグループ分けに対応した際、#478で`<SmartHRUIMetaInfo>`コンポーネントを移動しましたが、以下の3ページで階層構造が考慮できておらず、グループ追加前とStorybookのリンク先が変わってしまっていました。
https://smarthr.design/products/components/dropdown/dropdown-menu-button/
https://smarthr.design/products/components/dropdown/filter-dropdown/
https://smarthr.design/products/components/input/search-input/
リンク先が1階層深い、個別のストーリーになるように修正しました
`https://smarthr-ui.netlify.app/?path=/story/buttons（ボタン）-dropdown`
↓
`https://smarthr-ui.netlify.app/?path=/story/buttons（ボタン）-dropdown--dropdown-menu-button`
`https://smarthr-ui.netlify.app/?path=/story/buttons（ボタン）-dropdown`
↓
`https://smarthr-ui.netlify.app/?path=/story/buttons（ボタン）-dropdown--filter-dropdown` …
> 階層のあるsmarthr-uiコンポーネントのリンク先を修正

- README.md
- src/components/index/Gotcha.tsx
- src/data/gotchaItem.json
※Cloudinaryアカウントがテスト用のため、マージはアカウント切り替え後に行う
https://github.com/kufu/smarthr-design-system-issues/issues/1165
Gotchaで使われている画像をCloudinaryにアップロードした画像に差し替えました。
Cloudinaryを利用することで、以下のような画像の出し分けができます。
- ブラウザに応じて最適な画像フォーマットが選択される
- 画像幅を指定したリクエストができるので、`img`要素の`srcset`属性と合わせて、画面幅が狭い時には小さい画像を利用できる
→これにより、パフォーマンスの向上が見込めます。
また、画像の読み込みが速くなったためか、2枚の画像（表示中画像と隠れている次の画像）の読み込み終わり判定がうまくいかないケースがあったため、`useMemo`を使うように変更しています。
`picture`要素ではなく、`img`要素＋`srcset`属性を使っているので、実際にどのソース画像が選択されるかはブラウザ依存です。Viewportが768pxだと768pxの画像が選択されるわけではなく、dprなども考慮されるので、たとえばChromeではViewport500pxくらいからは大きな画像が選ばれるようです。
今は1272pxと768pxの2つですが、もう少し細かい刻みで画像を増やしてもいいかもしれません。
また、Gotcha以外のトップページの画像については従来のままなので、こちらもCloudinaryを利用してフォーマットの最適かをしても良いかもしれません。
https://deploy-preview-469--smarthr-design-system.netlify.app/
**"Mobile"でのLighthouseの結果** …
> Gotchaの画像をCloudinaryに配置

- src/data/gotchaItem.json
GOTCHA!に名刺の画像も追加する
- シン名刺の導線をトップに配置し、回遊できる状態をつくる
- ユースケースの提示
- GOTCHA!に名刺の画像を追加
特になし
https://deploy-preview-501--smarthr-design-system.netlify.app/
https://github.com/kufu/smarthr-design-system-issues/issues/1158
> GOTCHA!に名刺の画像を追加

- content/articles/accessibility/policy.mdx
- content/articles/accessibility/test/202105/index.mdx
- content/articles/accessibility/test/202112/index.mdx
- content/articles/operational-guideline/page-template/style-template.mdx
- content/articles/products/components/heading.mdx
- content/articles/products/design-tokens/typography.mdx
- src/components/contents/IdiomaticUsageTable/IdiomaticUsageTable.tsx
- src/components/contents/shared/TableWrapper.tsx
- src/templates/article.tsx
closes kufu/smarthr-design-system-issues#1183
テーブルの表示まわりを確認したところ、`<ComponentPropsTable>`コンポーネントでは[親の`div`に`overflow-x: auto;`が適用されており](https://github.com/kufu/smarthr-design-system/blob/454b435354fa3874c3670ef00319846ea5b65800/src/components/ComponentPropsTable/ComponentPropsTable.tsx#L93-L94)、テーブル幅が100%超える場合にはスクロールバーが表示されていましたので、それ以外のテーブルも同じようにしました。
`overflow-x: auto;`を適用した`TableWrapper`コンポーネントを用意し、
```
<TableWrapper>
<Table>...</Table>
</TableWrapper>
```
のようにラップしました。
[Gatsbyのカスタムコンポーネント](https://www.gatsbyjs.com/docs/how-to/routing/customizing-components/)を利用して、`table`要素（GFMのtable記法）があれば、`TableWrapper`コンポーネントでラップするようにしました。
```article.tsx
table: ({ children }) => <TableWrapper mdTable={true}>{children}</TableWrapper>,
```
↑このとき、`children`には`table`要素自体は含まれないので、`<table>{children}</table>`を …
> テーブル幅が100%超える場合、レイアウトを崩さず横スクロールにする

- .eslintrc.js
closes kufu/smarthr-design-system-issues#1186
- `.eslintrc.js`に、ルールを追加して`a11y-anchor-has-href-attribute`ルールをoffにしました。
- `.eslintrc.js`でprettierが警告を出していた部分も修正しました。
ローカルにて、`yarn lint:ts`で出ていた警告がすべて消えたのを確認しました。
Linterの警告解消のみなので、ビルド結果への影響はありません。
> ESLintの`a11y-anchor-has-href-attribute`ルールをoffにする

- .github/workflows/deploy-to-netlify.yml
closes kufu/smarthr-design-system-issues#1190
`netlify-cli`コマンドで、Netlifyに保存している環境変数を取得できるので、GitHub Actionsでビルドする際にもそれを利用するように変更しました。この仕組みであれば、環境変数の定義はNetlify上（と、ローカルの`.env`ファイル）のみでOKになります。
具体的には、`netlify-cli env:list --plain`コマンドで取得した環境変数一覧を、`.env`ファイルに保存しています（これまでは、GitHub secretsを`.env`に保存する仕組みでした）。
このGitHubリポジトリに保存されているsecretの削除は行なっていないため、削除後に念のためActionsからのNetlifyデプロイを確認するほうが良いかもしれません。
GitHub Actions上でビルドし、`public`ディレクトリをartifactとしてダウンロードして確認しました。
→正しくサイトが構築できていました（Airtableのコンテンツが表示されている、検索ができる、Gotcha画像が表示できている等）。
Actionsのログ：https://github.com/kufu/smarthr-design-system/actions/runs/4131341296
GitHub Actions上でビルドし、`netlify-cli`の`deploy`コマンドを、`--prod`を除いて実行しました（デフォルトで`prod=false`になるため）。
→デプロイプレビューが作られましたが、こちらも正しくサイトが構築できていました。
Deployのログ：https://app.netlify.com/sites/smarthr-design-system/ …
> GitHub Actionsでビルドする際にNetlify上の環境変数を参照する

- src/components/search/Search/SearchBox.tsx
- src/pages/search.tsx
closes kufu/smarthr-design-system-issues#1166
- 環境変数の `GATSBY_ALGOLIA_APP_ID`と`GATSBY_ALGOLIA_SEARCH_API_KEY` のいずれか（または両方）が `undefined`の状態で検索クエリを入力した場合に、警告メッセージを表示します。
- 本番環境（`process.env.BRANCH === 'main'`）の場合は、~~メッセージは表示しません。~~ これまでどおりビルド時にgatsby-plugin-algoliaのエラーで、ビルドが止まります。
また、`/src/pages/search.tsx`内で、Algoliaのindex名（`content`）がベタ書きされていたので、環境変数を参照するように変更しました（環境変数には元から `GATSBY_ALGOLIA_INDEX_NAME`として定義されています）→ https://github.com/kufu/smarthr-design-system/pull/531/commits/b90368f28b80228a223eeb16c45f40b205d3baa6
react-instantsearch-domライブラリの`<InstantSearch>`コンポーネントまわりの動作は変わっていないので、引き続きKEYがなくてもリクエストは飛んでいます（＝エラーレスポンスが返るので、コンソールにはエラーが出ます）。
KEYがない場合にコンポーネント自体をレンダリングしない、というのは可能ですが、検索入力のテキストボックスも表示されなくなりそうです。
https://deploy-preview-531--smarthr-design-system.netlify.app/search/ …
> AlgoliaのKEYが設定されていない場合にメッセージを表示

- gatsby-config.ts
- package.json
- src/components/contents/AppWriting/AppWriting.tsx
- src/components/contents/BasicConceptTable/BasicConceptTable.tsx
- src/components/contents/IdiomaticUsageTable/IdiomaticUsageTable.tsx
- src/constants/airtable.ts
- yarn.lock
closes kufu/smarthr-design-system-issues#1167
`AIRTABLE_API_KEY`・`AIRTABLE_BASE_ID`のいずれかが環境変数に設定されていない場合、gatsby-source-airtableプラグインの代わりにgatsby-source-mockプラグインを有効にして、モックデータでビルドできるようにしました。
ただし、mainブランチの場合（`process.env.BRANCH`が`main`の場合）はKEYの有無にかかわらずgatsby-source-airtableを有効にします（KEYがなければこれまでと同様にビルドエラーになります）。
また、モックデータを利用している場合は、Airtableコンテンツを表示するページにメッセージを表示します。
関連するコンポーネントは以下です。
`/src/components/contents/AppWriting/AppWriting.tsx`（UIテキスト）
`/src/components/contents/BasicConceptTable/BasicConceptTable.tsx`（ライティングスタイル）
`/src/components/contents/IdiomaticUsageTable/IdiomaticUsageTable.tsx`（用字用語：一覧、用字用語：理由）
https://deploy-preview-534--smarthr-design-system.netlify.app/products/contents/writing-style/
https://deploy-preview-534--smarthr-design-system.netlify.app/products/contents/idiomatic-usage …
> Airtableのキーが未設定の場合にモックデータを使ってビルドする

- .github/workflows/link-check.yml
closes kufu/smarthr-design-system-issues#1181
このリポジトリ（smarthr-design-system）でリンクチェックのWorkflowを実行し、リンク切れがあれば別のリポジトリ（smarthr-design-system-issues）にissueを立てたいので、GitHubのRest API経由でissueをPOSTするように変更しました。
Rest APIでは、作りたいissueのタイトルと本文をJSONフォーマットで送信するので、チェックした日付（タイトル）とエラー内容（本文）を入れたJSONファイルを作り、それを`curl` コマンドで送信するしくみです。
issue作成のためのトークンは、`CREATE_ISSUE_TOKEN`という名前でActionsのSecretに設定されている想定になっています。定期実行は月曜日のAM11時です。
SDS本体への影響はありません。
> リンクチェッカーでのissue作成をRest API経由に修正

- .github/workflows/link-check.yml
https://github.com/kufu/smarthr-design-system-issues/issues/1181
issue作成がうまくいかないので、ひとまず実行結果を手動で確認できるようにしました。
リンクチェックの実行結果と、あればエラー出力を、Actionsのサマリーに出力するようにしました。
issue作成や通知についてはこのPRでは対応していません。
このPRのブランチから手動で実行してみました
https://github.com/kufu/smarthr-design-system/actions/runs/4279281141
**リンク切れがない場合の出力例**
**リンク切れがあった場合の出力例**
> リンクチェックの結果をサマリーに出力するように変更

- content/articles/operational-guideline/figma-operation.mdx
- content/articles/products/components/notification-bar.mdx
- scripts/linkChecker.ts
- static/_redirects
closes kufu/smarthr-design-system-issues#1202
以下の3種類の問題がありました
- 末尾スラッシュが漏れていたもの
- →追加しました
- GIF画像
- リンクチェッカーが`.gif`拡張子に対応していなかったので、修正しました。
- また、スクリプト内でLinterに引っかかったところも合わせて修正しています。
- 移動したページを参照していたもの
- リンク先の変更・リダイレクト設定の追加を行いました。
→ リンクチェックでは何も検知しなくなりました。
- https://deploy-preview-552--smarthr-design-system.netlify.app/products/components/notification-bar/ →ページ内のリンク3箇所に末尾「/」を追加（挙動は変わりません）
- `LineClampコンポーネントも使えます `
- `Headerよりも上に配置します`
- `AppNaviの下に`
- f987abe83f98d515fc173316a3cd815cef926359 で、`/products/resource/components/`がなくなった対応
- https://deploy-preview-552--smarthr-design-system.netlify.app/operational-guideline/figma-operation/#h2-2 → `Figmaライブラリ`のリンク先を修正
- リダイレクトを追加：https://deploy-preview-552--smarthr-design-system.netlify.app/products/resource/components/ …
> リンク切れとリンクチェッカーの修正対応

- src/components/shared/GlobalStyle/GlobalStyle.tsx
closes kufu/smarthr-design-system-issues#1185
`table th, table td` にグローバルに `min-width: 7em;`の指定を追加しました。
左右`1em`ずつpaddingが効いている（+`box-sizing: border-box;`の指定がある）ので、実質`5em`分のコンテンツ表示領域を確保することになります。
個別のテーブルに対してのスタイル指定（上書き）は追加していません（すでに指定されていたものはそのままです）。
SP表示などで、日本語が1〜2文字で折り返されて縦書きのようになるケースはなくなりました。逆に、1〜2文字しか入らないセル（「○」「A」など）については、これまでよりやや幅が広くなってしまっています。
（いずれもスマートフォン表示）
https://deploy-preview-553--smarthr-design-system.netlify.app/basics/icons/
|Before|After|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/7822534/221762843-fb2017e4-7e1b-44c0-b17f-ba0e49a0b83e.png" width="300" alt="現在のアイコンページのスクリーンショット"> | <img src="https://user-images.githubusercontent.com/7822534/221762783-1b88c252-f132-4e5c-9ad7-0e2c20e9fb5e.png" width="300" …
> テーブルセルにグローバルにmin-widthを適用

- src/components/ComponentStory/ComponentStory.tsx
- src/components/article/CodeBlock/CodeBlock.tsx
closes kufu/smarthr-design-system-issues#1204
コードブロックの内容が、記事表示エリアの幅より広い場合に横スクロールするようにしました。
例：https://deploy-preview-556--smarthr-design-system.netlify.app/products/contents/help-center/review/#h3-2
コードの内容に長いテキストがある場合は横スクロールします。
その際、右上のコピーボタンは固定にしたいため、親階層に`<div>`をひとつ追加しています。
https://github.com/kufu/smarthr-design-system/blob/400b5a9ec5f2343cc81710e2ac1c735f1afb6d52/src/components/article/CodeBlock/CodeBlock.tsx#L132
例：https://deploy-preview-556--smarthr-design-system.netlify.app/products/components/accordion-panel/
基本的にはプレーンなコードブロックと同じです。以前は、`<ComponentStory>`コンポーネント側から、`> * {...}`のような形で`<CodeBlock>`内のCSSを上書きしていましたが、`isStorybook`というpropsを渡して`<CodeBlock>`内でCSSを出し分けるように変更しました。
https://github.com/kufu/smarthr-design-system/blob/400b5a9ec5f2343cc81710e2ac1c735f1afb6d52/src/components/article/Co …
> コードブロックに横スクロールを追加

- scripts/exportUIProps.ts
- scripts/linkChecker.ts
closes kufu/smarthr-design-system-issues#1210
globパッケージを使用している、以下の2つのスクリプトを修正し、エラーなく実行できることを確認しました。
- /scripts/exportUIProps.ts
- /scripts/linkChecker.ts
具体的には、globのAPIがcallback関数を指定するのではなくPromiseを返す実装に変わったので、その対応をしました。
`exportUIProps.ts`を実行すると、`smarthr-ui-props.json`が書き出されますが、コミットには含めていません。
- ローカルのファイルパスなどを含むため、大量のdiffが出てしまうので。
- propsの一覧などは同じ内容が書き出されるので、ビルド後のComponentPropsTableには変化がないことを確認しました。
含めたほうが良ければ追加します。
```
yarn export:ui-props
npx ts-node scripts/linkChecker.ts
```
見た目上の変化はありません。
> globパッケージのアップデートに対応

- src/components/ComponentStory/ComponentStory.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/1193
`/products/components/` 以下のページにSmartHR UIのバージョン切り替え機能を追加しましたが、以下の実装・考慮漏れがあったので修正しました。
- Storybookへのリンク（iframeではない）URLの修正
- プルダウンに元からあるバージョンを表示中は、`blankLabel`はバージョン名ではなく「-」にする（重複してしまうので）
https://deploy-preview-582--smarthr-design-system.netlify.app/products/components/tooltip/
https://deploy-preview-582--smarthr-design-system.netlify.app/products/components/tooltip/?v=25.0.0
※存在しないバージョン（またはでたらめな文字列など）の場合はこれまでどおり「-」、Chromaticに存在しないがコードは存在するバージョン（例えば「v25.0.0」）の場合もこれまでどおりそのバージョンを表示します。
|Before|After|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/7822534/225823417-3f1f7a74-1a17-4861-8e57-35d541b641a9.png" alt width="350"> | <img src="https://user-images.githubusercontent.com/7822534/225823291-b9ff1aa9-4416-4b …
> ComponentStory内のリンク・プルダウンの不具合を修正

- content/articles/accessibility/test/202105/index.mdx
- content/articles/accessibility/test/202112/index.mdx
- src/components/contents/shared/TableWrapper.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/1209
アクセシビリティ試験結果のテーブルは、セルの中身が「A」など短いテキストの列があり、グローバルに指定している`min-width: 7em;`（5em+左右paddingが1emずつ）より幅を狭めたいので、個別のスタイルを適用しました。
具体的には、テーブルの親要素になる`TableWrapper`コンポーネントに、`type="narrow"`というpropsを渡せるようにして、`narrow`が指定された場合は、内包するテーブルの`th,td`に`min-width: 2em;`を指定しています。
マークダウン記法のテーブルにも、セルの中身が短いテキストものがあり、同様に幅指定を縮めたいところなのですが、マークダウンではpropsが渡せないため、対応できていません。
グローバルな指定をSP表示で狭めると、今度は`min-width: 7em;`の指定で改善していたページ（例えば：https://deploy-preview-553--smarthr-design-system.netlify.app/basics/icons/ ）の表示が元に戻ってしまい、悩ましいです。
https://deploy-preview-580--smarthr-design-system.netlify.app/accessibility/test/202105/
https://deploy-preview-580--smarthr-design-system.netlify.app/accessibility/test/202112/
|Before|After|
| --- | --- |
| <img …
> TableWrapperにセルの幅指定のpropsを追加

- src/components/article/CodeBlock/CodeBlock.tsx
LiveEditorでコードとコンポーネントのプレビューを表示するページがありますが、CDNで読み込んでいるTypeScriptのJSのパスが変わったため、レンダリングできていませんでした。（TS5のリリースが3日ほど前なので、おそらくそれ以降の現象と思われます）
例：
https://smarthr.design/products/components/button/#h2-0
https://smarthr.design/products/design-patterns/select-company-account/#h2-2
取り急ぎ、TS5でも存在しているファイル名に変更しました。
応急処置的な修正なので、パス内の `@latest`をバージョン固定にする、ソースを`public`ディレクトリに入れてこちら側でホスティングするなど、別の方法を検討したほうが良いかもしれません。
（`import`してしまうと、Gatsbyのバンドルサイズが跳ね上がるため、必要なページのみクライアントで読み込みたいです。）
https://deploy-preview-591--smarthr-design-system.netlify.app/products/components/button/#h2-0
https://deploy-preview-591--smarthr-design-system.netlify.app/products/design-patterns/select-company-account/#h2-2
|Before|After|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/7822534/226309936-54e84fa8-b953-46f2-a79c-f …
> TSのバージョンアップに伴い、CDNのパスを修正

- src/components/ComponentStory/ComponentStory.tsx
- src/components/article/CodeBlock/CodeBlock.tsx
closes kufu/smarthr-design-system-issues#1212
バージョン切り替えやリンク部分は https://github.com/kufu/smarthr-design-system/pull/581 のdraftのコミットを持ってきました（コンフリクトがあり一部編集しています）
また、背景色の追加と、コードブロックのカラーテーマをダークに変更しました。
その際、以下の調整をしています。
- iframe部分の背景色を `#FFF`に（設定しないと周囲と同じライトグレーになるため）
- コードブロック部分のpaddingなどを調整（ダークテーマにしても端が白くなってしまうなどしたため）
https://deploy-preview-592--smarthr-design-system.netlify.app/products/components/accordion-panel/
`<CodeBlock>`コンポーネントを使用しているが、今回の調整対象ではない箇所（CSSが影響を受けているのでデグレがないか確認）：
- LiveEditor（元からダークテーマ）
- https://deploy-preview-592--smarthr-design-system.netlify.app/products/design-patterns/upward-navigation/#h2-1
- mdのコードフェンス記法
- https://deploy-preview-592--smarthr-design-system.netlify.app/products/design-process/review/#h3-5
|Before|After|
| --- | --- |
| <img …
> ComponentStoryコンポーネントのレイアウト・スタイル調整

- content/articles/communication/capture/service-capture.mdx
SmartHR Mag.のサービス画面キャプチャを追加しました！
https://github.com/kufu/smarthr-design-system-issues/issues/1215
- サービス画面キャプチャページの下部にSmartHR Mag.のセクションを追加
- Google ドライブのリンクを設置
とくになし
https://deploy-preview-594--smarthr-design-system.netlify.app/communication/capture/service-capture/#h2-4
|Before|After|
| --- | --- |
| ![スクリーンショット 2023-03-24 18 58 24](https://user-images.githubusercontent.com/101125529/227491158-87975a4a-a887-4ea1-823c-81fd6570228a.png) | ![スクリーンショット 2023-03-24 19 20 59](https://user-images.githubusercontent.com/101125529/227495454-ce907320-42f7-4fcd-a73d-d30fda9546e2.png) |
> SmartHR Mag.のサービス画面キャプチャを追加

- content/articles/accessibility/policy.mdx
ウェブアクセシビリティ方針のページで参照してたコーポレートミッションが古かったので、新しいミッションを参照しつつ、方針も新しくした
- あたらしいミッションを受けてリライト
- 具体的に目指すものに、「さまざまな特性を持つユーザーが実際に利用できること」を追加
> ウェブアクセシビリティ方針を新しいミッションに準じたものに

- src/components/index/ContentNavigation/Category.tsx
トップページのナビゲーションで、3列になっている部分がありますが、画面幅が1300px以下あたりからリンクが3つある場合と1つの場合で画像のサイズがずれてきてしまいます。
以前はどのカテゴリも3つ画像があったようですが、今は2つや1つの箇所もあるので、調整しました。
トップページの、各カテゴリへのリンクが並んでいるナビゲーション部分のCSSを変更しました。`flex`→ `grid`にして、常に3カラム分を確保しています。
https://deploy-preview-611--smarthr-design-system.netlify.app/
画面幅1200pxでのキャプチャです
|Before|After|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/7822534/229739300-7c4c8fb9-6c44-422d-9dc9-7389f12bebbf.png" width="350" alt> | <img src="https://user-images.githubusercontent.com/7822534/229739362-9e7d19bf-e3f5-4f38-bd1e-7a3fbfa49539.png" width="350" alt> |
> トップページのナビゲーションのレイアウトを修正

- src/components/ComponentPropsTable/ComponentPropsTable.tsx
https://github.com/kufu/smarthr-design-system-issues/issues/1221
- プロダクト/コンポーネント配下の各ページのPropsテーブルを見やすいレイアウトに改修
- https://deploy-preview-619--smarthr-design-system.netlify.app/products/components/accordion-panel/#h2-0
- 比較用：https://smarthr.design/products/components/accordion-panel/#h2-0
|Before|After|
| --- | --- |
| <img width="795" alt="image" src="https://user-images.githubusercontent.com/1369376/230803566-9bae2cf6-4f4e-4557-8084-f3fa17f8daff.png"> | <img width="795" alt="image" src="https://user-images.githubusercontent.com/1369376/230803550-6a3e4be7-d186-4f06-a295-41b5be8ae42b.png"> |
> Propsテーブルのレイアウトの改修

- src/components/article/IndexNav/IndexNav.tsx
- src/templates/article.tsx
closes https://github.com/kufu/smarthr-design-system-issues/issues/1223
- コンポーネントのページ右のページインデックスに項目別にPropsを表示するようにした
- https://deploy-preview-620--smarthr-design-system.netlify.app/products/components/accordion-panel/
|Before|After|
| --- | --- |
| <img width="587" alt="image" src="https://user-images.githubusercontent.com/1369376/231616679-776943b4-55d0-49f9-802d-1ee429161800.png"> | <img width="587" alt="image" src="https://user-images.githubusercontent.com/1369376/231616639-52dd4f11-667b-45bf-a0a2-4bdb2e628be9.png"> |
> コンポーネントに複数Propsが存在する場合、ページインデックスに反映されていなかった問題を修正

- src/components/article/FragmentTitle/FragmentTitle.tsx
closes https://github.com/kufu/smarthr-design-system-issues/issues/1228
ページ内アンカーなどで移動した際に、スクロール位置がずれている問題を修正
|Before|After|
| --- | --- |
| <img width="770" alt="image" src="https://user-images.githubusercontent.com/1369376/231914370-f7dcab7e-03d4-4237-a45e-0f6195f78cd4.png"> | <img width="770" alt="image" src="https://user-images.githubusercontent.com/1369376/231914391-e614b128-1a9a-4682-9ce6-432b0593d5ae.png"> |
> scroll-margin-topの値を調整

- src/components/ComponentPropsTable/ComponentPropsTable.tsx
closes https://github.com/kufu/smarthr-design-system-issues/issues/1227
propの説明に`@deprecated`が含まれていれば、prop名の横に警告アイコンを表示する
- https://deploy-preview-622--smarthr-design-system.netlify.app/products/components/input/#h2-0
- 説明の途中に@deprecatedがある：https://deploy-preview-622--smarthr-design-system.netlify.app/products/components/combo-box/#props-MultiComboBox
|Before|After|
| --- | --- |
| <img width="745" alt="image" src="https://user-images.githubusercontent.com/1369376/231923680-1f086fa5-37ea-4e5a-9679-8b19bcd90f49.png"> | <img width="745" alt="image" src="https://user-images.githubusercontent.com/1369376/231923729-39a8a410-a31e-48cf-9477-9241d4a325a7.png"> |
> コンポーネントの非推奨のpropに警告アイコンを表示するように改修

- content/articles/products/components/tooltip.mdx
- src/components/article/CodeBlock/CopyButton.tsx
- src/components/article/FragmentTitle/FragmentTitle.tsx
- src/components/article/Sidebar/Sidebar.tsx
- src/components/search/Search/SearchBox.tsx
- src/components/shared/Header/Header.tsx
- src/components/shared/Private/Private.tsx
closes kufu/smarthr-design-system-issues#1229
TSXコンポーネント内で`<Icon size={}>`のように使われてる箇所は、CSSで`font-size`を指定するように変更しました。
MDXコンポーネント内で使われているケースは[content/articles/products/components/tooltip.mdx](https://github.com/kufu/smarthr-design-system/compare/fix/remove-icon-size-prop?expand=1#diff-3c9999d5b7461f40f0bbe4c642b10cdfa8eaeeb0e225603867911229299d56a5)のみでしたが、こちらは`size={16}`でちょうどフォントサイズと同じになっていたので、size propsの削除だけを行いました。明示的に`style={{fontSize: '16px'}}`としても良いかもしれません。
変更したページ例：
https://deploy-preview-623--smarthr-design-system.netlify.app/ SP表示時のハンバーガーアイコン
https://deploy-preview-623--smarthr-design-system.netlify.app/search/ テキストボックス左端の虫眼鏡アイコン
https://deploy-preview-623--smarthr-design-system.netlify.app/basics/ 左サイドバーメニューのキャレットボタン
https://deploy-preview-623--smarthr-design-system.netlify.app/basi …
> SmartHR UI Iconのsizeプロパティを削除

- src/lib/fetchStoryData.ts
https://pxgrid.slack.com/archives/C018J0A6DCH/p1682053310369069
[/products/components/](https://smarthr.design/products/components/)以下の各ページを調べたところ、下記の2ページでStorybookのURLが正しくなく、エラー表示になっていました。
- [Dialog](https://smarthr.design/products/components/dialog/) → ActionDialog_With_Trigger タブ
- [Icon](https://smarthr.design/products/components/icon/) → アイコンの生成 タブ
各ストーリーの名前・URLはSmartHR UIのコード（`*.stories.tsx`）から取得しており、ビルド時に`gatsby-node`内で処理していますが、名前が日本語で始まるケースや`_`が入るケースに対応できていなかったため、文字列を変換する正規表現などを修正しました。
https://deploy-preview-634--smarthr-design-system.netlify.app/products/components/dialog/
https://deploy-preview-634--smarthr-design-system.netlify.app/products/components/icon/
他のコンポーネントにも影響する部分のため、すべてのコンポーネントページ・タブについて確認しましたが、エラー表示はありませんでした。（以前から未対応の`BaseColumn`を除く）
> StorybookのURLが正しく設定できていないUIコンポーネントを修正

- scripts/content-checker/storybookUrlChecker.ts
- https://github.com/kufu/smarthr-design-system/pull/641
- https://github.com/kufu/smarthr-design-system/actions/runs/4847899821
GitHub Actionsで実行した際、Puppeteerのwaringメッセージが出ており、現在のheadlessモードの実装が近く非推奨になるので、新しいモードを試すように、となっている。Warningも実行結果のサマリーに出力されてしまい邪魔なので、対応する。
StorybookチェッカーはPuppeteerの基本的な機能しか使っておらず、新しいモードでも問題なく動作したので、切り替えました。
ドキュメント：https://developer.chrome.com/articles/new-headless/
ローカル環境ではスクリプトが問題なく実行できることを確認しました。
SDS本体への影響はありません。
> StorybookのURLチェッカーのPuppeteerを新しいモードに変更

- src/components/article/CodeBlock/CodeBlock.tsx
https://github.com/kufu/smarthr-design-system/pull/647
react-liveのメジャーアップデートに伴い、typescriptでエラーが出ていたので、型定義を更新しました。（このアップデートではreact-live自体がTSで書かれるようになったようです。）
`LiveProviderProps`という型をimportして利用していましたが、exportされなくなったようで、
```tsx
'"react-live"' has no exported member named 'LiveProviderProps'
```
というエラーと、この型が存在しないことに起因するエラーが2つ出ていました。
`LiveProvider`コンポーネントは引き続きexportされているので、そのPropsの型を参照するようにしました。
```tsx
type LiveProviderProps = React.ComponentProps<typeof LiveProvider>
```
また、以前に型エラー回避のために追加していた `@ts-ignore`が不要になっていたので削除しました。react-liveのTS化に伴い解決したようです。（おそらくこのあたり：https://github.com/FormidableLabs/react-live/blob/b3c8d0052051bc031f10a79338da14d05d7fa49e/src/components/Live/LivePreview.tsx#L12-L15 ）
型定義のみなので、ビルド後のコードには影響しないはずです。
ライブエディタがあるページは念のため確認しました、例えば、 …
> react-liveの型定義を更新

- content/articles/basics/icons/creation-guideline.mdx
Design System内における「Font Awesome」のタイポを修正する。
正式な表記は「Font Awesome」（FとAは大文字、Font と Awesome の間はスペース有り）なのですが、
Design System内にある、正式な表記以外のタイポを修正しました。
https://github.com/kufu/smarthr-design-system-issues/issues/1235
- Design System内における「Font Awesome」以外のタイポを「Font Awesome」に修正する。
とくになし
アイコン>[作成ガイドライン](https://deploy-preview-657--smarthr-design-system.netlify.app/basics/icons/creation-guideline/)の
- 概要セクションに2つ
https://deploy-preview-657--smarthr-design-system.netlify.app/basics/icons/creation-guideline/#h2-1
- [1.Font Awesomeを利用する方法]に3つ
https://deploy-preview-657--smarthr-design-system.netlify.app/basics/icons/creation-guideline/#h2-2
|Before|After|
| --- | --- |
| ![image](https://user-images.githubusercontent.com/101125529/236738626-476a8957-0e3a-4e94-ba68-366d7010f3da.png) | <img width="786" …
> Font Awesomeのタイポを修正

- content/articles/products/design-tokens/shadow.mdx
- #604 の続き
影のトークンの「レイヤー順序との関係」が実装とズレており、原則連動しているとはいえないため、実態に合わせて表現を見直しました。
- 「レイヤー順序との関係」を廃止
- セマンティクストークンに利用コンポーネントを追加
- Previewでみてね。
|Before|After|
| --- | --- |
| <img width="770" alt="image" src="https://github.com/kufu/smarthr-design-system/assets/64398878/33f0bcd1-2d95-4a1d-91ef-dccd8655c455"> | <img width="750" alt="image" src="https://github.com/kufu/smarthr-design-system/assets/64398878/1a28bcd2-573e-43a0-b600-2c99751d473d"> |
> [影トークン] セマンティクストークンの表に利用コンポーネントを追加、レイヤー順序との関係を廃止

- src/lib/fetchStoryData.ts
closes kufu/smarthr-design-system-issues#1236
階層になっているページ（`dropdown/dropdown-menu-button`・`dropdown/filter-dropdown`・`input/search-input`）でのStory名の決め方を、より厳密なものにしました。
これまでは、階層になっているものは例外的にStoryName（frontmatterで指定しているもの）を使ってURL作る、ということをやっていましたが、v7からはそのような例外処理が不要になっていましたので、「階層があれば」ではなく、「UIのコード中の`Default.storyName = '...'`の部分があれば」その名前を使う、という条件分岐に変更しました。
v7対応のコードからは`Default.storyName = '...'`の記述はなくなっているので、上記の条件分岐では常に`false`になります。（ですので、このコードはバージョン切り替えでStorybookがv6のUIバージョンが指定された場合の後方互換用になるはずです。）
影響があるのは以下の3ページです：
https://deploy-preview-660--smarthr-design-system.netlify.app/products/components/dropdown/dropdown-menu-button/
https://deploy-preview-660--smarthr-design-system.netlify.app/products/components/dropdown/filter-dropdown/
https://deploy-preview-660--smarthr-design-system.netlify.app/produ …
> SmartHR UIのStorybook v6 → v7 アップデートのため*stories.tsxのパーサーを調整

- src/components/ComponentPropsTable/ComponentPropsTable.tsx
- src/components/article/PageIndex/PageIndex.tsx
- src/components/contents/AppWriting/AppWriting.tsx
- src/components/contents/BasicConceptTable/BasicConceptTable.tsx
- src/components/contents/IdiomaticUsageTable/IdiomaticUsageTable.tsx
closes kufu/smarthr-design-system-issues#1251
markedがv5にメジャーアップデートされ、以下の機能がdeprecatedになったようです。
- 見出しタグにIDを振る（ https://www.npmjs.com/package/marked-gfm-heading-id ）
- メールアドレスをエンコードする（ https://www.npmjs.com/package/marked-mangle ）
これらは、デフォルトでは有効になっているものの、今後は削除される予定とのことで、有効にしたい場合は別途パッケージをインストール必要があるとのこと。
SDSでは、どちらも使っていないので、警告メッセージに従い、明示的に無効にするようにしました。
```
marked.setOptions({ headerIds: false, mangle: false })
```
デフォルトで有効だったものが削除予定、という状況なので、警告が出るのは仕方がないとは思うのですが、警告を消すためにオプションを追加しているような状態なのが少々悩ましいです。
とはいえ、キャッシュがない状態のビルド時（Netlify上でのビルドも該当します）に、コンポーネントが呼ばれるたびに警告が2つずつ出力され、2000行以上になるので、消せるのであれば消したい気持ちもあります。
Airtable由来のコンテンツやComponentPropsTable、PageIndexのマークダウン変換にmarkedを使っています。
https://deploy-preview-705--smarthr-design-system.netlify.app/products/contents/ …
> markedの非推奨になった機能をオフに設定

- package.json
- src/components/article/CodeBlock/CodeBlock.tsx
- yarn.lock
https://github.com/kufu/smarthr-design-system/pull/646
prism-react-rendererがv1→v2になったので、breaking changeに対応しました。
renovateが作ったPRでは、モジュールがimportできずにビルドエラーになっていましたが、その他にprism-react-rendererがTS化したことで型の不整合が起きていた点も調整しています。
`<CodeBlock>`コンポーネントで使用しているので、例えば以下のようなStorybookのプレビュー、LiveEditor、静的なコード表示が関係しますが、見た目や動作に影響は出ていません。
https://deploy-preview-718--smarthr-design-system.netlify.app/products/components/button/
https://deploy-preview-718--smarthr-design-system.netlify.app/operational-guideline/page-template/style-template/#h2-4
見た目への影響はありません。
> prism-react-rendererのメジャーアップデートに対応

- plugins/gatsby-source-component-captures/fetchComponentCaptures.ts
- plugins/gatsby-source-component-captures/gatsby-node.ts
- src/components/ComponentCaptures/ComponentCaptures.tsx
コンポーネント一覧で各項目にコンポーネントページへのリンクが貼られていたが、一部のコンポーネントでリンク切れになっていたので修正しました。
- 階層の深いコンポーネントページのパスが間違っていたので修正
- Storybookには存在するが、SDSに存在しないコンポーネントを表示しないように修正
下記のSDSに存在しないコンポーネントは表示しないようにしました。
- Balloon
- SpreadsheetTable
- FormControl
- Fieldset
- RadioButtonPanel
- SideMenu
> コンポーネント一覧でのリンク切れの修正

- package.json
- plugins/gatsby-source-component-captures/fetchComponentCaptures.ts
https://github.com/kufu/smarthr-design-system/pull/727 に関連。
https://smarthr.design/products/components/ のページにコンポーネントのサムネイルの一覧とリンクを配置していますが、これらの情報はStorybook上から取得していました。
このとき、Storybookには存在するがSDS側にページ(mdx)として存在しないコンポーネントがあり、応急処置として直接それらのコンポーネント名をハードコーディングして除外していましたが、正式な処理としてmdxファイルの存在の有無で除外するようにしました。
https://deploy-preview-734--smarthr-design-system.netlify.app/products/components/
現時点でResponseMessageというSDSにはページの存在しないコンポーネントが一覧に表示されようとしてしまっています。
この修正PRのプレビューでは除外されています。
|Before|After|
| --- | --- |
| <img width="665" alt="image" src="https://github.com/kufu/smarthr-design-system/assets/1369376/6786f499-7f4f-4690-b987-c0f101503749"> | <img width="665" alt="image" src="https://github.com/kufu/smarthr-design-system/assets/1369376/a788a104-cbb3-423a-b738-b0cd1633f581"> |
> コンポーネント一覧に表示するサムネイルをmdxファイルの有無で判定されるように修正

- content/articles/products/components/fieldset.mdx
- package.json
- scripts/content-checker/storybookUrlChecker.ts
- src/components/ComponentStory/ComponentStory.tsx
- src/gatsby-node/index.ts
- src/lib/fetchStoryData.ts
- yarn.lock
https://github.com/kufu/smarthr-design-system/pull/730#pullrequestreview-1478527600
GitHub上のSmartHR UIのStorybookのコードは、`/src/components/{コンポーネント名}/{コンポーネント名}.stories.tsx` のようなパスにあると想定していたが、新しいFieldsetコンポーネントは`/src/components/New{コンポーネント名}/{コンポーネント名}.stories.tsx`となり、ディレクトリ名とコンポーネント名が異なるので、それに対応しました。
また、Storybookへのリンク部分で、これまではStory名を入れずにStorybookのリダイレクト機能に頼っていたのですが、それが難しくなったので調整しました。
具体的には、https://story.smarthr-ui.dev/?path=/story/forms（フォーム）-fieldset というURLでは、https://story.smarthr-ui.dev/?path=/story/forms（フォーム）-fieldset（非推奨）--all へリダイレクトされてしまうので、https://story.smarthr-ui.dev/?path=/story/forms（フォーム）-fieldset--all （←Story名である「all」を追加）へのリンクになるようにしました。
Storybook v7で追加された[stories.json](https://story.smarthr-ui.dev/stories.json)から情報を取ってくるようにすれば、`dirName`の指定やコードのパース処理の一部などは不要にできそうですが、これについては別途対応しま …
> StoryNameとGitHub上のディレクトリ名が異なるケースに対応

- content/articles/contact.mdx
問い合わせポータルページには、問い合わせ先一覧を掲載していたのですが、
各コンテンツページによって問い合わせ先がそれぞれ異なり、運用が複雑になってきました。
そのため一覧を削除し、簡易にしました。
issue：https://app.asana.com/0/1204801913310809/1204841238502480/f
-
https://deploy-preview-765--smarthr-design-system.netlify.app/contact/
|Before|After|
| --- | --- |
|  |  |
> 問い合わせ先の詳細一覧を削除

- src/components/contents/IdiomaticUsageTable/IdiomaticUsageTable.tsx
- src/constants/airtable.ts
ローカル環境でAirtable関連の環境変数がセットされていない場合には、モックデータを使うようになっていますが、Airtable上のコンテンツの一部が.mdxファイルに移ったり、あ行・か行…で分割して表示するようになった影響で、モックデータでは正常にビルドできなくなっていたので、調整しました。
- モックデータの更新
- データをあ行、か行…に分けた際に、該当の項目がないとエラーになっていたので、対応
- これは、本番データでも起こり得るかもしれません（現状は全ての行カテゴリに項目があるので問題は起きていませんが） 
本環境でのビルドには影響しません。
モックデータでビルドした場合は以下のようになります。
> Airtableコンテンツのモックデータを調整

- .stylelintrc
- src/components/ColorPalette/ColorPalette.tsx
- src/components/ComponentPreview/ProductWrapper.tsx
- src/components/article/Sidebar/Sidebar.tsx
- src/components/index/ContentNavigation/Category.tsx
- src/components/index/ContentNavigation/ContentNavigation.tsx
- src/components/index/Faq/FaqItem.tsx
- src/components/index/Faq/FaqList.tsx
- src/components/index/Gotcha.tsx
- src/components/index/Introduction/Introduction.tsx
- src/components/login/Login.tsx
- src/components/search/Search/SearchResultOuter.tsx
- src/components/shared/Footer/Footer.tsx
- src/components/shared/GlobalStyle/GlobalStyle.tsx
- src/components/shared/Header/Header.tsx
- src/pages/index.tsx
- src/pages/login.tsx
- src/pages/search.tsx
- src/templates/article.tsx
Media QueriesのRange Syntaxの記法を使っていましたが、Safariへの導入が最近だったことでレイアウトが崩れて見えてしまうユーザーがいたため差し戻します。
- Range Syntaxにする以前の書き方に戻しました
- stylelintのRange Syntaxのルールを無効にしました
見た目上の変化はありません
> レンジ記法のstylelint無効と差し戻し

- src/components/shared/GlobalStyle/GlobalStyle.tsx
游ゴシックのフォントがWindows環境で見にくい状態になっていた
font-faceを使って太字の場合は`Yu Gothic Bold`が適用されるようにした
- https://deploy-preview-784--smarthr-design-system.netlify.app/accessibility/
- Windows11のChrome、EdgeでBeforeとAfterでフォントが見やすくなったことを確認済みです
|Before|After|
| --- | --- |
| <img width="750" alt="image" src="https://github.com/kufu/smarthr-design-system/assets/1369376/77accc9a-349b-472a-a080-0f766a32dcb1"> | <img width="750" alt="image" src="https://github.com/kufu/smarthr-design-system/assets/1369376/33f93bc9-815a-49b0-9ce8-4cea71c42cd7"> |
> 游ゴシックがWindowsで見にくくなってしまう問題の対応

- src/components/ComponentCaptures/ComponentCaptures.tsx
- src/components/article/IndexNav/IndexNav.tsx
- src/components/article/PageIndex/PageIndex.tsx
- src/constants/application.ts
- src/templates/article.tsx
closes kufu/smarthr-design-system-issues#1266
右サイドバーにあるページ内の見出しへのナビゲーションを、ビルド時ではなくクライアントでのレンダリング時に生成するように変更しました。
これまでは`/src/templates/article.tsx`内でAirtableコンテンツおよびMDXファイル内の見出しタグを取得して`IndexNav`コンポーネントに渡していましたが、代わりに`<article>`要素のrefを渡して`IndexNav`コンポーネント側で見出しタグを取得するように変更しました。
クライアント側での動作なので、これまで表示できていなかったReactコンポーネント内の見出しなども表示できるようになりました。
これまでは、[`INDEXED_DEPTH`という定数が定義されており](https://github.com/kufu/smarthr-design-system/blob/1024578a501a106801a7acc09e7f76e4f24714b1/src/constants/application.ts#L1)、それによってどの見出しレベルまでをMDXから取得するかが決まっていましたが、article.tsxでの取得処理は不要になったので、この定数は削除しました。
`IndexNav`コンポーネントでは元から`h2`と`h3`が表示対象で、またAirtableコンテンツでは例外的に`h2`のみとなっていましたが、その点は変更ありません。
見出しタグにid属性がなかった場合は、`IndexNav`コンポーネント内で連番で付与するようになってはいますが、元からidが振られているほうが良いかと思うので、`ComponentCapture`と`PageIndex`コンポーネントにはid属性値を追加しました→ …
> 右サイドバーのページインデックスをCSRに変更

- src/components/contents/IdiomaticUsageTable/IdiomaticUsageTable.tsx
kufu/smarthr-design-system-issues#1262
#764 で、全角スペースによる改行を追加した際、Reactの`key`が不足していて、開発環境ではコンソールにエラーが出ている。
ループ処理で出力する`<br />`エレメントにReactの `key`が付与できていなかったので追加しました。
https://deploy-preview-798--smarthr-design-system.netlify.app/products/contents/idiomatic-usage/data/
開発中以外は元からコンソールエラー出ないので変化がわかりませんが、ローカルではエラーが消えたことを確認しています。
見た目上の変化はありません
> 用字用語：一覧のコンポーネントにReactのキーを追加

- package.json
- src/components/article/IndexNav/IndexNav.tsx
- src/components/article/PageIndex/PageIndex.tsx
- src/components/article/Sidebar/Sidebar.tsx
- src/components/index/Faq/FaqItem.tsx
- src/components/search/IndexList/IndexList.tsx
- src/components/shared/Footer/Footer.tsx
- src/components/shared/Private/Private.tsx
- src/pages/search.tsx
- src/templates/article.tsx
- yarn.lock
smarthr-ui v34で[SectioningContent](https://smarthr.design/products/components/sectioning-content/)が追加されて見出しレベルが自動計算されるようになっており、合わせて追加されたESLintのルール（`a11y-heading-in-sectioning-content`）で警告が出る箇所がある。
lintの警告が出ている例：https://github.com/kufu/smarthr-design-system/actions/runs/5581720220 → Annotations
Linterのメッセージに従って、`Nav` `Article`などのsmarthr-uiコンポーネントを利用したり、見出しコンポーネントの名称を修正したりしました。
また、直接関連はないのですが、#806 でのmicromarkのメジャーアップデートにより型エラーが出ていたので、関連するパッケージ[micromark-extension-mdxjs
](https://www.npmjs.com/package/micromark-extension-mdxjs) も合わせてアップデートしました（Renovateを待っていると1週間後になりそうなので）。
~~`nav`要素と`article`要素をそれぞれ`Nav`コンポーネントと`Article`コンポーネントに置き換えた部分で、コンポーネントに`ref={}`が定義されていると型エラーになるようです。~~
以下の2箇所です：
https://github.com/kufu/smarthr-design-system/blob/ea58cd78a68c3900ba917ba7d1af4d5a13d508dd/src/templates/ar …
> smarthr-ui v34のHeadingレベル周りのアップデートに対応

- package.json
- yarn.lock
https://github.com/kufu/smarthr-design-system/pull/812
→ postcssをpackage.jsonの `resolutions`に指定しているため、RenovateのPRが自動マージされない
#360 で、stylelintの動作不具合解消のためにpostcssのバージョンを固定しましたが、最近は最新バージョンに追従しても問題なくなっているため、固定を解除しました。
stylelintが実行できることを確認しました。
> postcssのバージョン固定を解除

- content/articles/basics/illustration/creation-guideline.mdx
- yarn.lock
SmartHR Design Systemでは[イラストレーションの作成ガイドライン](https://smarthr.design/basics/illustration/creation-guideline/)にて、[twemoji](https://twemoji.twitter.com/)を人物のイラストレーションの喜怒哀楽表現の参照元に定めています。
現在twemojiはOSSですが、今後非公開になる可能性もあります。
問題の発生を未然に防ぐため、twemojiが非公開になった場合、何を人物のイラストレーションの喜怒哀楽表現の参照元にするべきなのか追記しました。
- twemojiが非公開になった場合、何を人物のイラストレーションの喜怒哀楽表現の参照元にするのか追記
とくになし
https://deploy-preview-822--smarthr-design-system.netlify.app/basics/illustration/creation-guideline/#h3-1
|Before|After|
| --- | --- |
| <img width="900" alt="スクリーンショット 2023-07-27 12 39 38" src="https://github.com/kufu/smarthr-design-system/assets/101125529/7c0452c1-873a-42ba-82d6-2e69b11367b9"> | <img width="965" alt="スクリーンショット_2023-07-27_12_41_18" src="https://github.com/kufu/smarthr-design-system/assets/101125529/da247b94-1ebc-45bb-be86-ca1f29 …
> 人物のイラストレーションの喜怒哀楽表現の参照元について補足を追記

- content/articles/products/contents/app-writing.mdx
- content/articles/products/contents/idiomatic-usage/usage.mdx
- content/articles/products/contents/writing-style.mdx
- src/components/article/IndexNav/IndexNav.tsx
- src/templates/article.tsx
closes kufu/smarthr-design-system-issues#1283
画面のスクロールが発生した際に、メインコンテンツ部分で表示中のセクションを割り出し、右サイドバーのナビゲーションでもその部分に背景色がつくようにしました。
- メインコンテンツ部分は、iframeのリサイズや従業員限定コンテンツの読み込みなどで、セクションの位置がずれることがあるため、スクロールごとに表示中セクションの算出をしています。
- ハイライトしたい項目が、サイドバーの表示範囲外にある場合は、その項目が中央に来るようスクロールさせています。
- スムーススクロールなどは入れていませんが、実装は可能です。
- 現在地の判定として、画面上端から200pxのところに見出しが来たら、そのセクションに入ったものとしていますが、この位置（200px）は調整可能です。
- 背景色のpaddingのため、CSSを少し調整しています。
右サイドバーはフォーカス時は下線がつくようになっていますが、それは変更していません。
また、Airtable由来のページでは、右サイドバーに `h3`を表示しない実装になっていましたが、現状該当するページが1ページしか無くなってしまいました→ https://smarthr.design/products/contents/idiomatic-usage/usage/
ハイライト表示にも影響するため、いったん例外処理をなくし、`h3`を表示しています。表示するアイテムが増えるので、非表示にすべきであれば、MDXに移行したAirtabaleコンテンツと合わせて対応できればと思います。
https://deploy-preview-819--smarthr-design-system.netlify.app/foundation/
右サイドバーが縦に長いページ例 …
> 右サイドバーに現在地のハイライト表示を追加

- content/articles/basics/logos/sound.mdx
- content/articles/basics/meta/index.mdx
- content/articles/communication/business-card/index.mdx
- content/articles/communication/sample/text.mdx
[[サウンドロゴ] 画面](https://smarthr.design/basics/logos/sound/#h2-4) に、サウンドロゴの利用方法に関する相談・お問い合わせのメールアドレスが掲載されていないので掲載したい。
[issueをみる（社内限定）](https://app.asana.com/0/1204801913310809/1205169518598905/f)
[[サウンドロゴ] 画面](https://smarthr.design/basics/logos/sound/#h2-4) に、サウンドロゴの利用方法に関する相談・お問い合わせのメールアドレスを追加
とくになし
https://deploy-preview-836--smarthr-design-system.netlify.app/basics/logos/sound/#h2-4
|Before|After|
| --- | --- |
| <img width="1169" alt="スクリーンショット 2023-08-01 23 10 56" src="https://github.com/kufu/smarthr-design-system/assets/101125529/f04633b1-af84-4dfa-9880-8e0f5d77b4ba"> | <img width="1121" alt="スクリーンショット 2023-08-01 23 15 03" src="https://github.com/kufu/smarthr-design-system/assets/101125529/184447ce-0ba9-4bd5-833c-164c47759c1e"> |
> サウンドロゴのお問い合わせ先メールアドレスを追加

- content/articles/basics/meta/index.mdx
- content/articles/basics/meta/ogp.mdx
- src/components/Head/Head.tsx
closes kufu/smarthr-design-system-issues#1288
実際のHTMLヘッダーのOGPタグの出力内容と、メタ情報のページの内容の両方を変更しています。変更後は実際の出力内容とメタ情報ページのコード例にある項目は同じになっています。
- `twitter:domain`の削除（メタ情報ページ）
- `twitter:title`の追加（メタ情報ページ）
- `og:title`の例を変更（メタ情報ページ）
- `og:site_name`の追加（HTMLヘッダー）
https://deploy-preview-837--smarthr-design-system.netlify.app/basics/meta/#h4-0
https://deploy-preview-837--smarthr-design-system.netlify.app/basics/meta/ogp/#h2-0
トップページのHTMLヘッダー内のメタ情報
```
<meta name="description" content="SmartHR Design Systemは、だれでも・効率よく・迷わずにSmartHRらしい表現をするためのデザインシステムです。" data-gatsby-head="true"/>
<meta property="og:title" content="SmartHR Design System" data-gatsby-head="true"/>
<meta property="og:description" content="SmartHR Design Systemは、だれでも・効率よく・迷わずにSmartHRらしい表現をするためのデザインシステムです。" data-gatsby-head="true"/>
<meta …
```
> OGPメタタグの整理・更新

- src/components/login/Login.tsx
kufu/smarthr-design-system-issues#1292 に付随して、ログイン不具合の解消にはしばらくかかりそうなので、一時的にログインできない旨を表示する。
ログインページの説明文を一時的に変更しました。また、フォームの`input`、`button`にも`disabled`属性を付与しています。
文字色はデザイントークンの`DANGER`です。ログインに失敗した場合のエラー表示などと同じ色です。
https://smarthr.design/products/design-tokens/color/#h3-1
「ログイン」ボタンを押した後に処理を行うJSのコードはそのままで、ひとまず削除などはしていません。
https://deploy-preview-861--smarthr-design-system.netlify.app/login/
|Before|After|
| --- | --- |
| <img src="https://github.com/kufu/smarthr-design-system/assets/7822534/4b01b5dc-45f8-4df7-b59f-2d32d5d98dfc" alt width="350"> | <img src="https://github.com/kufu/smarthr-design-system/assets/7822534/73611ead-f5c8-4dce-b4c7-76fbc98051e7" width="350" alt> |
> 一時的にログインできない旨を表示

- src/components/ComponentStory/ComponentStory.tsx
- src/components/article/CustomLink/CustomLink.tsx
- src/components/article/CustomLink/index.ts
- src/components/contents/shared/TextUrlToLink.tsx
- src/components/shared/Footer/FootStaticLinks.tsx
- src/templates/article.tsx
closes kufu/smarthr-design-system-issues#1290
- MDXコンテンツにテンプレートを適用する際、`a`タグにカスタムコンポーネントを適用し、リンク先が外部であれば`target="_blank"`属性およびアイコンを自動的に追加するようにしました。
- ESLintのルール[jsx-no-target-blank](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md) により、`_blank`の場合は`rel="noreferrer"`の指定が推奨されているため、こちらも追加しています。
- Airtableコンテンツなどで使われている、`https://〜`から始まる文字列をリンクに変換するコンポーネント（`<TextUrlToLink>`）にも同じルールを適用しました。
- フッターの「更新情報（Twitter）」「運営会社」へのリンクには、手動でアイコンを追加しました。
Reactコンポーネント内にリンクが書かれていた場合は、自動的な属性・アイコン付与の対象にはなりません。現状の実装では、コンポーネントごとに個別対応が必要です。
- 外部リンクを含むコンポーネントはあまりなさそうです。
- 例えば`<ComponentStory>`コンポーネントでは、smarthr-uiのStorybookへのリンクには元から`target`属性とアイコンがついています。
外部・内部リンクが記述されている事例
- https://deploy-preview-849--smarthr-design-system.netlify.app/accessibility/alternative-text/#h2 …
> 外部リンクに自動的にアイコン・target属性を付与する仕組みを追加

- netlify/edge-functions/private-fetch.ts
- src/components/login/Login.tsx
- src/components/shared/Private/Private.tsx
- src/context/LoginContext.tsx
- static/_redirects
kufu/smarthr-design-system-issues#1292
プライベートコンテンツをBasic認証で保護し、Edge functions経由で認証・コンテンツ取得するように変更しました。
- リダイレクト（リライト）ルールの削除
- Edge functionsの設置
- ログイン、ログイン状態保持を行う部分を上記に合わせて修正
Basic認証に変更すると、Cookieでのセッション維持ができなくなるため、Gatsby内で状態を保持するように変更しています。そのため、サイト内回遊中は問題ありませんが、リロードを行うとログイン状態は維持できなくなる仕様です。
このPRをマージしてからでないとプライベートサイト側を更新できないため、現状ではログインはまだできません。プライベートサイト側の更新後に、ログインページをアクティブに戻します。
- /privateパスの、リライト設定がなくなっている
- このページ下部に出ているredirect rulesが、57→56になっているので問題なく反映されていそうです
- ページロード時のログインチェックで必要なヘッダーが送られる
- そして401が返る
- Basic認証のダイアログが表示されない（Privateサイト側にsite protectionがある間はされないはずではありますが）
ことをこのPRで確認したいです。ローカルでは `netlify dev`コマンドにて確認できています。
画面上の変更はありません。
> プライベートコンテンツへのリクエスト方法を変更

- src/components/login/Login.tsx
kufu/smarthr-design-system-issues#1292
プライベートコンテンツ提供サイトの認証方法を変更し、#863 でこちら側もリクエスト方法を切り替えました。動作に問題なさそうなので、無効にしていたログインUIを再度有効にします。
ログインページのパスワード入力フォームが機能するように戻し、ログイン不具合の注意書きなども削除しました。見た目上は、不具合発生以前の状態に戻っています。
ローカルでは`netlify dev`コマンドにて動作確認済みです。
ログイン機能には、引き続きNetlify特有の機能を利用しているので、ローカルでは`yarn dev`コマンドでの動作確認はできません。
- ログイン画面：https://deploy-preview-864--smarthr-design-system.netlify.app/login/
- プライベートコンテンツのあるページ例：https://deploy-preview-864--smarthr-design-system.netlify.app/basics/illustration/user-co-main/
認証方法が以前と変わったため、ログイン状態を維持できる範囲が少し変わりました。
- 画面をリロードした場合：以前はログインしたままでしたが、今後はログアウト状態になります
リンクを辿ってサイト内を回遊している状況では維持されますが、上記の点が不便なようでしたらsessionStorageの活用などを検討するのが良いかもしれません。
|Before|After|
| --- | --- |
| <img src="https://github.com/kufu/smarthr-design-system/assets/7822534/2b614fc5-2c58-4a87-b0b2-16 …
> ログイン画面を有効なものに戻す

- src/components/contents/ServiceCapture/CaptureImageWithDesc.tsx
サービス画面キャプチャのページの画像が、いつの間にか表示されなくなっていた
親のa要素にinline-blockを適用
https://deploy-preview-866--smarthr-design-system.netlify.app/communication/capture/service-capture/#h2-0
|Before|After|
| --- | --- |
| <img width="782" alt="image" src="https://github.com/kufu/smarthr-design-system/assets/1369376/3958c847-852d-48e7-b1a6-af91fbcaf7de"> | <img width="782" alt="image" src="https://github.com/kufu/smarthr-design-system/assets/1369376/0f40ded3-aca4-4934-b257-29ae9445b166"> |
> サービス画面キャプチャのページの画像が表示されなくなっていた問題を修正

- src/components/article/CustomLink/CustomLink.tsx
- src/components/contents/ServiceCapture/CaptureImageWithDesc.tsx
- src/templates/article.tsx
関連：#849、#866
#849 にて、テンプレートに `a`要素を置換するカスタムコンポーネントを追加しましたが、mdxファイル内の画像にも影響し、一部のページで画像が表示できない原因となっていたため、修正しました。
具体的には、mdxファイル内の画像記法（`![xxx](yyy)`）→gatsby-remark-imagesプラグインで`a`タグでのラップ、スタイルの適用などの処理が行われる→`a`タグなので#849 のカスタムコンポーネントが適用、という処理になっていますが、
カスタムコンポーネント適用時にgatsby-remark-imagesが追加したスタイルが失われていました。
カスタムコンポーネントに、`href`以外の属性値もrest propsとして渡し、適用するようにしました。
外部リンクの場合には、`target="_blank"`と`rel="noreferrer"`を追加する、という処理は変わりません。
また、#866でスタイルの追加をしていますが、このPRの修正で根本的に解決でき、不要になるので、元に戻しました。
画像が表示されている：
https://deploy-preview-869--smarthr-design-system.netlify.app/communication/capture/service-capture/
外部リンクにはアイコンと`target="_blank"`と`rel="noreferrer"`が適用できている例：
https://deploy-preview-869--smarthr-design-system.netlify.app/accessibility/alternative-text/#h2-2
見た目上の変化はありません。
> a要素のカスタムコンポーネントに属性値の継承処理を追加

- src/components/article/CustomLink/CustomLink.tsx
関連：#869
#869 で、プラグインが出力した`target="_blank"`属性がそのままHTMLに出力されるように修正しましたが、Gatsbyの`Link`コンポーネントを使用していると、リンク先が内部URLの場合には同一タブで開かれてしまうので修正する。
`target="_blank"`の場合には、`a`タグを使用するように変更しました。
https://deploy-preview-870--smarthr-design-system.netlify.app/communication/capture/service-capture/
画像をクリックすると、別タブ（ウィンドウ）で開きます。
見た目上は変化ありません。
> target="_blank"の場合はLinkコンポーネントを使わないように修正

- package.json
- scripts/content-checker/linkChecker.ts
https://github.com/kufu/smarthr-design-system-issues/issues/1285
コミットのタイミングでlint-staged→husky経由でリンクチェックが実行されるようにしました。
またその際、末尾スラッシュがないものは自動で追加するようにしました。
それにあたり、リンクチェッカー本体にも以下の変更を加えています。
- `--fix`オプションをつけると末尾スラッシュは自動追加する
- ファイルパスを引数に渡すと、そのファイルのみをチェック（・スラッシュ追加）対象とする
- lint-staged がステージングされているファイルのパスを絶対パスで渡すため
- エラーがあった場合は`process.exit(1)`で終了していましたが、`process.exit(0)`に変更しました
- リンク切れがあった場合に、`1`で終了するとコミットが中止してしまうため
- GitHub Actionsでの定期実行では、`1`で終了しても無視するようにしているので、影響はありません。
また、最終的に出力するエラーメッセージにも、
`No trailing slash - fixed automatically` と `No trailing slash - could not be automatically fixed`（＝修復に失敗した場合。あまり起こらないとは思います）を追加しています。
コミット時に自動修復するので、ほぼLinterのような動作ですが、無効にはできない（例えば`/* disable...*/`のようなコメントを入れられない）ので、何かの事情でスラッシュを入れたくないケースが出てきた場合に困るかもしれません。 …
> コミット時の末尾スラッシュの自動修復を追加

- src/components/ComponentStory/ComponentStory.tsx
https://pxgrid.slack.com/archives/C018J0A6DCH/p1692927084500679
階層のあるコンポーネントの場合に、GitHubのソースコードへのリンクが正しくないので修正する。
#771 で階層の指定方法を変更した際に、考慮が漏れていたようです。
Storybookのパスの取得などと同様、GitHubのソースコードのパスも`smarthr-ui-props.json`から取得するように変更しました。
階層があるために、リンクが正しくなかったページ：
https://deploy-preview-867--smarthr-design-system.netlify.app/products/components/dropdown/dropdown-menu-button/
https://deploy-preview-867--smarthr-design-system.netlify.app/products/components/dropdown/filter-dropdown/
https://deploy-preview-867--smarthr-design-system.netlify.app/products/components/input/search-input/
https://deploy-preview-867--smarthr-design-system.netlify.app/products/components/layout/ 以下の各コンポーネント
階層のないページはそのままです
例：https://deploy-preview-867--smarthr-design-system.netlify.app/products/components/accordion-panel/ …
> コンポーネントページのGitHubのリンク先を修正

- .github/workflows/netlify-clear-cache-deploy.yml
closes kufu/smarthr-design-system-issues#1287
NetlifyのAPIにPOSTリクエストを送信することで、キャッシュクリアを伴うビルド・デプロイ（対象はmainブランチ）をトリガーできることが分かったので、GitHub Actionsにそのようなワークフローを追加しました。
Netlifyのsite_idとAuthorization tokenが必要ですが、デプロイ用のワークフローでも利用しているものなので、すでにこのリポジトリのActions用シークレットにセットされているはずです。
このあたり：https://github.com/kufu/smarthr-design-system/blob/94697b4c24d303169b5ec606a4149ffca78aefa1/.github/workflows/deploy-to-netlify.yml#L21-L23
`package.json`に `netlify-build: gatsby clean && gatsby build` のようなNetlify用ビルドコマンドを追加することも考えましたが、Netlify上で毎回キャッシュクリアを行うことは意図していないので、上記のAPI利用を採用しました。
mainブランチにマージしないとActionsを実行できないため、このリポジトリの環境では未検証です。テスト用リポジトリ・サイトでは動作確認済みで、成功すればNetlify側のビルドログには`Building without cache`と記録されるはずです。
`Initializing`セクションの最初の部分です：
サイト本体への影響はありません。
> Netlify上でキャッシュクリア・ビルドするGH Actionsを追加

- plugins/gatsby-source-ui-versions/fetchUiVersions.ts
- plugins/gatsby-source-ui-versions/gatsby-node.ts
- src/components/ComponentStory/ComponentStory.tsx
プロダクト＞コンポーネント以下の各SmarthrUIコンポーネントについて、バージョン選択のドロップダウンメニューの並び順が期待どおりでなくなっているので修正する。
新しい2件が最後になってしまっている。
- GitHubのAPIからリリースコミットの作成日時も取得するように変更してgatsby-nodeに登録し、`useStaticQuery()`での取得の際に、日時での`sort`オプションを追加しました。
- また、GitHubのAPIはデフォルトでは30件までの取得になっていたので、上限の100件に増やしました。
順序が期待通りでなくなる現象は、明確には再現できませんでしたが、GitHubのAPIからのデータ取得時には時系列になっており、そのままgatsby-nodeに登録できていることは確認しました。キャッシュがある状態で、新しいバージョンが追加された場合などに順序がずれてしまっていたのかもしれません。
GitHub APIからのデータ取得は、`page`パラメータをつけてループ処理にすれば101件以降も取得できますが、現状は実装していません。現状でも新しいものから100件までは取得可能ですし、また100件以上となるとUI側（ドロップダウンメニュー）がそのままで良いかも検討したいかもしれません。必要があれば別途対応できればと思っています。
https://deploy-preview-875--smarthr-design-system.netlify.app/products/components/accordion-panel/
データの並び順・数のみの変更なので、動作には影響はないかと思います。
|Before|After|
| --- | --- |
| <img …
> 選択できるSmartHR UIバージョンの数・並び順を改善

- content/articles/contact.mdx
- src/gatsby-node/index.ts
- src/templates/article.tsx
closes kufu/smarthr-design-system-issues#1296
MDXファイルで、frontmatterに`robotsNoIndex: true`をセットすると、そのページのHTMLヘッダーに`<meta name="robots" content="noindex"/>`が追加されるようにし、お問い合わせページに適用しました。
[サイト内検索](https://smarthr.design/search/)のインデックスについては何もしていないので、そちらの検索では引き続きお問い合わせページも出てきます。
- HTMLヘッダーにメタタグが出力されている：
- https://deploy-preview-877--smarthr-design-system.netlify.app/contact/
- トップページやその他のページには出力されていない：
- https://deploy-preview-877--smarthr-design-system.netlify.app/ 
- https://deploy-preview-877--smarthr-design-system.netlify.app/introduction/ （例）
※Gatsbyの仕様上、devサーバ（`yarn dev`コマンドで起動）では確認できません。ローカルではビルドした`public/contact/index.html`ファイルを直接確認しました。
見た目上の変化はありません。
> ページを検索エンジンにindexするかどうかを指定する機能を追加

- content/articles/communication/mock.mdx
- 社内メンバーの一部が、[端末モックと画面キャプチャを合成できるFigmaファイル](https://www.figma.com/file/ul8bbn8p3aPIXo0DsjjsA6/%E7%AB%AF%E6%9C%AB%E3%83%A2%E3%83%83%E3%82%AF%E5%90%88%E6%88%90?type=design&node-id=723%3A121&mode=design&t=u1R3wDAgKOH9kDOk-1)を閲覧できない可能性があるため、[[端末モック](https://smarthr.design/communication/mock/)] 画面にフィードバック先を掲載しました。
- [[端末モック](https://smarthr.design/communication/mock/)] 画面にフィードバック先を掲載
- とくになし
https://deploy-preview-884--smarthr-design-system.netlify.app/communication/mock/#h2-3
> 端末モックのフィードバック先を追加

- src/components/shared/Private/Private.tsx
https://pxgrid.slack.com/archives/C018J0A6DCH/p1695197744014409?thread_ts=1695193755.228289&cid=C018J0A6DCH
プライベートコンテンツのマークダウンをHTMLに変換するパーサーを、micromarkからmarkedに置き換えました。
画像が入っているプライベートコンテンツが表示できていない問題があり、画像をbase64エンコードしてmdに埋め込む実装を検討していますが、micromarkは埋め込みの画像に非対応のため、markedにしたい、という事情です。marked自体は`ComponentPropsTable`などですでに使われています。
micromarkはここ以外では使われていませんが、ひとまず残しています。
micromarkが採用された理由はおそらくmdx用の拡張があるからなので、変換したいコンテンツが`.mdx`の場合にはmicromarkを使う、という実装にしてあります。
ただし、現在は.mdxのプライベートコンテンツは読み込んでいなさそうですし、.mdx＋埋め込み画像の場合にはパースできないため、.mdのみの対応で良いということであれば今後削除しても良さそうです。
プライベートコンテンツのあるページ：
https://deploy-preview-885--smarthr-design-system.netlify.app/basics/illustration/item/
https://deploy-preview-885--smarthr-design-system.netlify.app/basics/illustration/smarthr-co/ …
> プライベートコンテンツのmdパーサーを変更

- src/components/article/IndexNav/IndexNav.tsx
- src/components/article/IndexNav/IndexNavItems.tsx
#890 
https://pxgrid.slack.com/archives/C018J0A6DCH/p1697004960165319
右サイドバー部分で、PC/SP表示のコードを共通化した際に、元あったCSSが意図したとおりに適用されなくなっていたため、修正しました。
具体的にはgrid直下の要素に`overflow-y: auto`が適用されるのが正しいため、そのように修正しています。また、表示中の項目が画面内に入るよう、JSでスクロールさせる機能がありますが、そのスクロール対象の要素も合わせて修正しています。
右サイドバーがメインコンテンツより長くなるページで表示の不具合が発生していました。
ページ例：
https://deploy-preview-910--smarthr-design-system.netlify.app/products/contents/idiomatic-usage/usage/
https://deploy-preview-910--smarthr-design-system.netlify.app/products/components/
※不具合発生前のPRプレビュー例：https://deploy-preview-849--smarthr-design-system.netlify.app/products/components/
この時と同じ表示に戻っています。
|Before|After|
| --- | --- |
| <img src="https://github.com/kufu/smarthr-design-system/assets/7822534/d65a4c80-c633-45e7-b48a-c37e609b0a34" width="350" …
> 右サイドバーのPC表示時のCSSを修正

- content/articles/products/components/button.mdx
- plugins/gatsby-source-component-captures/fetchComponentCaptures.ts
https://pxgrid.slack.com/archives/C018J0A6DCH/p1697016863956069
プロダクト→コンポーネント→Button ページで、ページ内で使われているコンポーネントの `import`文がどこかの段階で消えてしまっていたようなので、追加しました。
他のコンポーネントのページもひととおり確認しましたが、上記のようなimport漏れはなさそうでした。（余分にimportされているページはあるかもしれませんが、その場合は表示不具合は起きないので、そのままにしてあります。）
https://deploy-preview-912--smarthr-design-system.netlify.app/products/components/button/#h2-2
|Before|After|
| --- | --- |
| <img src="https://github.com/kufu/smarthr-design-system/assets/7822534/6e6ef65a-47c4-45c7-bfdb-463404e0db8b" width="350" alt> | <img src="https://github.com/kufu/smarthr-design-system/assets/7822534/b05bab80-12b5-4883-9a31-345e59ceadd7" width="350" alt> |
> Buttonコンポーネントページの表示不具合を修正

- src/components/ComponentCaptures/ComponentCaptures.tsx
- src/components/article/PageIndex/PageIndex.tsx
- src/components/index/ContentNavigation/Category.tsx
- src/components/index/Faq/FaqItem.tsx
- src/components/index/Faq/FaqList.tsx
- src/components/index/Gotcha.tsx
- src/components/index/Introduction/Introduction.tsx
- src/components/login/Login.tsx
- src/components/search/IndexList/IndexList.tsx
- src/components/shared/Footer/Footer.tsx
- src/components/shared/Private/Private.tsx
- src/pages/404.tsx
- src/pages/search.tsx
ref: https://github.com/kufu/eslint-plugin-smarthr/tree/main/rules/a11y-heading-in-sectioning-content
ESLintで smarthr/a11y-heading-in-sectioning-content の警告が複数出ており、また依存するsmarthr-uiのバージョンが上がってPageHeadingコンポーネントが利用できるようになったので、警告に対処しました。
ページ全体の見出しとして `h1` でマークアップされていた箇所は `PageHeading`コンポーネントに置き換え、他は見出し（`h2`や`h3`）とそれに続くコンテンツをまとめて`Section`コンポーネントでラップしました。
トップページの、各カテゴリへのリンク部分について、`ul > li h2`のようなマークアップになっており、そもそも`h2`や`h3`があることが正しくない、またはリストであることが正しくないかもしれません。修正が必要であれば別途対応したいです。
`yarn eslint:ts`で警告がゼロになったことを確認しています。ページごとのマークアップの変化は以下です。
検索ページ、404ページ、ログインページ
→ `PageHeading`にするとスタイルが適用されて見た目が変わってしまう箇所もあったので、CSSも調整しています。
「SmartHR Design System」のところが `h2`なので、見出しが対応する範囲としてフッター全体を`Section`でラップしました。
- Gotchaのメインの画像部分が `Heading`という名前のコンポーネントになっていたのですが、見出しではないので名称を`GotchaMain`に変更しました。マークアップは以前から …
> ESLintで警告の出ていたheadingとsectioning contentを調整

- content/articles/communication/capture/capture-others.mdx
- content/articles/communication/capture/capture-product.mdx
https://github.com/kufu/smarthr-design-system/actions/runs/6528126011#summary-17723875304
同じページ内のアンカーリンクが今は存在しない`id`を指していたので、修正しました。
https://deploy-preview-923--smarthr-design-system.netlify.app/communication/capture/capture-product/
https://deploy-preview-923--smarthr-design-system.netlify.app/communication/capture/capture-others/
どちらも、本文5行目の「利用者・利用範囲」のリンク先が `#2-5`になっており、機能していなかったので正しいものに修正しました。
見た目上の変化はありません。
> リンク切れになっていたアンカーリンク先を再設定

- content/articles/products/components/calendar.mdx
`/products/components/calendar/` にて
- 1文目に主語 `Calendarコンポーネントは、` が抜けていたので追加しました
- DatePickerへの言及があったので、その部分をリンクに変更しました
- 
- Previewでみてね。→ https://deploy-preview-927--smarthr-design-system.netlify.app/products/components/calendar/
|Before|After|
| --- | --- |
| <img width="754" alt="image" src="https://github.com/kufu/smarthr-design-system/assets/7392923/df51f26c-5eb6-44be-9d67-08dd518af2e3"> | <img width="752" alt="image" src="https://github.com/kufu/smarthr-design-system/assets/7392923/d4ffa56e-3d49-4f73-a0b0-d2c866b871fe"> |
> Calendarを微修正

- content/articles/products/components/headline-area.mdx
- HeadlineArea `/products/components/headline-area/` の上部の「非推奨です」メッセージのCompactInformationPanelの表示が崩れていた
- 他の非推奨コンポーネントではCompactInformationPanelではなくBaseColumnを使っている
「非推奨です」の部分をBaseColumnに書き換え
- Previewでみてね。 https://deploy-preview-928--smarthr-design-system.netlify.app/products/components/headline-area/
|Before|After|
| --- | --- |
| <img width="772" alt="image" src="https://github.com/kufu/smarthr-design-system/assets/7392923/14202fc8-f4b9-4033-942b-6c57896e1312"> | <img width="753" alt="image" src="https://github.com/kufu/smarthr-design-system/assets/7392923/7bc5058e-2b6c-4c56-bada-808874366a60"> |
> HeadlineAreaの「非推奨」メッセージの表示崩れ修正

- content/articles/operational-guideline/page-template/component-template.mdx
- content/articles/products/components/button.mdx
- content/articles/products/components/dropdown/dropdown-menu-button.mdx
- content/articles/products/components/notification-bar.mdx
- package.json
- src/components/article/CodeBlock/CodeBlock.tsx
- src/components/article/CodeBlock/LiveContainer.tsx
- yarn.lock
closes kufu/smarthr-design-system-issues#1305
関連： #924 
[react-live](https://github.com/FormidableLabs/react-live)を使ったLiveEditorコンポーネントを、iframeに入れ、局所的に[smarhtr-normalize-css](https://github.com/kufu/smarthr-normalize-css)が適用されるようにしました。
実装は、以下のようになっています。
[react-frame-component](https://github.com/ryanseddon/react-frame-component)を使っています。そのまま `iframe`としても、styled-componentsのGlobalStyleはiframeを突き抜けてサイト本体のグローバルとして適用されてしまうためです。
ただし、このコンポーネントはGatsbyの静的ビルドではレンダリングされないようで、初回のページロード時のみうまく表示できません。そこで、[issue](https://github.com/ryanseddon/react-frame-component/issues/192#issuecomment-1153078390)を参考に、クライアントでのレンダリングをトリガーしています。
スクロールバーは出したくないので、iframeの中身のレンダリングが完了した時点で高さを計算し、iframeの`height`に設定しています。
LiveEditor部分は、「CDNからtypescriptの読み込みが終わってからCSRする」という実装になっているために、`DOMContentLoaded`が使えず、またtsの読み込み直後ではまだレンダリン …
> LiveEditorをiframe内に入れてCSSノーマライズを適用

- content/articles/products/components/dialog.mdx
- content/articles/products/components/notification-bar.mdx
- content/articles/products/components/tooltip.mdx
- content/articles/products/design-patterns/delete-dialog.mdx
closes kufu/smarthr-design-system-issues#1306
MDX内のコンポーネントコードから、`typeof window !== 'undefined'`によるレンダリング条件の分岐を削除しました。
条件分岐しているページとしていないページが混在していたので、元からないページはそのままです。（例えば FlashMessage。）
該当の箇所：
https://deploy-preview-950--smarthr-design-system.netlify.app/products/design-patterns/delete-dialog/#h2-1
https://deploy-preview-950--smarthr-design-system.netlify.app/products/components/dialog/#h2-1
https://deploy-preview-950--smarthr-design-system.netlify.app/products/components/notification-bar/#h3-1
https://deploy-preview-950--smarthr-design-system.netlify.app/products/components/tooltip/#h3-2
- 条件分岐の削除後も、ビルドおよびコードの実行が正常にできることを確認しました。
- ページロード時にコンソールに出ていたReactエラーがなくなったことも確認しました。
見た目上の変化はありません。
> MDX内のコンポーネントコードをサーバー側でもレンダリングするように変更

- netlify/edge-functions/private-fetch.ts
- package.json
- renovate.json
- src/components/ComponentPropsTable/ComponentPropsTable.tsx
- src/components/article/PageIndex/PageIndex.tsx
- src/components/contents/IdiomaticUsageTable/IdiomaticUsageTable.tsx
- yarn.lock
closes: kufu/smarthr-design-system-issues#1307
出ていた型エラーは3種類だったので、それぞれ対応しました。
https://github.com/kufu/smarthr-design-system/commit/ab9e1d24ea3108b6666ca9cdd8d872e1f08cd68b
`'XXXComponent' cannot be used as a JSX component` のようなエラー。
これらは、package.jsonに`devDependencies`として定義している`@types/react`のバージョンと、Reactに関係するパッケージ（styled-componentsやAlgoliaのreact-instantsearch-domなど）が依存する`@types/react`のバージョンがずれていることに起因していました。
package.jsonでの依存は`18.2.35`、各パッケージが依存するのはどれも`18.2.12`で、yarn.lockを確認するとこの2バージョンが共存している状態でした。
`18.2.12`に統一すると型エラーは出なくなったため、package.jsonで直接`18.2.12`を指定するようにしました。
パッケージ側が新しい型に対応するまでは、バージョンアップを避けたほうが良さそうなので、Renovateの自動マージも無効にしました。
https://github.com/kufu/smarthr-design-system/commit/2db0d3fd7921feefd5ef34ba6161dd0cb2a16ab0
Airtableやsmarthr-ui-props.json …
> TypeScriptの型エラーを解消

- package.json
- renovate.json
- yarn.lock
#960 で@types/react のバージョンを下げて型エラーが出ないようにしましたが、#963 で上がってしまい、再度エラーになっていました。パッチバージョンのアップデートでもエラーが再発する状況なので、Renovateによる自動マージが起こらないよう設定を変更しました。
- @types/reactをバージョン18.2.12に戻す
- Renovateの設定を更新
`npx tsc --noEmit` にてエラーが出なくなったことを確認しました。
ビルド後のサイトに影響はありません
> 型エラー回避のため@types/reactのバージョンを固定

- .stylelintrc
- package.json
- yarn.lock
#992 
上記PRでのLintのログ：https://github.com/kufu/smarthr-design-system/actions/runs/6999634767/job/19039192615?pr=992
stylelint-config-standard のアップデートに伴い、`media-query-no-invalid`ルールのLintエラーが数十個出るようになったため、ルールを無効にしました。
```
@media (max-width: ${CSS_SIZE.BREAKPOINT_MOBILE_2}) {...}
```
のような、styled-componentsとJS変数を用いたメディアクエリがすべて引っかかってしまうのですが、[stylelintのドキュメント](https://stylelint.io/user-guide/rules/media-query-no-invalid/)にも
> This rule is only appropriate for CSS. You should not turn it on for CSS-like languages, such as Sass or Less, as they have their own syntaxes.
と書かれており、CSS-in-JSな環境では無効にして良いのではという判断です。
SDSのstylelintのルールは、[stylelint-config-smarthr](https://github.com/kufu/stylelint-config-smarthr)も適用しているので、そちらでまとめて無効にするようなことがあれば、SDSでは特に指定しなくても良くなるかもしれません。
`yarn lint:style` …
> stylelint-config-standardのアップデートに伴いルールを調整

- src/components/ComponentStory/ComponentStory.tsx
products/components/ 以下の各コンポーネントで、Storybookの内容をiframeで表示しているが、ブラウザによりページロード時の表示が `404`（存在しないChromaticのURLにアクセスしてしまう）になっていたため、修正しました。
ChromaticのURLは、`https://2928bb8--63d0ccabb5d2dd29825524ab.chromatic.com/iframe.html?id=...` のようなフォーマットで、サブドメインの最初の7文字（`2928bb8`）がsmarthr-uiの各バージョンを表しますが、デフォルトでは空文字列で、ページロード後に表示すべきバージョンで上書きしていました。
この上書き時に、Chromeでiframeの更新がかかっていないケースがあったため、デフォルトバージョンを予めセットしておき、HTMLに静的に書き出されるように変更しました。
ページ例：https://deploy-preview-994--smarthr-design-system.netlify.app/products/components/button/
プルダウンでのバージョン切り替え時には、該当のバージョンのURLへのリクエストが行われていることも確認しました。
|Before|After|
| --- | --- |
| <img src="https://github.com/kufu/smarthr-design-system/assets/7822534/af5de08c-8e79-4db0-bb10-76956480eef5" alt width="350"> | <img src="https://github.com/kufu/smarthr-design-system/assets/7822534/1 …
> Storybookのiframe URLの初期値を予めセットしておくように変更

- src/components/ComponentStory/ComponentStory.tsx
#994 の変更に伴い、コードのほうがページロード時に取得できなくなっていました。
GitHubからのコード取得（`fetch`）をトリガーする条件を調整しました。
初期表示バージョンのコードだけでもサーバー側でセットしておいても良いのかもしれませんが、未検討です。
https://deploy-preview-995--smarthr-design-system.netlify.app/products/components/accordion-panel/
|Before|After|
| --- | --- |
| <img src="https://github.com/kufu/smarthr-design-system/assets/7822534/682b44f6-f6bc-4c16-af03-73a09dd1df4b" alt width="350"> | <img src="https://github.com/kufu/smarthr-design-system/assets/7822534/5970c447-89eb-4201-bec8-1fa5bbd237f2" alt width="350"> |
> Storybookのコードが取得できていない不具合を修正

- src/components/shared/Footer/Footer.tsx
#843 にて、フッターの一番左のカラム（ロゴ・ログインボタンなどのところ）を`<section>`要素で囲ったため、gridアイテムの適用先が変わってしまい、余白が消えていました。
`<section>`の子要素がgridアイテムになるよう、CSSを調整しました。
https://deploy-preview-997--smarthr-design-system.netlify.app/
#843 より前のPRのプレビューを参照し、その時と同じ余白に戻ったことを確認しました。
|Before|After|
| --- | --- |
| <img src="https://github.com/kufu/smarthr-design-system/assets/7822534/d9386ca6-afcd-4152-8b02-0f1d939959c5" alt width="350"> | <img src="https://github.com/kufu/smarthr-design-system/assets/7822534/e1ea81ee-7b23-43d9-a587-13f60440eff4" alt width="350"> |
> フッターのログインボタン周辺の余白を修正

- package.json
- plugins/gatsby-source-ui-versions/gatsby-node.ts
https://pxgrid.slack.com/archives/C018J0A6DCH/p1701404956773799
`smarthr-ui.css`を `/static`以下に配置し、ライブエディタのiframeで読み込んでいるが、自動的にコピーされるようにしたい。
以下の2つを実装してみています。どちらかでも良いのかもしれません。
どちらも`node_modules/smarthr-ui/smarthr-ui.css` を `static/` にコピーしています。
`package.json`の`postinstall`に、`cp`コマンドを追加しました。
- リポジトリをcloneして`yarn (install)` すればコピーされる
- smarthr-uiのバージョンを上げる際も、手動で`yarn`は実行すると思うので、そこでもコピーされる
- Netlify上でも`yarn --frozen-lockfile`が実行されるので、ビルド前にコピーされる
Gatsbyプラグインには、ビルド前や後に実行できるフックがあるので、smarthr-uiのコードなどを取得しているgatsby-source-ui-versionsプラグインに、`onPreInit`フックを追加しました。ビルドのたびにコピーされます。
- ビルドするごとに実行されるので、コピーが動く回数は多くなる
- `yarn dev`した場合にもコピーされる
- smarthr-uiのバージョンが上がった後などに、ローカルで`yarn (--frozen-lockfile)`**しない**人がいれば、古いバージョンのCSSがコピーされる可能性がある
- → .gitignore にCSSファイルを追加しておくほうが良い？ …
> smarthr-ui.cssをコピーするしくみを追加

- src/components/shared/Header/Header.tsx
closes kufu/smarthr-design-system-issues#1311
smarthr-uiのDialogコンポーネントに、固定値として`15px`の余白をpropsとして渡すようにしました。
元々は`rem`を使った余白がCSSで指定されており、また画面幅によっても変化させていましたが、いったんpx単位の固定値になっています。
https://deploy-preview-1024--smarthr-design-system.netlify.app/
→ SP幅でハンバーガーメニューを開く
余白がなく右上にくっついてたのが上下左右均等な余白に戻りました。
|Before|After|
| --- | --- |
| <img src="https://github.com/kufu/smarthr-design-system/assets/7822534/f9d6ec92-453c-4c86-bd0b-2ac9eebeb30a" alt width="350"> | <img src="https://github.com/kufu/smarthr-design-system/assets/7822534/00a44fd8-96ca-4f91-9dca-6d750742775d" alt width="350"> |
> SP版のメインメニューのレイアウトを調整

- scripts/content-checker/storybookUrlChecker.ts
#1026 で、gatsby-plugin-ui-versionsにキャッシュ機能を追加しましたが、StorybookのURLチェッカーからもプラグイン内のコードを利用しており、合わせて変更が必要でした。
チェックの際にはキャッシュは使わず、オプションを渡してデータを取得するようにしました。
このブランチにて、手動でチェックを実行しました：https://github.com/kufu/smarthr-design-system/actions/runs/7286011908
サイト本体には影響しません。
> Storybook checkerをプラグインに合わせて修正

- src/components/article/CodeBlock/CodeBlock.tsx
- src/components/article/CodeBlock/LiveContainer.tsx
closes kufu/smarthr-design-system-issues#1313
CodeBlockのライブエディタ部分をiframe（react-frame-component）い入れていましたが、編集時にエラーが出るため、エディタ部分のみiframeの外に出しました。
NotificationBarページで、以下のテキストの折り返しが効かなくなっていますが、ここは元からiframeの適用外で、別の問題と思われるので、何もしていません。
https://smarthr.design/products/components/notification-bar/#h3-2
ライブエディタのあるページ：
https://deploy-preview-1048--smarthr-design-system.netlify.app/operational-guideline/page-template/component-template/
https://deploy-preview-1048--smarthr-design-system.netlify.app/operational-guideline/page-template/style-template/
https://deploy-preview-1048--smarthr-design-system.netlify.app/products/components/badge/
https://deploy-preview-1048--smarthr-design-system.netlify.app/products/components/button/
https://deploy-preview-1048--smarthr-design-system.netlify.app/products/compo …
> LiveEditorのエディタをiframeの外に移動

- content/articles/basics/colors/index.mdx
- content/articles/basics/icons/index.mdx
- content/articles/basics/illustration/index.mdx
- content/articles/basics/illustration/item.mdx
- content/articles/basics/illustration/scene.mdx
- content/articles/basics/illustration/smarthr-co.mdx
- content/articles/basics/illustration/user-co-main.mdx
- content/articles/basics/illustration/user-co-other.mdx
- content/articles/basics/logos/index.mdx
- content/articles/basics/logos/motion.mdx
- content/articles/basics/logos/sound.mdx
- content/articles/basics/meta/index.mdx
- content/articles/communication/capture/capture-others.mdx
- content/articles/communication/capture/capture-product.mdx
- content/articles/communication/capture/kit.mdx
- content/articles/communication/capture/service-capture-in-mock.mdx
- content/articles/communication/eye-catching-images.mdx
- content/articles/communication/mock.mdx
- content/articles/communication/photography/jingle-movie.mdx
- content/articles/communication/slides.mdx
- content/articles/introduction/user/smarthr_employee.mdx
- content/articles/products/index.mdx
アプリストアSmartHR Plusを2023/12/4に正式リリースしたことに伴い、SmartHR Design System内のすべての表記を「SmartHR Plus β版」から「SmartHR Plus」に変更しました。
- SmartHR Design System内のすべての表記を「SmartHR Plus β版」から「SmartHR Plus」に変更
- どこを変更したのか？の確認は、[Files changedタブ](https://github.com/kufu/smarthr-design-system/pull/1058/files)からお願いします🙏
- とくになし
変更箇所が多いため、割愛します
変更箇所が多いため、割愛します
> SmartHR Design Systemに掲載している表記「SmartHR Plus β版」から「β版」をトル

- content/articles/communication/photography/index.mdx
- content/articles/communication/photography/jingle-movie.mdx
[[写真・動画](https://smarthr.design/communication/photography/)] 配下にどんなコンテンツがあるのか？が分かりづらいので、コンテンツの内容を掲載しました。
- [[写真・動画](https://smarthr.design/communication/photography/)] に、配下にあるコンテンツ「[オフィス写真](https://smarthr.design/communication/photography/photography-office/)」と「[ジングルムービー](https://smarthr.design/communication/photography/jingle-movie/)」の概要を掲載しました。
- とくになし
https://deploy-preview-1059--smarthr-design-system.netlify.app/communication/photography/
|Before|After|
| --- | --- |
| ![CleanShot 2024-01-11 at 11 41 23@2x](https://github.com/kufu/smarthr-design-system/assets/101125529/674c7ee4-6e00-440d-886d-0542a9ae613d) | ![CleanShot 2024-01-11 at 11 37 01@2x](https://github.com/kufu/smarthr-design-system/assets/101125529/2d8ed7aa-1ed6-430f-b53b-9773fd41c2c7) |
> 「写真・動画」のコンテンツの内容をindexに掲載

- content/articles/products/components/tooltip.mdx
Tooltipはユーザビリティやアクセシビリティ観点での懸念点があるため、積極的使用するものではないと思っています。
デザインシステムの Tooltip のページでも「[使用上の注意](https://smarthr.design/products/components/tooltip/#h2-0)」として記載されています。
しかし、「スペースがないからTooltipにしよう」という判断が割とされやすい状況があるように感じています。
「絶対にTooltipを使用しないようにしよう」と言いたいわけではないのですが、「スペースをあまり使いたくない」という理由から即「tooltipを採用しよう！」という判断になることを避けたいなと思いました。
そこで、判断基準をより明確に定義するとわかりやすくなるのではないかと思い、PRを出しました。
[#design_system_相談](https://kufuinc.slack.com/archives/CJX59GJFR/p1700046626026089)でも相談させてもらっている件です。
Tooltipに関する注意点をより具体化し、推奨ではないことが伝わりやすくしました。
[#design_system_相談](https://kufuinc.slack.com/archives/CJX59GJFR/p1700046626026089)で相談した内容を[SmartHRでのルール](https://smarthr-inc.docbase.io/posts/3184432#smarthr%E3%81%A7%E3%81%AE%E3%83%AB%E3%83%BC%E3%83%AB)にまとめ、その内容をデザインシステムに反映しています。
|Before|After|
| --- | --- |
|  |  |
> Tooltipの使用上の注意をより具体化した

- content/articles/products/contents/help-center/error-handling.mdx
- 去年、yunakさんとokeの全ページ修正・整理したことで「よくある質問」の例として適切じゃなくなったページがある
- ２ページ分の例の削除
- 代わりに1ページの例を追加
|Before|After|
| --- | --- |
|  |  |
> 記載例として適切じゃないページの削除

- content/articles/products/design-tokens/typography.mdx
[タイポグラフィ | デザイントークン | SmartHR Design System](https://smarthr.design/products/design-tokens/typography/#h2-0)
書体の理由に、さまざまな言語で正しくレンダリングされることを追加
- 文章を追加
|Before|After|
| --- | --- |
| <img width="737" alt="Beforeスクリーンショット「ユーザーが慣れ親しんでいる環境を尊重し、以下の書体を指定します。」" src="https://github.com/kufu/smarthr-design-system/assets/6724665/64a9120f-2389-42df-b136-f62de32ddf49"> | <img width="754" alt="Afterスクリーンショット「ユーザーが慣れ親しんでいる環境を尊重し、またOSの設定に委ねることでさまざまな言語で正しくレンダリングされることを期待し、以下の書体を指定します。」" src="https://github.com/kufu/smarthr-design-system/assets/6724665/c782a568-66e6-4205-bef0-b328dee98065"> |
> feat: font-familyに多言語の理由を追加

- content/articles/products/components/status-label.mdx
StatusLabelコンポーネントのガイドラインに使用上の注意を追加しました。
https://deploy-preview-1131--smarthr-design-system.netlify.app/products/components/status-label
パッと思いついたものを記述しました。過不足ふくめレビューお願いいたします。
> StatusLabelのコンポーネントのガイドラインに使用上の注意を追加する

- content/articles/products/components/text.mdx
- content/articles/products/design-tokens/leading.mdx
- content/articles/products/design-tokens/typography.mdx
https://smarthr.atlassian.net/browse/SD-692
- コンポーネントとして利用頻度がNo.1のTextのページを充実
- Storybookにあった注意点を「使用上の注意」に転記
- propsの説明と実装例を追加
- デザイントークンのページからTextにリンク
- タイポグラフィ
- ついでにWIPだった「強調」を埋めた
- 行送り
- なし
- Previewでみてね。
- https://deploy-preview-1142--smarthr-design-system.netlify.app/products/components/text/
- https://deploy-preview-1142--smarthr-design-system.netlify.app/products/design-tokens/typography/
- https://deploy-preview-1142--smarthr-design-system.netlify.app/products/design-tokens/leading/
|Before|After|
| --- | --- |
|  |  |
> Textの内容を充実、デザイントークンからリンク

- content/articles/products/components/compact-information-panel.mdx
https://smarthr.atlassian.net/browse/SD-641
- `CompactInformationPanel`は`NotificationBar[base="base"]`で代替が可能になったため非推奨にします。
- smarthr-uiも平行して対応中です。
- https://github.com/kufu/smarthr-ui/pull/4622
- Previewでみてね。
- https://deploy-preview-1150--smarthr-design-system.netlify.app/products/components/compact-information-panel/
|Before|After|
| --- | --- |
|  |  |
> CompactInformationPanelを非推奨にする

- content/articles/products/components/dropdown/index.mdx
- https://smarthr.design/products/components/dropdown/ の派生コンポーネントへのリンク切れを修正
- リンク切れを修正
以下のリンクの遷移先にある3つのリンクが機能することを確認してください。
https://deploy-preview-1170--smarthr-design-system.netlify.app/products/components/dropdown/#h2-0
比較対象は以下のリンクより確認できます。
(なぜかFilterDropdownはうごく 全ては謎…)
https://smarthr.design/products/components/dropdown/#h2-0
|Before|After|
| --- | --- |
|  |  |
> Dropdownの派生コンポーネントへのリンク切れを修正

- content/articles/products/design-patterns/contents-in-header/index.mdx
`contents-in-header`の画像のパスが間違っていた。
ローカルで画像が表示されない
- 画像のパスを画像ファイルの位置に合わせた
- ローカルで画像が表示されないのは変わらなかった
以下のURLで画像が表示されていることを確認
https://deploy-preview-1180--smarthr-design-system.netlify.app/products/design-patterns/contents-in-header/
> 画像のパスを実際のファイルの位置に変更

- content/articles/basics/illustration/index.mdx
- content/articles/basics/illustration/smarthr-co.mdx
- content/articles/operational-guideline/page-template/style-template.mdx
- content/articles/products/components/check-box/index.mdx
- content/articles/products/components/combo-box/multi-combo-box.mdx
- content/articles/products/components/combo-box/single-combo-box.mdx
- content/articles/products/design-patterns-core-features/access-control-setting-pattern.mdx
- content/articles/products/design-patterns/modal-ui/index.mdx
- src/components/DoAndDont/DoAndDont.tsx
- `DoAndDont`コンポーネントにwidthプロパティを追加
- `StaticImage`コンポーネントのwidthではなく、`DoAndDont`コンポーネントのwidthを使うことで、labelが適切に折り返すようになります。
- モバイル表示時は幅いっぱい表示するように
- 
https://deploy-preview-1188--smarthr-design-system.netlify.app/operational-guideline/page-template/style-template/#h2-12
|Before|After|
| --- | --- |
|  |  |
> DoAndDontコンポーネントにwidthプロパティを追加、使用ページの修正

- content/articles/products/components/dialog/action-dialog.mdx
旧Dialogを、
```
dialog/
├ index
├ ActionDialog
├ MessageDialog
└ ModelessDialog
```
の4つに分けたうちの、ActionDialogの分です。
関連PR
#1201 
#1203 
#1204
-
- 
|Before|After|
| --- | --- |
|  |  |
> ActionDialogを分離

- content/articles/products/design-patterns/feedback/index.mdx
読んでて気になったので提案しましたが、棄却でも問題ないです!
> 💬: 同期処理の “同期” を読み違える可能性があったので “同期的な” に修正

- package.json
意識して `yarn clean` や `yarn gatsby clean` しなくてもいいように `predev` に足しました。
> 👷: yarn dev がよくコケるので predev で gatsby clean する

- content/articles/communication/photography/index.mdx
- 「[写真・動画](https://smarthr.design/communication/photography/)」内のテキストリンクのURLがリンク切れになっていたので、正しいURLに変更
- 「オフィス写真」と「ジングルムービー」のリンク先に、正しいURLを指定
-掲載場所：コミュニケーション > 写真・動画
- とくになし
https://deploy-preview-1243--smarthr-design-system.netlify.app/communication/photography/
> 写真・動画 > コンテンツ内容のURLを変更

- content/articles/products/design-patterns/mobile-friendly-layout/index.mdx
実装では `isNarrowView` になっているため修正
- `isNarrowScreen` を`isNarrowView` に修正
- なし
|Before|After|
| --- | --- |
|  |  |
> fix: 実装に合わせて`isNarrowScreen` を `isNarrowView` に修正

- content/articles/products/components/radio-button/index.mdx
https://kufuinc.slack.com/archives/CJX59GJFR/p1725504495865029
- RadioButtonページのSingleComboBoxへのリンクがtypoしてたので修正した
- 
https://deploy-preview-1260--smarthr-design-system.netlify.app/products/components/radio-button/#h4-0
|Before|After|
| --- | --- |
|  |  |
> RadioButtonページのリンクミスを修正

- content/articles/products/design-patterns/smarthr-table.mdx
見出しが不適当だったため修正しました。
0ページを指しているわけではなく、1ページに収まる場合を指していたので「以内」としました。
> ✏️: 1ページ未満 → 1ページ以内

- astro.config.mjs
- package.json
- pnpm-lock.yaml
- src/components/ComponentPreview/ComponentPreview.tsx
- src/components/ComponentPreview/ProductWrapper.tsx
- src/components/ComponentPreview/README.md
- src/components/ComponentPreview/WrapperBase.tsx
- src/components/ComponentPreview/index.ts
- src/components/MDXComponents/CodeBlock.astro
- src/components/article/CodeBlock/CodeBlock.tsx
- src/components/article/CodeBlock/CopyButton.tsx
- src/components/article/CodeBlock/DesignPatternCodeBlock.tsx
- src/components/article/CodeBlock/LiveContainer.tsx
- src/components/article/CodeBlock/README.md
- src/components/article/CodeBlock/index.ts
- src/pages/[...slug].astro
- src/remark/remark-code-block.ts
Astro 移行
- 記事内のコードブロック部分のコンポーネントを移植しました
- Storybook の部分のコンポーネントは移植していないので、 ResizableContainer を利用している箇所はコメントアウトしています
> コードブロック (ライブエディタ) を移植

- src/components/CodeBlock/CopyButton.tsx
- src/components/CodeBlock/LiveContainer.tsx
- src/components/CodeBlock/index.tsx
- src/components/ComponentPreview/ProductWrapper.tsx
- src/components/ComponentPreview/index.tsx
- src/components/ComponentStory/index.tsx
- src/components/ResizableContainer/index.tsx
- src/components/article/Article.astro
- src/components/article/CodeBlock.astro
- src/components/article/ComponentPropsTable/TypeTag.tsx
- src/components/article/ComponentPropsTable/index.tsx
- src/components/article/ComponentStory.astro
- src/components/article/CustomLink/index.tsx
- src/components/article/DesignPatternCodeBlock/index.tsx
- src/components/article/FragmentTitle/index.tsx
- src/pages/[...slug].astro
- Astro移行
Astroコンポーネントが実質的にdefault exportなので、named exportが混ざっているとMDXでimportする際に戸惑う場面があったので統一しました
- Reactコンポーネントをdefault exportに統一
↓
> default exportに統一

- src/components/shared/Header/Header.tsx
smarthr-ui の Dialog に top / right / bottom / left を指定できなくなったため、styled-components で上書きました。
Before | After
--- | ---
> fix: smarthr-ui の追従によるモバイルメニュー崩れを修正

- package.json
- static/smarthr-ui.css
- yarn.lock
smarthr-ui [v58.1.1](https://github.com/kufu/smarthr-ui/releases/tag/v58.1.1) に追従しました。
特に影響のない変更のため取り込みのみ。
- 
|Before|After|
| --- | --- |
|  |  |
> ⬆️: smarthr-ui を v58.1.1 に更新

- package.json
- Astro化
- `pnpm build` で `astro check` を実行しないように
- ESLint を導入している & husky や CI で実行しているので、ビルド時に動かす必要はないはず
> buildでastro checkを実行しないように

- src/components/Head.astro
- src/layouts/ArticleLayout.astro
- Astro化
- ページのタイトル形式を修正しました
- タイトルに親のカテゴリー名が無い (色 | デザイントークン のようなもの)
- タイトル末尾に SmartHR Design System が無い
> fix: ページタイトルの形式が異なる

- src/components/CodeBlock/ComponentPreview.tsx
- src/components/article/CodeBlock.astro
- Astro化
- ```tsx layout="product"` のような指定ができない問題を修正しました
> fix: Markdownの書式でCodeBlockのlayout="product"が指定できない

- .github/workflows/deploy-to-netlify.yml
- scripts/update-algoliasearch.ts
- Astro化
- スクリプトが動作するよう修正
- デプロイのワークフローで実行するよう追加
Gatsby のプラグインでは ObjectID に内部で生成された ID が使われていましたが、移行に伴い ObjectID にページのパスを使うよう変更しました。
これにより、同じインデックスが2重で登録されてしまうので、初回デプロイ時のみ手元でコマンドを実行して本番環境のインデックスをまるごと入れ替える必要がありそうです。
インデックスの入れ替えは
```
pnpm tsx ./scripts/update-algoliasearch.ts --replace-all
```
で実行できるようにしています。
> Algoliaのインデックスを更新するスクリプトを修正

- src/components/article/DoAndDont.astro
- src/content/articles/operational-guideline/page-template/style-template.mdx
- src/content/articles/products/components/check-box/index.mdx
- src/content/articles/products/components/combo-box/multi-combo-box.mdx
- src/content/articles/products/components/combo-box/single-combo-box.mdx
- src/content/articles/products/components/drop-zone/index.mdx
- src/content/articles/products/components/information-panel/index.mdx
- src/content/articles/products/components/input/index.mdx
- src/content/articles/products/components/radio-button-panel/index.mdx
- src/content/articles/products/components/radio-button/index.mdx
- src/content/articles/products/components/textarea/index.mdx
- src/content/articles/products/design-patterns-core-features/access-control-setting-pattern.mdx
- src/content/articles/products/design-patterns/mobile-friendly-layout/index.mdx
- src/content/articles/products/design-patterns/modal-ui/index.mdx
- src/content/articles/products/design-patterns/smarthr-table.mdx
- src/content/articles/products/design-patterns/visual-guidance/index.mdx
- Astro化
- DoAndDontコンポーネントのslot名をlabelに変更
- 移植前の該当するProp名がLabelだったため
> DoAndDontのslot名をtextからlabelに変更

- src/components/article/ComponentStory.astro
- Astro化
- 特に PC で ComponentStory のレイアウトシフトが大きかったので軽減しました
- スマホではプレースホルダーの高さと実際の高さが異なり、若干のレイアウトシフトが起きますが、ファーストビューに ComponentStory 全体が入ることはほぼないので考慮していません
|Before|After|
| --- | --- |
| ![before](https://github.com/user-attachments/assets/9d7c614f-84a9-4a16-b713-37d2faba14c3) | ![after](https://github.com/user-attachments/assets/a778ee5f-4846-4f7f-924b-5e4a28ce188e) |
> ComponentStoryのレイアウトシフトを軽減

- src/components/Header/Header.astro
- src/components/Header/MobileMenuContainer.tsx
- src/components/search/Search/SearchResultOuter.module.scss
- src/content/articles/products/usability/_components/UsabilityCheckListWarning.tsx
- src/data/indexContent.json
- src/data/navigationItem.json
- src/lib/throttle.ts
- src/pages/search.astro
- Astro化
- SearchBoxと同じ高さをフォールバック要素に指定し、検索ページのレイアウトシフトを軽減
- スマホヘッダーのハンバーガーメニューをビルド時にもレンダリングするように変更し、ヘッダーのレイアウトシフトを改善
|Before|After|
| --- | --- |
| ![before](https://github.com/user-attachments/assets/3841374a-3dd2-4315-9a65-9121a48896da) | ![after](https://github.com/user-attachments/assets/a14870d7-a7e5-4512-abb9-2b7b04afa9db) |
|Before|After|
| --- | --- |
| ![sp-before](https://github.com/user-attachments/assets/0224cc26-3231-476c-b97e-74307c008690) | ![sp-after](https://github.com/user-attachments/assets/448e7463-e9ba-4ee8-b6ca-f2de1a14618b) |
> アイランドコンポーネント部分のレイアウトシフトを軽減・改善

- src/components/article/ComponentPropsTableTag.astro
- Astro化
- PropTable のタグが適切に改行されず突き抜ける場合がある問題を修正しました
- ComponentPropsTableTag の span に `word-break: break-word` を付け、適切に改行されるように
(tertiaryLinks の箇所)
|Before|After|
| --- | --- |
| ![image](https://github.com/user-attachments/assets/43910a32-3fdd-418e-a345-88d1e5807755) | ![image](https://github.com/user-attachments/assets/791ae3fb-01f9-4f69-adfd-6ba5d4a0c2aa) |
> PropTableのタグが適切に改行されず突き抜ける場合がある

- src/components/ComponentStory/index.tsx
- Astro化
- ファイルではなく、その親ディレクトリを開くようリンクを修正
↓この部分
> fix: GitHubのリンク先がファイルになっていたので修正

- content/articles/products/design-tokens/z-index.mdx
FloatArea の z-index 値がマジックナンバーだったため、定義しました。
smarthr-ui を同時修正中。 https://github.com/kufu/smarthr-ui/pull/5066
レイヤー順序の FIXED_MENU に FloatArea へのリンクを追加。
- 
|Before|After|
| --- | --- |
|  |  |
> 📝: レイヤー順序に FloatArea を追加

- content/articles/accessibility/index.mdx
アクセシビリティディレクトリ内のページから、アクセシビリティの品質基準のページへの動線が一個もなかった
- アクセシビリティのトップページに、品質基準へのリンクを追加した
- 
|Before|After|
| --- | --- |
|  |  |
> アクセシビリティのトップページから品質基準ページ（プロダクト内）へリンクさせる

- content/articles/products/components/bottom-fixed-area.mdx
非推奨メッセージをResponseMessageで実装したら、Flexで意図しない形になってしまっていたので Icon with Text での実装に変えました
- 
スクショとコードだけ見ていただければ
|Before|After|
| --- | --- |
| <img width="420" alt="image" src="https://github.com/user-attachments/assets/685364c3-e086-4fbc-b13b-51add7bcd011"> | <img width="402" alt="image" src="https://github.com/user-attachments/assets/f33c78eb-5333-4c49-890c-efd75e83b646"> |
> BottomFixedAreaの非推奨メッセージを修正

- astro.config.mjs
Gatsbyのプリフェッチのタイミングがリンクがビューポートに入ったら、だったのでそれに合わせました
> https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/#link-drives-gatsbys-fast-page-navigation
- リンクがビューポートに入ったらprefetchするよう設定を変更
> feat: リンクがビューポートに入ったらprefetchするように

- content/articles/products/components/radio-button/index.mdx
何も入力しない場合は、「選択しない」をつくれる
- [スレ](https://kufuinc.slack.com/archives/CDG1XRPTP/p1730784640694019?thread_ts=1730773802.634249&cid=CDG1XRPTP)をうけて、何も選択しない選択肢はありなので、実態に合わせるように変更
- 以下の文章を削除
`何も入力しない状態を選択肢として用意したい場合にはSelectの使用を推奨します。` 
- なし
https://deploy-preview-1363--smarthr-design-system.netlify.app/products/components/radio-button/
|Before|After|
| --- | --- |
| <img width="754" alt="スクリーンショット 2024-11-05 15 23 22" src="https://github.com/user-attachments/assets/b8c4c73b-4c10-41ae-95ac-cc3d38481d74"> | <img width="750" alt="image" src="https://github.com/user-attachments/assets/973b6b32-a6f5-4f51-a7ee-220dd8db0d56"> |
> [RadioButton]Select推奨の一文を削除

- src/components/article/ResponsiveImage.astro
フィードバック: 7
> プレビューで表示される画像全般、現行サイトに比べて画質が落ちている気がする
画像のフォーマットを webp から png に変更し、画像のクオリティを優先するように変更しました
また、サイズは 13KB -> 9KB と減少しました
| Before | After |
|-|-|
| <img width="503" alt="image" src="https://github.com/user-attachments/assets/a98c1359-e7e3-49db-846f-22d6738450c1"> |<img width="709" alt="image" src="https://github.com/user-attachments/assets/e4283249-1a61-4731-98fa-9b5ac4b8d79a"> |
- 
|Before|After|
| --- | --- |
|  |  |
> 画像のフォーマットと圧縮率を変更

- netlify.toml
- package.json
Netlifyでのビルド時にAlgoliaのインデックスを更新するスクリプトを走らせていなかったので修正しました
- `build:prod` を追加し、Netlifyではこれを実行するよう変更しました
> fix: Netlifyでのビルド時にAlgoliaのインデックスを更新するように

- .gitignore
`.cache` `.netlify` `public` を除外したい
- .gitignoreに上記ディレクトリを追加しました
- また、Gatsby版の .gitignore を参考に `storybook-static/` を追加しました
- 
|Before|After|
| --- | --- |
|  |  |
> 除外するディレクトリを追加

- src/components/search/Search/SearchBox.tsx
- src/pages/search.astro
AlgoliaのAPIキーが無い場合、検索ページが壊れているように見える
- clientの作成前に環境変数を確認して、無い場合警告を表示するように
- 移行により `isAvailable` が機能しなくなっていたため削除
> 検索に必要なenvが不足している場合警告を表示するように

- src/components/ComponentStory/index.tsx
フィードバック 11
> コンポーネントのプレビュー部分の [GitHub] ボタンを押すと、stories ディレクトリがあるコンポーネントはそこに飛んでしまう (コンポーネントのrootに飛んでほしい)
- `stories.filePath` から `stories/` も削除するようにして、リンク先は常にコンポーネントのルートを指すように修正しました
- 
|Before|After|
| --- | --- |
|  |  |
> GitHubのリンク先がコンポーネントのルートを指すように

- src/components/index/Gotcha/index.module.scss
lighthouseのアクセシビリティスコアがガチャのリンク部分が小さくアイテムごとの空白が少ないことにより下がっています。
↓の画像は過去3ヶ月のlighthouseのアクセシビリティスコアの遷移をグラフにしたものです。満点の時と5ptほどスコアを下げている時があります。
この原因がこのPRで対策した「Touch targets do not have sufficient size or spacing.」という評価基準です。
> https://dequeuniversity.com/rules/axe/4.10/target-size
lighthouseはタッチ部分のサイズが24px x 24pxより大きいか、他のタッチ部分と8pxの間が空いているかを評価基準にしています。
リンク同士に8pxのgapを設定しました。
24px x 24pxのタッチサイズを確保するのはデザイン上変更が大きいかなと思ったのでリンク同士のgapで対応しました。
netlifyのブランチプレビューをlighthouseにかけていただければ修正されていることがわかるかと思います。
|Before|After|
| --- | --- |
|![Pasted_Image_2024_11_19__2_46](https://github.com/user-attachments/assets/27a68a54-1706-49f5-b92f-99c593a80c39) |![Pasted_Image_2024_11_19__2_43](https://github.com/user-attachments/assets/9493f647-7268-4fb0-96ef-229438747a9f)|
> lighthouseのアクセシビリティスコア向上のため、ガチャのリンク部分のスペースを広くする

- src/content/articles/accessibility/low-vision.mdx
Storybookの整理後BaseColumn componentのdocsページのリンク先が変わったため、弱視・ロービジョンのユーザーについてのページでリンク先がエラになってる
https://smarthr.atlassian.net/browse/SD-952
- アクセシビリティコンテンツの「弱視・ロービジョンのユーザーのウェブ利用時の課題と解決案」ページ内のBaseColumn componentのリンク切れを修正
- 見た目の調整
ファイル上でリンク先が確認取れると十分と思いますが、previewでも確認できます
Before - リンク切れ
https://smarthr.design/accessibility/low-vision/#h2-1
After - Storybook docs page
https://deploy-preview-1434--smarthr-design-system.netlify.app/accessibility/low-vision/#h2-1
> fix: 弱視・ロービジョンのユーザーに付いてページのstorybookリンク切れ修正

- src/content/articles/products/components/base/base-column.mdx
- [BaseColumn](https://smarthr.design/products/components/base/base-column/) における `Dialog` へのリンクが `InformationPanel` へのリンクになっていたので修正しました
- 🍐 
- 念のため動作確認用のリンクはこちら
- https://deploy-preview-1465--smarthr-design-system.netlify.app/products/components/base/base-column/
|Before|After|
| --- | --- |
|  |  |
> リンクの指定ミスを修正

- src/content/articles/communication/capture/capture-product.mdx
https://smarthr.atlassian.net/browse/SD-841
- [SmartHRオプション機能](https://smarthr.design/communication/capture/capture-product/#h2-1)の[カスタム社員名簿機能](https://smarthr.design/communication/capture/capture-product/#h3-2)をセクションごと削除
- 新たに追加する画面の検討
- Previewでみてね。
|Before|After|
| --- | --- |
| ![CleanShot 2024-12-20 at 18 13 41@2x](https://github.com/user-attachments/assets/1b0a44a0-0608-4b2c-b778-5fdb72aca8ca) | ![CleanShot 2024-12-20 at 18 13 48@2x](https://github.com/user-attachments/assets/68886ec7-4209-4f38-8a0a-a1ad9e9a2543) |
- 赤枠の部分を変更
> カスタム社員名簿機能の画面キャプチャを取り下げる

- src/content/articles/products/components/text-link/index.mdx
- 「新規ウィンドウで開くテキストリンク」が必須であることを明記・強調
- 「ヘルプセンターを開くテキストリンク」が推奨であることを強調
- 新規ウィンドウとヘルプセンターが同時のときには新規ウィンドウを優先することを明記
- 
- プレビューで確認
- https://deploy-preview-1432--smarthr-design-system.netlify.app/products/components/text-link/#h2-1
|Before|After|
| --- | --- |
|  |  |
> [TextLink]新規ウィンドウで開くときとヘルプページを開くときが同時のときを対処を記載

- src/content/articles/products/design-patterns/permissions-settings.mdx
[権限設定](https://smarthr.design/products/design-patterns/permissions-settings/#h4-5)のページにて、「操作の権限が2つ以内の場合はRadioButtonPanelを使ってください」という表記があるが、2つ以内に限定する必要はないため、その記載を削除したい。
cf. [2つ以内の表記が妥当かの相談スレ](https://kufuinc.slack.com/archives/CDG1XRPTP/p1734073128762699)
- 削除した
- 🍐 
https://deploy-preview-1479--smarthr-design-system.netlify.app/products/design-patterns/permissions-settings/#h4-5
|Before|After|
| --- | --- |
|  |  |
> 権限編集ダイアログ内のRadioButtonPanelの個数制限を削除

- src/content/articles/communication/eye-catching-images.mdx
- コミュニケーション＞アイキャッチページにある使い方の説明figmaへのリンクを削除する。
- https://smarthr.atlassian.net/browse/SD-989
- 該当ページ：[アイキャッチ＞ブログのアイキャッチ＞2. テンプレートを使って自作する＞Figmaでつくる](https://smarthr.design/communication/eye-catching-images/#h4-0)
- Figmaの使い方リンクに関わる文中を編集、該当箇所を削除
- 修正前）Figmaのアカウントの発行方法などはFigmaの利用方法を、 Figmaでアイキャッチを自作する方法は、Figmaアイキャッチテンプレートの使い方 | Google ドライブを参照してください。
- 修正後）Figmaのアカウントの発行方法などはFigmaの利用方法を参照してください。
- 
- Previewでみてね。
|Before|After|
| --- | --- |
| ![CleanShot 2025-01-30 at 13 11 02@2x](https://github.com/user-attachments/assets/67e98277-d98f-434b-85dc-9db2fd271a2e) | ![CleanShot 2025-01-30 at 13 11 30@2x](https://github.com/user-attachments/assets/35ae781a-d4c6-4e2b-b839-6148b1805019) |
> アイキャッチの使い方Figmaのリンクを削除

- src/content/articles/accessibility/link-text.mdx
- アクセシビリティコンテンツのリンクテキストページのテキストリンクの書き方ページへリンクが切れていたため、修正しました
- デザインの調整
- Previewまたはコード上でもどちらかでリンク先があっていることが確認取れたら問題です
https://github.com/user-attachments/assets/1e779102-75bc-4745-b802-7c82cfeb335c
https://github.com/user-attachments/assets/4cfe6a7d-66d4-40fe-b185-93f3c86648d8
> fix: テキストリンクの書き方ページのurl修正

- src/layouts/ArticleLayout.astro
本文エリア下の「前へ」「次へ」リンク（ページネーション）がリストでマークアップされていたため、ナビゲーションにしたい
- 該当要素を`nav`要素でくくった
- 
- 例：https://deploy-preview-1510--smarthr-design-system.netlify.app/products/principles/
見た目の変更はありません。
|Before|After|
| --- | --- |
|  |  |
> 本文エリアのページネーション（次へ・前へ）を`nav`でマークアップ

- src/content/articles/accessibility/check-list/lang.mdx
-　ページの言語のチェックリストページのwcagの関連リンクが「達成基準 1.3.3: 感覚的な特徴を理解する」になっていましたので、リンクを修正しました
- デザイン・レイアウトの変更
- 修正した内容のリンクテキストとリンク先が確認できれば問題ない
- previewでもみれます
|Before|After|
| --- | --- |
https://smarthr.design/accessibility/check-list/lang/#h2-4 | https://deploy-preview-1511--smarthr-design-system.netlify.app/accessibility/check-list/lang/#h2-4
| <img width="531" alt="wcagの関連リンクが「達成基準 1.3.3: 感覚的な特徴を理解する」" src="https://github.com/user-attachments/assets/98fdcd07-c615-442f-8559-9683a06b2e05" /> | <img width="617" alt="wcagの関連リンクが「ページの言語と一部分の言語を理解する」" src="https://github.com/user-attachments/assets/aa5a0356-2ba9-4905-b324-3878eb3542f7" /> |
> fix: ページの言語のチェックリストページのwcagの関連リンクを修正

- src/content/articles/products/contents/ui-text/help-link.mdx
ソリスケの観点から、Airtableからスプシに置き換えたい。
https://smarthr.atlassian.net/browse/SD-1012
- ↓記事にある Airtableの埋込部分を、Markdown形式の表に変更（記載量が軽めなので、スプシ埋め込みするほどではないと判断）
- :design_system:[ヘルプページへの動線 | UIテキスト](https://smarthr.design/products/contents/ui-text/help-link/)
- 注釈と注釈の詳細の位置が遠いので近づける
- 他にあるAirtableの埋込部分は別PRで対応予定
- Previewでみてね。
|Before|After|
| --- | --- |
| ![screenshot](https://github.com/user-attachments/assets/5ce8afc5-431d-4028-8776-c7ffeeb1d0fb) |  ![screenshot 3](https://github.com/user-attachments/assets/882b9b97-6e7f-450e-ba69-e302199cd9e9) |
> Airtableの埋め込み→表記載に変更: ヘルプページへの動線編

- package.json
- pnpm-lock.yaml
ドキュメントの更新は特になし!
Yarn → pnpm になったことにより、内部的に発動していた `postinstall` が動かなくなったため、`upgrade:smarthr-ui` を作りました。
以下のコマンドで upgrade できます。
```bash
$ pnpm run upgrade:smarthr-ui
```
> 👽: smarthr-ui v70.1.0 に更新

- src/components/article/CustomLink/index.module.scss
- src/components/article/CustomLink/index.tsx
maiha さんが代替テキスト入ってなかったことを発見。
-
- 
|Before|After|
| --- | --- |
|  |  |
> ♿️: CustomLink の外部リンクに代替テキストがなかったので TextLink に差し替え

- src/content/articles/accessibility/_components/TableReel.astro
- src/content/articles/communication/sample/text/_components/TableReel/index.module.scss
- src/content/articles/products/usability/_components/TableReel/index.module.scss
https://kufuinc.slack.com/archives/C018J0A6DCH/p1749552171109319
- スタイル修正
- なし
以下で確認
before:
- https://smarthr.design/communication/sample/text/#h3-1
- https://smarthr.design/accessibility/low-vision/#h2-1
- https://smarthr.design/products/usability/usability-checklist/#h2-2
after:
- https://deploy-preview-1660--smarthr-design-system.netlify.app/communication/sample/text/#h3-1
- https://deploy-preview-1660--smarthr-design-system.netlify.app/accessibility/low-vision/#h2-1
- https://deploy-preview-1660--smarthr-design-system.netlify.app/products/usability/usability-checklist/#h2-2
|Before|After|
| --- | --- |
|  |  |
> fix: TableReelのスタイルを上書きしている箇所でのスタイル崩れを修正

- src/content/articles/accessibility/status/index.mdx
情報アクセシビリティ自己評価様式の結果を追加します。
- タイトルを「機能ごとの検証結果」から「検証結果」に変更しました。
- ページはじめの文を変更しました。
-  「 各機能のプロセスごとに、WCAG達成基準に基づく検証や、支援技術で利用可能であるかを検証しています。」を「各機能ごと」に変更し、続けて「情報アクセシビリティ自己評価様式による評価や」の部分をアクセシビリティ検証結果一覧の説明文に移動しました。
-  アクセシビリティ検証結果一覧の説明文を「WCAG達成基準に基づく検証や、支援技術で利用可能であるかを検証しています。」から「WCAG達成基準やアクセシビリティ簡易チェックリストに基づくチェック、支援技術で利用可能であるかを検証しています。」と変更しました。
-  「製品のアクセシビリティ向上を進めています。」を「製品のアクセシビリティ検証を進めています。」に変更しました。
-   情報アクセシビリティ自己評価様式の説明と結果を追加しました。
- 人事評価システムとスキル管理システムの結果ファイルへのリンクを追加しました。
- アクセシビリティ検証結果一覧の見出しレベルを修正しました。
- 見た目の調整
- キャプチャとプレビューの確認をお願いします。
[ Before]
[ After ]
> 情報アクセシビリティ自己評価様式追加

- src/content/articles/communication/sample/text/index.mdx
- サンプルテキストページの「法人番号」に誤字（コピペミス）があったので修正しました
- 法人番号を正しいものに修正
- Previewでみてね
- 最初の数字「2」の有無
|Before|After|
| --- | --- |
| ![CleanShot 2025-07-03 at 16 18 06@2x](https://github.com/user-attachments/assets/5eaa3a1b-fa4b-4f47-9546-9289fa1d7f85) | ![CleanShot 2025-07-03 at 16 18 58@2x](https://github.com/user-attachments/assets/8c9f2d8f-b4ea-4300-9df9-a5df1f8cf13b) |
> サンプルテキストの誤字（コピペミス）の修正

- src/content/articles/accessibility/check-list/label.mdx
- src/content/articles/accessibility/check-list/link-text.mdx
- src/content/articles/accessibility/check-list/markup-list.mdx
ウェブアクセシビリティ簡易チェックリストにおいて、「関連するWCAG2.1達成基準」のリンクを一部修正しました。また、不要な空白行を削除しました。
1. 以下のページの達成基準のリンクを2.0から2.1に変更
- 「入力する内容や、操作がラベルとして表示されている」
- 「リンクのテキストからリンク先が判別できる」
2. 以下のページにおいて、不要な空白行の削除
- 「リストが ul, ol, dlでマークアップされている」
- やったこと以外のすべて
Previewでみてね。
> アクセシビリティ簡易チェックリストのWCAG達成基準を一部修正

- src/content/articles/introduction/user/group.mdx
- SmartHRグループ会社をコーポレートサイトに合わせる
はじめに＞利用者のかたへ＞SmartHR グループ会社従業員＞[対象者](http://localhost:4321/introduction/user/group#h2-0)を以下に変更。
- Smart相談室株式会社
- AIRVISA株式会社
- 株式会社CloudBrains
- なし
- Previewでみてね。
|Before|After|
| --- | --- |
| <img width="2744" height="1602" alt="CleanShot 2025-07-11 at 12 52 22@2x" src="https://github.com/user-attachments/assets/07b56aa7-0e9e-47ba-9e51-39087a882889" /> | <img width="2744" height="1602" alt="CleanShot 2025-07-11 at 12 51 29@2x" src="https://github.com/user-attachments/assets/36741484-2dd6-4cb2-8f84-76d122fea1bd" /> |
> グループ会社情報の更新

- src/content/articles/products/components/text-link/help-link/index.mdx
- src/content/articles/products/components/text-link/index.mdx
- src/content/articles/products/contents/ui-text/help-link.mdx
:docbase:[プロダクトからヘルプページへの流入を取る方法](https://smarthr-inc.docbase.io/posts/3224598)では、ヘルプページへのリンクは「HelpLink」の使用が推奨されている。
しかし[TextLink | コンポーネント | SmartHR Design System](https://smarthr.design/products/components/text-link/#h4-2) の「ヘルプセンターを開くテキストリンク」の説明が古く、矛盾しているので、修正する。
チケット：https://smarthr.atlassian.net/browse/SD-1129
- TextLinkの説明にHelpLinkコンポーネントの使用を反映
- https://smarthr.design/products/components/text-link/#h4-2
- 「ヘルプページへの動線」の説明が誤っていたため修正
- https://smarthr.design/products/contents/ui-text/help-link/#h3-2
- 新規ウィンドウでリンクを開く場合もヘルプアイコン（FaQuestionCircleIcon）が必須という説明になっていた。新規ウィンドウで開くことを示すアイコン（FaExternalLinkAltIcon） の表示を優先することが正しいため、修正した
- 関連スレ：https://kufuinc.slack.com/archives/CJX59GJFR/p1756085175588049
- Previewでみてね。
> TextLinkコンポーネントの説明を最新化 SD-1129 

- src/components/article/ComponentPropsTable.astro
- src/content/articles/products/components/dialog/action-dialog/index.mdx
- src/content/articles/products/components/dialog/index.mdx
- src/content/articles/products/components/heading/index.mdx
- src/content/articles/products/components/table/index.mdx
- src/content/articles/products/design-patterns/visual-guidance/index.mdx
- 書かれていなかったコンポーネントをいくつか追加
- PageHeading、FormDialog、WakuWakuButton
- ComponentPropsTableでpropsがないコンポーネントでも`showTitle`があればタイトルを表示できるようにした
- WIPだったリンクを適切なものに置き換え
- 
- Previewでみてね。
- https://deploy-preview-1734--smarthr-design-system.netlify.app/products/components/dialog/#h3-0
- https://deploy-preview-1734--smarthr-design-system.netlify.app/products/components/dialog/action-dialog/#props-FormDialog
- https://deploy-preview-1734--smarthr-design-system.netlify.app/products/components/heading/#h3-0
- https://deploy-preview-1734--smarthr-design-system.netlify.app/products/components/table/#props-WakuWakuButton
- https://deploy-preview-1734--smarthr-design-system.netlify.app/products/design-patterns/visual-guidance/#h3-4
|Before|After|
| --- | --- |
|  |  |
> コンポーネントを追加（PageHeading、FormDialog、WakuWakuButton）
