src/components/shared/Header/Header.tsx

- 幅固定レイアウトにより意図しない折返しが発生していた
- 今後アクセシビリティカテゴリが追加になる可能性がある
- 入り切らない場合に最大3段になるように調整
- ほか、合わせて細かい調整を入れた（コメント入れます
Preview でざっと見てちょ。

🚸: ヘッダーの一部を EveryLayout 化

---

yarn.lock

https://github.com/kufu/smarthr-design-system-issues/issues/943
- [sharp](https://www.npmjs.com/package/sharp)のバージョンを最新のv0.30.6に変更
（ローカルでは再現しないエラーのため、PRプレビューでビルドがうまくいくかどうか確認します。）

netlifyでsharpライブラリのエラーが出る問題に対応

---

package.json

https://github.com/kufu/smarthr-design-system-issues/issues/950
- Netlify の管理画面から [Gatsby Cache](https://github.com/jlengstorf/netlify-plugin-gatsby-cache#readme) を有効化
- build コマンドに変数を追加し、インクリメンタルビルドを有効化
- gatsby v3 以降であればデフォルト有効の記述を見かけたが、効いてなさそう? だったので念の為追記
- https://www.gatsbyjs.com/docs/reference/release-notes/v3.0/#incremental-builds-in-oss
|Before|After|
| --- | --- |
|  |  |

⚡️: Gatsby インクリメンタルビルドを有効化

---

src/components/index/Gotcha.tsx

https://github.com/kufu/smarthr-design-system-issues/issues/1078
トップページ>Gotchaの表示内容はランダムに選択するため、SSR/CSRで異なる内容になる可能性があり、そのためハイドレーション関係のエラーがコンソールに表示されていました。そこで、
- SSR時はindex=-1に固定するようにしました（画像・説明文は表示しません）
- CSR時のみ発火する`useEffect`内で、最初のランダムアイテムを選択するようにしました
https://deploy-preview-328--smarthr-design-system.netlify.app/
トップページ表示時の見た目や動作は変わっていません。
該当のコンソールエラーは出なくなりました

コンソールエラー回避のため、SSR時のGotchaの表示を調整

---

content/articles/operational-guideline/release.mdx

リポジトリへのリンクを追加。あわせてDocBaseへのリンクも追加し、Issueのリンクを修正した。
細かいリリース手順を書くこと
|Before|After|
| --- | --- |
| <img width="657" alt="image" src="https://user-images.githubusercontent.com/7392923/200465445-4d677bf8-b516-403f-9dc9-2fa28fd074f4.png"> | <img width="674" alt="image" src="https://user-images.githubusercontent.com/7392923/200465396-648db899-cf11-4fcb-9fd9-411e8d5d86dd.png"> |

リポジトリへのリンクを追加

---

content/articles/products/design-process/design-data/figma-library-update.mdx

- 記事内のデザインデータの作り方へのリンクが誤っていたので修正
|Before|After|
| --- | --- |
|  |  |

デザインデータの作り方へのリンクを修正

---

src/components/ColorPalette/ColorPalette.tsx
tsconfig.json

refs https://github.com/kufu/smarthr-design-system-issues/issues/1135
tsc --noEmitによるエラーの解消
対応前はエラーが大量に出力していたが、対応後は何も出力されなくなりました。
|Before|After|
| --- | --- |
| <img width="710" alt="image" src="https://user-images.githubusercontent.com/1369376/205838747-f41d9145-3700-431d-b1e4-09909e00be43.png"> | <img width="432" alt="image" src="https://user-images.githubusercontent.com/1369376/205838788-b1e50382-4de5-429f-8fee-4a3228300fcb.png"> |

tsc --noEmitチェックのエラーを解消

---

.github/workflows/deploy-to-netlify.yml

closes https://github.com/kufu/smarthr-design-system-issues/issues/1184
GitHub Actionsからの実行の場合、環境変数が不足していたそうなので、その指定追加
|Before|After|
| --- | --- |
|  |  |

GitHub ActionsによるNetlifyのデプロイに環境変数が不足していたので追加

---

content/articles/products/components/status-label.mdx

📝: StatusLabel にプレビューを追加

---

content/articles/accessibility/alternative-text.mdx
content/articles/accessibility/check-list.mdx

問い合わせ先にSlackチャンネルを指定していたが、社内だと明記していなかった。(社外の人から問い合わせがあった。)
問い合わせ先にSlackチャンネルを指定していた2ページに対して、チャンネル名の前にテキスト「社内Slack」を追加した
- Previewでみてね。
- コードだけでも大丈夫

問い合わせ先Slackチャンネルについて「社内Slack」を明記した

---

content/articles/products/contents/mail.mdx

通知メールのガイドラインを参照していて気づきました。
`お問い合わせください`の方が聞き慣れていて、よく使われていると判断して変更しました。
- `お問い合わせてください`→`お問い合わせください`に変更
|Before|After|
| --- | --- |
|  |  |

通知メールのガイドラインの表現を変更

---

content/articles/products/contents/error-messages.mdx

- Airtableにバックグラウンド処理のエラーメッセージのライティングパターンを追加
- エラーメッセージのページにAirtableを埋め込み
|Before|After|
| --- | --- |
|  |  |

バックグラウンド処理のエラーメッセージのライティングパターンを追加します

---

src/components/login/Login.tsx

利用者が社内外に増えてきて多様化してきてるので、パスワードの入力方法の説明をアップデートしたい。
- 主にパスワードの入力方法のリライト
|Before|After|
| --- | --- |
|  |  |

ログイン画面の説明を修正

---

scripts/component-thumbnails/README.md
scripts/component-thumbnails/componentThumbnails.ts

サムネイル生成のためのコマンド実行時にいくつか注意点があったが、それがどこにも書かれていなかった
ソースコード内にコメントとREADME.mdを追加した
見た目上の変化なし

コンポーネントのサムネイル生成に関するドキュメントを追加

---

content/articles/communication/capture/service-capture-in-mock.mdx

先日リリースした画面キャプチャのURLが最新になっていませんでした。
ので、最新のURLに差し替えました。
- リンクのURLを変更
- とくになし
なし

リンクのURLを変更

---

content/articles/introduction/user/smarthr_app_partner.mdx

アプリ以外における禁止事項が、全体の禁止事項だと誤解されるケースがあるので、わかりやすくリライト
-
|Before|After|
| --- | --- |
|  |  |

アプリ（プロダクト）以外、ということをわかりやすくリライト

---

content/articles/accessibility/policy.mdx
content/articles/accessibility/test/202112/index.mdx
content/articles/accessibility/test/202306/index.mdx

レベルA準拠に向けて!!!!
- 試験
- smarthr-ui の修正
- 試験結果ページの作成
https://deploy-preview-745--smarthr-design-system.netlify.app/accessibility/test/202306/
|Before|After|
| --- | --- |
|  |  |

SmartHR UI アクセシビリティ試験結果｜202306

---

content/articles/accessibility/test/202306/index.mdx

✏️: レベルA準拠の間違い

---

content/articles/accessibility/policy.mdx

SmartHR UI が目標とする適合ベルを AA に上げました。
結果を更新し、目標達成スケジュールを追加しました。
https://deploy-preview-752--smarthr-design-system.netlify.app/accessibility/policy/

📈: ウェブアクセシビリティ試験の達成結果と目標を更新

---

content/articles/products/components/calendar.mdx

https://github.com/kufu/smarthr-design-system-issues/issues/1282
- カレンダーの説明を追加した
- 説明は、青本P.128より抜粋👇
```
カレンダーを表示し日付を選択するためのコンポーネントです。基本的にはDatePickerと合わせて使用されるため、単独で使用することはありません。
```
- キャプチャで見てね
-->
|Before|After|
| --- | --- |
| <img width="583" alt="image" src="https://github.com/kufu/smarthr-design-system/assets/65280580/f8d165cb-1719-40dc-a1ac-cca5968832d2"> | <img width="564" alt="image" src="https://github.com/kufu/smarthr-design-system/assets/65280580/c8cd7136-e07c-4537-a1a2-ccba02e8893e"> |

calendarのコンポーネントページに説明文を追加する

---

content/articles/products/components/switch.mdx

https://deploy-preview-899--smarthr-design-system.netlify.app/products/components/switch/#h3-2

📝: Switch のラベル例として「アーカイブを表示」を追加

---

package.json
scripts/update-smarthr-ui-css.ts
src/@types/cdn-typescript/index.d.ts
src/components/ComponentStory/ResizableContainer.tsx
src/components/article/CodeBlock/CodeBlock.tsx
src/components/article/CodeBlock/LiveContainer.tsx
src/components/index/Introduction/Introduction.tsx
src/components/shared/Header/Header.tsx
src/pages/index.tsx
static/smarthr-ui.css
yarn.lock

説明が必要なところはコメントを入れます。
Close #983

⬆️ smarthr-ui を v38.2.0 に更新

---

package.json
yarn.lock

-
|Before|After|
| --- | --- |
|  |  |

smarthr-uiを39.0.0にアップデート

---

package.json
static/smarthr-ui.css
yarn.lock

- smarthr-uiをv39.1.0へ更新
|Before|After|
| --- | --- |
|  |  |

smarthr-uiをv39.1.0へ更新

---

package.json
yarn.lock

SmartHR UI を v40.0.2に更新
|Before|After|
| --- | --- |
|  |  |

SmartHR UI を v40.0.2に更新

---

static/smarthr-ui.css

-
|Before|After|
| --- | --- |
|  |  |

fix: smarthr-ui.css の更新を反映

---

content/articles/products/components/chip.mdx
package.json
static/smarthr-ui.css
yarn.lock

- SmartHR UIをv40.1.0に更新
- Chipコンポーネントを新たに追加
|Before|After|
| --- | --- |
|  |  |

SmartHR UIをv40.1.0に更新

---

src/constants/application.ts

-
|Before|After|
| --- | --- |
|  |  |

fix: private-fetch が動作していなそうなので URI を直で書き換え

---

package.json
static/smarthr-ui.css
yarn.lock

-
|Before|After|
| --- | --- |
|  |  |

⬆️: smarthr-ui を v40.1.3 に更新

---

package.json
static/smarthr-ui.css
yarn.lock

-
|Before|After|
| --- | --- |
|  |  |

SmartHR UI v41.0.0 update

---

package.json
static/smarthr-ui.css
yarn.lock

-
|Before|After|
| --- | --- |
|  |  |

update smarthr-ui to v41.1.0

---

package.json
static/smarthr-ui.css
yarn.lock

-
|Before|After|
| --- | --- |
|  |  |

update smarthr ui to 41.1.2

---

package.json
static/smarthr-ui.css
yarn.lock

-
|Before|After|
| --- | --- |
|  |  |

SmartHR UIをv41.2.0に更新

---

package.json
static/smarthr-ui.css
yarn.lock

-
|Before|After|
| --- | --- |
|  |  |

⬆️: smarthr-ui を v41.3.0 に更新

---

content/articles/communication/capture/kit.mdx

App storeからSkitchがインストールできないので、Skitchに関する情報を削除しました。
issue: https://app.asana.com/0/1202550875681278/1206460977097717/f
- デザインシステムサイト上からSkitchに関する情報を削除
- とくになし
|Before|After|
| --- | --- |
| ![image](https://github.com/kufu/smarthr-design-system/assets/101125529/b42e85f0-467c-4de7-82da-0e25abcfbd37) |  |

Skitchに関する情報を削除

---

content/articles/products/components/icon.mdx
package.json
static/smarthr-ui.css
yarn.lock

- smarthr-uiをv43.3.0に更新
- Iconコンポーネントページで例示している旧名称アイコンを新名称アイコンに置き換え
|Before|After|
| --- | --- |
|  |  |

smarthr-uiをv43.3.0に更新

---

content/articles/products/components/icon.mdx
package.json
static/smarthr-ui.css
yarn.lock

This reverts commit bf46c2931f8c281a3c04a15477d3c975ef1fb37f, reversing changes made to 148d9b7361f07c5caa13f4a430146d5a07d531ed.
-
|Before|After|
| --- | --- |
|  |  |

Revert "smarthr-uiをv43.3.0に更新"

---

content/articles/products/components/icon.mdx
package.json
src/templates/article.tsx
static/smarthr-ui.css
yarn.lock

Reverts kufu/smarthr-design-system#1096

Revert "Revert "smarthr-uiをv43.3.0に更新""

---

package.json
yarn.lock

-
|Before|After|
| --- | --- |
|  |  |

🔧: yarn install がコケるので resolutions を追加

---

content/articles/products/components/app-navi.mdx
content/articles/products/components/base/index.mdx
content/articles/products/components/bottom-fixed-area.mdx
content/articles/products/components/check-box.mdx
content/articles/products/components/combo-box.mdx
content/articles/products/components/date-picker.mdx
content/articles/products/components/definition-list.mdx
content/articles/products/components/drop-zone.mdx
content/articles/products/components/dropdown/dropdown-menu-button.mdx
content/articles/products/components/dropdown/filter-dropdown.mdx
content/articles/products/components/dropdown/index.mdx
content/articles/products/components/float-area.mdx
content/articles/products/components/header.mdx
content/articles/products/components/information-panel.mdx
content/articles/products/components/input-file.mdx
content/articles/products/components/input/index.mdx
content/articles/products/components/input/search-input.mdx
content/articles/products/components/layout/index.mdx
content/articles/products/components/line-clamp.mdx
content/articles/products/components/loader.mdx
content/articles/products/components/pagination.mdx
content/articles/products/components/radio-button.mdx
content/articles/products/components/select.mdx
content/articles/products/components/status-label.mdx
content/articles/products/components/tab-bar.mdx
content/articles/products/components/table.mdx
content/articles/products/components/text-link.mdx
content/articles/products/components/text.mdx
content/articles/products/components/textarea.mdx

-
|Before|After|
| --- | --- |
|  |  |

📝: 書籍「ちいさくはじめるデザインシステム」からコンポーネントの概要を転記

---

package.json
plugins/gatsby-source-component-captures/fetchComponentCaptures.ts
plugins/gatsby-source-ui-versions/fetchUiVersions.ts
src/components/article/Sidebar/Sidebar.tsx
src/templates/article.tsx
yarn.lock

- smarthr-ui の Storybook が v8 になったことにより、`/stories.json` が消えたため、Migration guide に則り `/index.json` から変換する処理を入れました
- https://github.com/storybookjs/storybook/blob/c67bf6785fdc67510721444aea6cacf3e3a5c228/MIGRATION.md#removed-storiesjson
- またコード外ですが、Netlify の環境変数 `SHR_UI_MAXVERSIONS` を指定しました（すべてを読み込むの無理だった説
-
|Before|After|
| --- | --- |
|  |  |

👽: smarthr-ui の Storybook v8 対応に追従。

---

.github/workflows/netlify-clear-cache-deploy.yml

ref https://smarthr.atlassian.net/browse/SD-734
デザインシステムサイトのログイン機能が動かない（ログインに失敗する）ことが頻発している。
再デプロイでログイン機能が動くようになるが、根本解決がされていない。
- 根本解決するまで暫定的に`Deploy to netlify`のGitHub Actionが定期的に実行されるように変更
|Before|After|
| --- | --- |
|  |  |

ログイン機能が不安定な状態を暫定的に回避する

---

content/articles/products/components/app-navi.mdx
content/articles/products/components/header.mdx
content/articles/products/components/input-file.mdx
content/articles/products/components/layout/center.mdx
content/articles/products/components/layout/cluster.mdx
content/articles/products/components/layout/reel.mdx
content/articles/products/components/layout/sidebar.mdx
content/articles/products/components/layout/stack.mdx
content/articles/products/components/pagination.mdx
content/articles/products/components/smarthr-logo.mdx
content/articles/products/components/visually-hidden-text.mdx
content/articles/products/design-patterns/smarthr-table.mdx

- 基準を充足するぞい
- 概要文を追加
- Layout系コンポーネント
- SmartHRLogo
- VisuallyHiddenText
- 概要文を修正
- Paginationの利用箇所として「よくあるテーブル」を明記
- AppNavi、Headerから[デザインパターンのヘッダー](/products/design-patterns/contents-in-header/)を参照するように
- その他
- InputFileの概要文を微修正
- よくあるテーブルのタイトルから括弧を削除
- ページの中身のアップデートが必要なものは別PRにします。
- DropdownMenuButton
- InputFile
- DropZone
- Text
- Previewでみてね。
- https://deploy-preview-1130--smarthr-design-system.netlify.app/products/components/
- 「充足するか」の観点でレビューをお願いします。
- Layout系コンポーネント
|Before|After|
| --- | --- |
|  |  |

Almostなコンポーネントの基準の充足（その1）

---

.github/CODEOWNERS

-
- 
|Before|After|
| --- | --- |
|  |  |

🔧: CODEOWNERS を追加

---

content/articles/products/usability/usability-checklist.mdx

- 重複している「を」削除
https://deploy-preview-1089--smarthr-design-system.netlify.app/products/usability/usability-checklist/

重複している「を」削除

---

package.json
static/smarthr-ui.css
yarn.lock

SmartHR UI をアップデート
- SmartHR UI をv46.01->v47.1.0にした
- [更新スレ](https://kufuinc.slack.com/archives/C018J0A6DCH/p1713499499936259)
-　なし
|Before|After|
| --- | --- |
|  |  |

SmartHR UI アップデート　

---

content/articles/products/components/page-counter.mdx

discriptionを追加
discriptionが空だったので追加
https://smarthr.atlassian.net/browse/SD-649
- 課題と同じ
- とくになし
- Previewでみてね。
- https://deploy-preview-1149--smarthr-design-system.netlify.app/products/components/page-counter/
|Before|After|
| --- | --- |
|  |  |

Add discription page-counter.mdx

---

content/articles/products/components/check-box/index.mdx

- 読み合わせ会のレビュー内容を反映
- 概要説明文をふさわしい書き方に調整
- キャプチャのタイトルが「スクリーンショット」になっていたのをふさわしい説明に修正
- 
https://deploy-preview-1159--smarthr-design-system.netlify.app/products/components/check-box/

Checkboxの概要説明とキャプチャのタイトルを修正

---

content/articles/products/components/notification-bar.mdx
package.json
plugins/gatsby-source-ui-versions/fetchUiVersions.ts
static/smarthr-ui.css
yarn.lock

-
- 
|Before|After|
| --- | --- |
|  |  |

🆙 smarthr-ui を v50.0.0 に更新

---

src/components/article/PageIndex/PageIndex.tsx

- PageIndexがリンクとして認識しづらい
- indexにソートが効いておらず表示順がデタラメになっている
- リンクのスタイルをBoxLinkを参考にしたものに変更してみた
- titleでソートされるように修正
- 
- https://deploy-preview-1160--smarthr-design-system.netlify.app/products/components/layout/

PageIndexの修正

---

package.json
static/smarthr-ui.css
yarn.lock

- smarthr-uiを50.1.0にアップデート
- 
|Before|After|
| --- | --- |
|  |  |

🆙 smarthr-ui を v50.1.0 に更新

---

package.json
static/smarthr-ui.css
yarn.lock

- SmartHR UI をv51.1.0 にupdate
- ヘッダーページの画像がローカルだとパスが違うので表示されないけど、と本番では表示される
- https://deploy-preview-1178--smarthr-design-system.netlify.app/products/design-patterns/contents-in-header/
- 
|Before|After|
| --- | --- |
|  |  |

SmartHR UI v51.1.0 にupdate

---

content/articles/products/components/button.mdx

https://smarthr.atlassian.net/browse/SD-642
- Buttonコンポーネントのガイドラインを更新しました。
- 全体的に説明が不明瞭な部分を修正しました。
- 「アイコン付きボタン」に、「prefixアイコンをつける判断基準」のセクションを追加しました。
- 「アクションに紐づくアイコン」はIconコンポーネントのページに別途追加する予定です。
https://deploy-preview-1169--smarthr-design-system.netlify.app/products/components/button

Buttonコンポーネントのガイドラインを更新

---

.github/workflows/netlify-clear-cache-deploy.yml

不安定なログインに対処するために実行していた定期的 rebuild を消しました。
https://github.com/kufu/smarthr-design-system/pull/1110/files の逆です。
-
- 
|Before|After|
| --- | --- |
|  |  |

👷: ログインが不安定なために定期実行していた rebuild を消す

---

package.json
static/smarthr-ui.css
yarn.lock

バージョンを上げました。特別な対応はしていません。
- 
|Before|After|
| --- | --- |
|  |  |

SmartHR UI更新 v51.1.1 → v51.2.0

---

package.json
static/smarthr-ui.css
yarn.lock

SmartHRのUIのバージョンを更新しました。
内部的な変更のみなので、コンテンツ更新はありません。
内部的な変更のみなので、コンテンツ更新はありません。

SmartHR UI更新 v51.2.0 → v52.0.1

---

content/articles/products/usability/usability-checklist.mdx

以下の基準が揃ったため「基準あり」に変更します。
- ページレイアウト
- デフォルト値
- 
|Before|After|
| --- | --- |
|  |  |

UIデザイン使用性チェックリストを最新に更新

---

content/articles/products/usability/usability-checklist.mdx

https://github.com/kufu/smarthr-design-system/pull/1236 の続き
- モバイルレイアウトを「基準あり」に変更
- 
|Before|After|
| --- | --- |
|  |  |

UIデザイン使用性チェックリストを最新に更新 その2

---

package.json
yarn.lock

⬆️: smarthr-ui を v52.1.0 に更新

---

content/articles/products/components/segmented-control.mdx

`submit` は関係なく読めたので、提案してみました。
https://deploy-preview-1224--smarthr-design-system.netlify.app/products/components/segmented-control/#h3-2

💬: SegmentedControl の記述から submit の概念を消す提案

---

content/articles/products/components/icon.mdx
package.json
static/smarthr-ui.css
yarn.lock

- smarthr-uiをv53.0.0へ更新
- 存在しないFaAnglesDownIconをimportしてerror出てたのでついでに直しました:pray:
- 
|Before|After|
| --- | --- |
|  |  |

smarthr-uiをv53.0.0へ更新

---

package.json
yarn.lock

コンテンツ更新なし
バージョン上げただけです
- 
|Before|After|
| --- | --- |
|  |  |

SmartHR UI更新追従 v53.0.0 → v53.1.0

---

content/articles/products/components/tab-bar.mdx
package.json
static/smarthr-ui.css
yarn.lock

TabBar のコード部分を触っています
https://deploy-preview-1249--smarthr-design-system.netlify.app/products/components/tab-bar/#h3-3

⬆️ smarthr-ui を v54.1.0 に更新

---

content/articles/basics/icons/creation-guideline.mdx

- アイコン作成ページにtypoを発見したので、修正しました。
- アイコン作成ページのtypoを修正。
- とくになし
https://deploy-preview-1252--smarthr-design-system.netlify.app/basics/icons/creation-guideline/
|Before|After|
| --- | --- |
| ![CleanShot 2024-08-07 at 16 27 58](https://github.com/user-attachments/assets/ee66d0b5-21bf-4013-833b-45a1747fa84b) | ![CleanShot 2024-08-07 at 16 33 02](https://github.com/user-attachments/assets/0b69d49a-bad8-40e5-a3fa-faee3a19ee96) |

アイコン作成ページのtypoを修正

---

content/articles/products/components/stepper.mdx
content/articles/products/components/time-picker .mdx
package.json
static/smarthr-ui.css
yarn.lock

- SmartHR UIのバージョンアップ
- [Stepper](https://deploy-preview-1253--smarthr-design-system.netlify.app/products/components/stepper/) 、[TimePicker](https://deploy-preview-1253--smarthr-design-system.netlify.app/products/components/time-picker%20/)のページのみを追加。中身はwip
- 
|Before|After|
| --- | --- |
|  |  |

smarthr-ui の更新v54.1.0→v55.0.0

---

plugins/gatsby-source-ui-versions/fetchUiVersions.ts

リリースコミットを正しく判定できるように修正
- chore(release): vN.N.N 形式のリリースコミットを判定できるように正規表現を調整
- smarthr-ui側がvがつくものとつかないものが混在するため (なぜ…？)
- 
|Before|After|
| --- | --- |
|  |  |

fix: リリースコミットの判定ロジックを修正

---

.gitignore
package.json
pnpm-lock.yaml
scripts/fetch-shr-ui-data.ts
scripts/fetch-ui-data.ts
src/components/ComponentPreview/ProductWrapper.tsx
src/components/ComponentPreview/index.ts
src/components/ComponentPreview/index.tsx
src/components/ComponentStory/ComponentStory.module.css
src/components/ComponentStory/ComponentStory.tsx
src/components/ComponentStory/README.md
src/components/ComponentStory/index.astro
src/components/ResizableContainer/index.tsx
src/components/article/CodeBlock/LiveContainer.tsx
src/layouts/Layout.astro
src/lib/fetchStoryCode.ts
src/lib/getUIData.ts
src/styles/global.css
src/types/ui.ts

ComponentStoryを移植

---

.prettierignore
.prettierrc.cjs
astro.config.mjs
scripts/component-thumbnails/componentThumbnails.ts
scripts/content-checker/linkChecker.ts
scripts/content-checker/storybookUrlChecker.ts
scripts/fetch-ui-data.ts
scripts/update-smarthr-ui-css.ts
scripts/zipImages.ts
src/components/ComponentPreview/ProductWrapper.tsx
src/components/ComponentStory/ComponentStory.tsx
src/components/article/Article.module.css
src/components/article/CodeBlock/CodeBlock.tsx
src/components/article/CodeBlock/CopyButton.tsx
src/components/article/CodeBlock/DesignPatternCodeBlock.tsx
src/components/article/CodeBlock/LiveContainer.module.css
src/components/article/CustomLink/index.tsx
src/components/article/FragmentTitle/index.tsx
src/content/articles/products/components/time-picker.mdx
src/lib/getUIData.ts
tsconfig.json

- Astro移行
- Prettierの対象ファイルをまとめてフォーマット

対象ファイルをまとめてフォーマット

---

astro.config.mjs
package.json
pnpm-lock.yaml

remark-emojiを追加

---

src/components/article/Article.module.css
src/components/article/ResponsiveImage.astro
src/pages/[...slug].astro

- Astro移行
- MDX内の画像の最適化&レスポンシブ対応

画像の最適化とレスポンシブ対応

---

src/env.d.ts
src/lib/fetchSdsAirtable.ts

Astro への移行
- gatsby-source-sds-airtable 相当の関数を追加

gatsby-source-sds-airtable を移行

---

package.json
static/smarthr-ui.css
yarn.lock

-　更新作業のみ
- 
https://deploy-preview-1288--smarthr-design-system.netlify.app/
|Before|After|
| --- | --- |
|  |  |

SDS更新58.0.3→58.1.0

---

package.json
pnpm-lock.yaml
src/components/IndexNav/IndexNavItems.module.scss
src/components/IndexNav/IndexNavItems.tsx
src/components/IndexNav/index.module.scss
src/components/IndexNav/index.tsx
src/components/article/ComponentCaptures.astro
src/content/config.ts
src/layouts/ArticleLayout.astro
src/lib/getHeadings.ts
src/lib/throttle.ts
src/pages/[...slug].astro
src/styles/mixin.scss

- Astro移行
- IndexNav (ページ右の目次) を移植

IndexNavを移植

---

src/components/article/ColorPalette.astro
src/components/article/ColorPaletteWrapper.astro
src/content/articles/products/design-tokens/color.mdx

ColorPaletteを移植

---

src/components/article/DoAndDont.astro

- Astro移行
- DoAndDontコンポーネントを移植

DoAndDontを移植

---

src/components/RoundedBoxLink.astro
src/layouts/ArticleLayout.astro
src/pages/[...slug].astro

RoundedBoxLinkを移植

---

src/components/Footer.astro
src/components/IndexNav/IndexNavItems.module.scss
src/components/IndexNav/index.module.scss
src/components/Sidebar/Sidebar.astro
src/components/Sidebar/SidebarItems.astro
src/components/article/ColorPalette.astro
src/components/article/DoAndDont.astro
src/layouts/ArticleLayout.astro
src/styles/mixin.scss

- Astro移行
- mixinの名前を元々使われていた定義名に準拠するように変更しました

mixinの名前を変更

---

.prettierignore
src/components/CodeBlock/ComponentPreview.tsx
src/components/CodeBlock/LiveContainer.tsx
src/components/article/CaptureImageWithDesc.astro
src/components/article/CustomTable.astro
src/components/article/TableWrapper.astro
src/content/articles/communication/capture/capture-others.mdx
src/content/articles/communication/capture/capture-product.mdx
src/content/articles/operational-guideline/page-template/style-template.mdx
src/content/articles/products/components/heading.mdx
src/content/articles/products/design-tokens/typography/index.mdx
src/layouts/ArticleLayout.astro
src/pages/[...slug].astro
tsconfig.json

- Astro移行
- TableWrapperを移植
- CaptureImageWithDescを移植

TableWrapper、CaptureImageWithDescを移植

---

.github/workflows/deploy-to-netlify.yml
.github/workflows/netlify-clear-cache-deploy.yml
netlify.toml

- Astro移行
- デプロイ関係のワークフローを追加
- netlify.tomlを追加

デプロイ関係の設定・ワークフローを追加

---

content/articles/products/components/button.mdx
content/articles/products/components/heading.mdx
content/articles/products/components/tooltip.mdx
content/articles/products/contents/idiomatic-usage/usage.mdx
content/articles/products/contents/ui-text/app-writing.mdx
static/_redirects

https://smarthr.atlassian.net/browse/SD-864
- リンクの表記が誤っている箇所を修正しました
今 products/contents/ui-text/app-writing/#h2-12
↓↓↓
正 /products/contents/ui-text/app-writing/#h2-12 
- リンクが切れているそうなのでリダイレクト設定を追加しました。
　- [発覚した経緯](https://x.com/atohsaaa/status/1844667137866252632)
- 
|Before|After|
| --- | --- |
|  |  |

構成を変更した際にリンク切れしてしまった箇所を修正しました

---

scripts/component-thumbnails/componentThumbnails.ts
scripts/content-checker/linkChecker.ts
scripts/content-checker/storybookUrlChecker.ts
scripts/fetch-ui-data.ts
scripts/zipImages.ts

lintのエラーを修正

---

package.json
static/smarthr-ui.css
yarn.lock

- SmartHR UI をv58.1.2にアップデート
- 
|Before|After|
| --- | --- |
|  |  |

SmartHR UI をv58.1.2にアップデート

---

package.json
pnpm-lock.yaml
public/smarthr-ui.css
scripts/update-smarthr-ui-css.ts

- Astro化
- 表示確認のため、最新の SmartHR UI に更新

(Astro) SmartHR UI を v58.1.2 に更新

---

src/lib/fetchComponentCaptures.ts

- Astro化
- コンポーネント一覧に表示されていないものがある
- 全てのコンポーネントが一覧の載るようロジックを修正
↑ Before / ↓ After

fix: コンポーネント一覧に表示されていないものがある

---

src/components/Sidebar/CaretButton.tsx
src/components/Sidebar/RecursiveSidebarItem.astro

- Astro化
- サイドバーで開いているページではない項目が展開される場合がある問題を修正
- パスの部分一致で判定していた部分をより厳密な判定に修正

fix: サイドバーの挙動を修正

---

.github/workflows/link-check.yml
.github/workflows/lint.yml
.github/workflows/storybook-check.yml

- Astro化
- ワークフローが正しく動作するように修正しました
- ローカル環境 ([act](https://github.com/nektos/act)) で検証しました

fix(workflow): 実行できるように修正

---

src/components/search/Search/SearchResultOuter.tsx

- Astro化
- https://github.com/kufu/smarthr-design-system/pull/1308#discussion_r1802252981
- 検索結果部分に `aria-live="polite"` を指定しました

検索結果にaria-live属性を追加

---

package.json
static/smarthr-ui.css
yarn.lock

smarthr-uiの更新
コンテンツの更新は特にしていません
Previewでみてね
https://deploy-preview-1340--smarthr-design-system.netlify.app/
|Before|After|
| --- | --- |
|  |  |

SmartHR UIをv59.0.0へ更新

---

src/content/articles/operational-guideline/page-template/component-template.mdx
src/content/articles/operational-guideline/page-template/style-template.mdx

- Astro化
以下の内容を追記しました。
- コンポーネントテンプレート
- プレビューを埋め込む際の注意点
- スタイルテンプレート
- 太字とエスケープが必要な文字について
- リンクについて
コメントの変更については、ページのスタイルに関係するものではないのでは？と思ったので追記していません。

テンプレートに変更になった書式について追記

---

content/articles/products/contents/idiomatic-usage/ichiran.mdx
content/articles/products/contents/idiomatic-usage/usage.mdx

https://smarthr.atlassian.net/browse/SD-806
- SmartHR用語にAppNaviを「［｛機能名｝］メニュー」と表記する用字用語を追加
- 索引にも「［｛機能名｝］メニュー」を追加
- 
ファイルでの確認で十分だよ。
|Before|After|
| --- | --- |
|  |  |

AppNaviを「［｛機能名｝］メニュー」と表記する用字用語を追加

---

src/components/IndexNav/IndexNavItems.tsx
src/components/IndexNav/index.tsx
src/components/Sidebar/CaretButton.tsx
src/components/Sidebar/RecursiveSidebarItem.astro
src/components/Sidebar/Sidebar.astro
src/components/Sidebar/SidebarItems.astro
src/components/search/IndexList.astro
src/layouts/ArticleLayout.astro
src/lib/createArticleMetaItems.ts
src/pages/[...slug].astro
src/types/article.ts

- Astro化
- 実態に則していない名前になってる箇所をリネーム
- 重複する型定義をシンプルに

変数名・Propsのオプション名を変更

---

content/articles/products/components/date-picker.mdx
content/articles/products/components/month-picker.mdx
content/articles/products/components/time-picker.mdx
package.json
static/smarthr-ui.css
yarn.lock

- DatePicker の説明を見直し
- TimePicker のパスを修正
- TimePicker に説明を追加
- MonthPicker を追加

🆙 smarthr-ui v60.0.0 に追従

---

package.json
pnpm-lock.yaml

⬆️: smarthr-ui を v60.0.1 に更新

---

.github/workflows/deploy-to-netlify.yml
.github/workflows/link-check.yml
.github/workflows/lint.yml
.github/workflows/storybook-check.yml
package.json

- `corepack use pnpm@9` を実行しました

chore: packageManagerのフィールドを追加

---

package.json
pnpm-lock.yaml
src/components/ComponentStory/index.tsx
src/components/FootStaticLinks.astro
src/components/Header/Header.astro
src/components/article/CustomLink/index.tsx
src/components/index/Gotcha/index.tsx
src/components/search/Search/SearchBox.tsx
src/content/articles/products/components/bottom-fixed-area.mdx
src/content/articles/products/design-patterns/delete-dialog/_components/DynamicActionDialog.tsx

https://smarthr.atlassian.net/browse/SD-885
-
- 
|Before|After|
| --- | --- |
|  |  |

🆙 smarthr-ui を v60.1.1 に更新

---

.husky/pre-commit

-
- 
|Before|After|
| --- | --- |
|  |  |

💚: pre-commit 時に linkChecker に必要な依存をインストール

---

README.md

READMEのサンプルコードが崩れていたので修正
- READMEのサンプルコードが崩れていたので修正しました
- 
|Before|After|
| --- | --- |
|  |  |

fix(README): サンプルコードを修正

---

package.json
pnpm-lock.yaml
public/smarthr-ui.css

SmartHR UI をv61.0.0 にupdate
-
- 
https://deploy-preview-1402--smarthr-design-system.netlify.app
|Before|After|
| --- | --- |
|  |  |

SmartHR UI v61.0.0に更新

---

src/content/articles/products/usability/usability-checklist.mdx

チェ活会KR2で整理した内容を踏まえてチェックリストを最新化したい
- 「達成基準」セクションを追加し、カテゴリごとの達成基準を追記
- 「基準の充足状況」列を「達成基準」列に変更し、↑にリンク
- チェック内容をアップデート（基準へのリンクを内容に含むようにした）
- その他
- HTMLタグで書いてた部分がマークダウンでかけるようになったので変更
- チェック手順はレビューがきたら全体的にアップデートします
- 情報設計のアウトプットもレビュードキュメントにぶら下げることを想定しているため、ここに含んでいません。
- Previewでみてね。
- https://deploy-preview-1393--smarthr-design-system.netlify.app/products/usability/usability-checklist/
|Before|After|
| --- | --- |
|  |  |

UIデザイン使用性チェックリストをアップデート

---

src/content/articles/products/usability/usability-checklist.mdx

-
- 
https://deploy-preview-1414--smarthr-design-system.netlify.app/products/usability/usability-checklist/
|Before|After|
| --- | --- |
|  |  |

使用性チェックリストの視覚的グルーピングに関するリンクを更新

---

public/_redirects

- 取り返しのつかない操作→ワンクッション必要な操作へのリダイレクト設定
- 
https://deploy-preview-1424--smarthr-design-system.netlify.app/products/design-patterns/irreversible-operation/ 
にアクセスして「ワンクッション必要な操作」に遷移すればOK
|Before|After|
| --- | --- |
|  |  |

取り返しのつかない操作→ワンクッション必要な操作へのリダイレクト設定

---

src/content/articles/products/design-patterns/confirmation-step/index.mdx

- 「ワンクッション必要な操作」にしたことで、いままでの「取り返しのつかない操作」だと気づかないので、経緯がわかるように記載した。
- 
- https://deploy-preview-1427--smarthr-design-system.netlify.app/products/design-patterns/confirmation-step/
|Before|After|
| --- | --- |
|  |  |

「取り返しのつかない操作」から「ワンクッション必要な操作」に変更した旨を記載

---

.github/CODEOWNERS

🔧: Astro 化に依る構成変更を CODEOWNERS に反映

---

package.json
pnpm-lock.yaml
src/content/articles/products/components/browser/index.mdx

- SmartHR UIのバージョンをv62.2.をに更新
- Browserコンポーネントのページを追加（中身はいったん空）
- 
|Before|After|
| --- | --- |
|  |  |

Update smarthr UI to v62.2.0

---

package.json
pnpm-lock.yaml
src/content/articles/products/components/combo-box/single-combo-box.mdx

⬆️: smarthr-ui を v62.2.3 に更新

---

public/smarthr-ui.css

smarthr-ui.cssが最新でなかったので更新しました
-
- 
https://deploy-preview-1459--smarthr-design-system.netlify.app/
|Before|After|
| --- | --- |
|  |  |

smarthr-ui v62.2.3に合わせてsmarthr-ui.cssを更新

---

package.json
pnpm-lock.yaml
public/smarthr-ui.css
src/content/articles/products/components/date-picker.mdx
src/content/articles/products/components/datetime-local-picker.mdx
src/content/articles/products/components/dropdown/filter-dropdown.mdx
src/content/articles/products/components/input/index.mdx
src/content/articles/products/components/month-picker.mdx
src/content/articles/products/components/time-picker.mdx
src/content/articles/products/components/wareki-picker.mdx

- smarthr-uiの更新
- WarekiPickerの追加
- DatePicker / DateTimeLocalPicker / MonthPicker / TimePickerの非推奨化
- AppHeaderの追加
- Inputで非推奨化されたPicker系コンポーネントを代替する方法の追記
https://deploy-preview-1473--smarthr-design-system.netlify.app/products/components/wareki-picker/
|Before|After|
| --- | --- |
|  |  |

smarthr-uiをv62.3.1へ更新

---

src/content/articles/products/components/text-link/index.mdx

- 使用上の注意の記載
- あわせて要素名の`a`タグに表記を揃えました
- 
|Before|After|
| --- | --- |
|  |  |

TextLinkをボタンとして使わない旨を記載

---

.github/CODEOWNERS

/products/配下であっても、ライティングページ（/src/content/articles/products/contents/配下）にはプロデザのApproveなしに変更を加えられるようにしたい
- 
- 
|Before|After|
| --- | --- |
|  |  |

CODEOWNERSを調整

---

package.json
pnpm-lock.yaml
public/smarthr-ui.css
src/content/articles/products/components/combo-box/multi-combo-box.mdx

https://kufuinc.slack.com/archives/C018J0A6DCH/p1737073697792699
- Smarthr UI v64.0.0にアップデート
- StoryのnameをMultiCombo(B)oxのbを大文字に変更
- 
https://deploy-preview-1490--smarthr-design-system.netlify.app/
|Before|After|
| --- | --- |
|  |  |

Smarthr UI v64.0.0にアップデート

---

package.json
pnpm-lock.yaml
public/smarthr-ui.css

-
- コンテンツの変更は特にしていません！
|Before|After|
| --- | --- |
|  |  |

smarthr-uiをv64.0.1に更新

---

package.json
pnpm-lock.yaml
public/smarthr-ui.css
src/content/articles/products/components/dialog/_components/DynamicStepFormDialog.tsx
src/content/articles/products/components/dialog/index.mdx
src/content/articles/products/components/dialog/step-form-dialog.mdx

- SmartHR UI をv65.2.0にアップデート
- [StepFormDialog](https://deploy-preview-1504--smarthr-design-system.netlify.app/products/components/dialog/step-form-dialog/)を追加
- [Dialog](https://deploy-preview-1504--smarthr-design-system.netlify.app/products/components/dialog/)ページに追加
- 
|Before|After|
| --- | --- |
|  |  |

SmartHR UI v65.2.0  update

---

src/content/articles/communication/capture/creation-guideline.mdx
src/content/articles/communication/sample/text/index.mdx

- ① サンプルテキストページに「[画面キャプチャ作成時の必須事項［2025年04月時点］](https://smarthr-inc.docbase.io/posts/3763976)」の導線を追加
- https://smarthr.atlassian.net/browse/SD-1072
- ② 画面キャプチャ 作成ガイドラインページに「[画面キャプチャの作成方法](https://smarthr-inc.docbase.io/posts/3580724)」の導線を追加
- https://smarthr.atlassian.net/browse/SD-1006
- ① サンプルテキストページに「[画面キャプチャ作成時の必須事項［2025年04月時点］](https://smarthr-inc.docbase.io/posts/3763976)」の導線を追加
- ② 画面キャプチャ 作成ガイドラインページに「[画面キャプチャの作成方法](https://smarthr-inc.docbase.io/posts/3580724)」の導線を追加
- ①・②それぞれ一部表記揺れを修正（キャプチャをご確認ください）
- Previewでみてね
- リンクが機能しているか確認してね
表記揺れを多用されている表現に修正
|Before|After|
| --- | --- |
| ![b-1](https://github.com/user-attachments/assets/7db9a5f6-9aee-4ccb-ae16-dd19d5fa293e) | ![a-1](https://github.com/user-attachments/assets/98383f89-9eda-43c3-acc2-14040d78c6c8) |
| …

サンプルテキストとキャプチャ作成方法のガイドラインを追加

---

package.json
pnpm-lock.yaml
public/smarthr-ui.css
src/content/articles/products/components/text-link/help-link/index.mdx

- Smarthr UI を v71.0.0 に更新
- HelpLinkのページを追加（TextLinkの配下に）
- HelpLinkのコンテンツ執筆
|Before|After|
| --- | --- |
|  |  |

Update smarthr UI to v71.0.0

---

src/content/articles/products/design-tokens/color.mdx

https://smarthr.atlassian.net/browse/SD-1099
- smarthr-uiには定義されているCHART_COLORSを色トークンに追加した
- https://github.com/kufu/smarthr-ui/blob/master/packages/smarthr-ui/src/constants.ts#L18 
- 営業資料では定義されている単色グラフ用の色を追加した
- 
https://deploy-preview-1654--smarthr-design-system.netlify.app/products/design-tokens/color/#h3-4
|Before|After|
| --- | --- |
|  |  |

チャート（グラフ）の色を追加

---

src/content/articles/products/design-patterns/wizard/index.mdx

Subtitleを使ったステップ表記にStepFormDialogコンポーネントが対応してくれたので、デザインシステム側の「未対応」の旨を削除しました。
SmartHR UI側：https://github.com/kufu/smarthr-ui/pull/5688
-
- 
|Before|After|
| --- | --- |
|  |  |

StepFormDialogの更新にあわせた記述変更

---

package.json
pnpm-lock.yaml

- smarthr-uiをv75.2.0に更新
- コンテンツの変更
previewを確認してください
|Before|After|
| --- | --- |
|  |  |

smarthr-uiをv75.2.0に更新

---

package.json
pnpm-lock.yaml
public/smarthr-ui.css
src/content/articles/products/components/button/index.mdx

Button[variant=tertiary] をちょちょっとしただけ。

⬆️: smarthr-ui を v75.3.0 に更新

---

package.json
pnpm-lock.yaml

- pnpm run upgrade:smarthr-uiで更新
- コンテンツの追加・修正など
|Before|After|
| --- | --- |
|  |  |

v75.3.2に追従

---

src/content/articles/communication/mock.mdx

モック合成ツール　Adobe Express版を作成したので、新たな方法として追記します。
https://smarthr.atlassian.net/browse/SD-1115
-「端末モック」ページに追記
- 同じページ内にあるデザインチームの体制の情報が古かったので、内容を修正
- 
https://deploy-preview-1723--smarthr-design-system.netlify.app/communication/mock/
|Before|After|
| --- | --- |
|  |  |

モック合成ツール AdobeExpress版を追記

---

package.json
pnpm-lock.yaml
public/smarthr-ui.css
src/content/articles/products/components/dialog/_components/DynamicStepFormDialog.tsx
src/content/articles/products/components/range-separator/index.mdx

- v75.4.1に更新
- DialogページでStepFormDialogが動作してなかったので変更
- RangeSeparatorを非推奨に変更
- 
- [Dialog(StepFormDialog)](https://deploy-preview-1728--smarthr-design-system.netlify.app/products/components/dialog/#h3-3)
- [RangeSeparator](https://deploy-preview-1728--smarthr-design-system.netlify.app/products/components/range-separator/)
|Before|After|
| --- | --- |
|  |  |

Update smarthr UI 75.4.1
